### ISSUE TITLE
[Suggestion] Making load points mutiple times clickable

### ISSUE THREAD

**Issue by Nevolox** [DevilXD/TwitchDropsMiner#10]
Literally the title ^^ It's kinda annoying to restart the miner to load points again

**Comment by DevilXD** [comment]
Hello o/

I know this isn't really mentioned anywhere, but the "Load Points" button is kinda "testing leftovers" that I felt like leaving for the release. It's actually specifically coded to disable itself after being clicked:

https://github.com/DevilXD/TwitchDropsMiner/blob/master/gui.py#L624-L627

The reason for this is quite simple - using it sends one request per tracked channel to Twitch, which means that you can end up sending up to 398 requests at once. From the Twitch dev perspective, this counts as literal API spam, and may end up getting your account (or IP) blocked from Twitch altogether. This means that the "Load Points" button's status is currently: "remove at the next good occasion", which is quite the opposite of me considering removing this restriction.

So, unfortunately, this is a Won't fix, and a note that the button may and will disappear in the future, possibly to be replaced with a feature that won't be as spammy as it is now.
