### ISSUE TITLE
Drops marked as active when not

### ISSUE THREAD

**Issue by St3ph32** [DevilXD/TwitchDropsMiner#102]
This drop (and many more for this game) is marked as active when it's not.

![image1](https://user-images.githubusercontent.com/44477728/208301595-a6b38624-ddeb-473b-97d9-f272450d6f58.png)

![image2](https://user-images.githubusercontent.com/44477728/208301608-d43de21f-c148-4153-9355-683242abc652.png)

I don't know if it's supposed to work like this, in that case I apologise.

**Comment by DevilXD** [comment]
That's the campaign being "marked" as active, yes. The "active" state is given to a campaign that has it's `starts_at` attribute in the past, and `ends_at` attribute in the future, meaning that the current time is strictly between the start and end of the campaign's timeframe.

However, drops can have their own timeframe as well, and thus come with their own `starts_at` and `ends_at` attributes - same logic applies. While drops usually have the same start and end timestamps as the campaign, they're not required to do so, and that's what happened in this exact case. Here are the campaign and drop timestamps:

```py
# Campaign:
starts_at: "2022-12-17T01:00:00Z"
ends_at: "2022-12-19T10:00:00Z"

# Drop:
starts_at: 2022-12-17T01:00:00Z
ends_at: 2022-12-17T02:00:00Z
```

As you can see, the drop was active for only 1 hour out of the 57 hours the campaign was active for. Same thing happened in #77, and it's not a bug, just the way Twitch decided to do things. The miner already takes care of checking the timeframe is correct for you, and won't mine a drop if it's outside of it's assigned timeframe.

Side note: Drops that can be mined display "X% of Y minutes", while ones that can't display just "Y minutes". You can see the drop from your pic can't be mined.
