### ISSUE TITLE
Add AndroidTV login method

### ISSUE THREAD

**Issue by aeongdesu** [DevilXD/TwitchDropsMiner#104]
According to https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/issues/94, we can login another method! (oauth2)

claiming drops also works as well 😊

**Comment by DevilXD** [comment]
Hi o/

I'm not familiar with any of these. It looks like an OAuth2 authorization flow, which requires you to login *before* authorizing a device, meaning that - while it is a way to obtain an authorization token - you need to be logged in already to do that. Have you tried doing all of that while being logged out?

If claiming drops works with an OAuth2 token, then one could just create their own application, authorize it the "legit" way (via browser, no need to implement anything besides verifying the authorization token is still valid) like any other app, and then use that. Unless this Smart TV token is special in some way, where it'd allow claiming drops while a 3rd party application would be denied.

**Comment by aeongdesu** [comment]
\o
I don't know if I understand your comment, but... this method works when other clients enter and authenticate from `twitch.tv/activate` (so check if it's authenticated through `id.twitch.tv/oauth2/token` every 5 seconds)

```
tv: get user code, and inform user of user code
me: enter user code and authenticate from twitch.tv/activate on my phone or computer etc
tv: authenticated and succeeded, try to get token

```

and with a custom OAuth2 app, I guess it won't work unless it's something special like SmartTV token

**Comment by DevilXD** [comment]
Your flow is missing a step before the first one:

```
me: you have to login into the twitch website from your browser
tv: get user code, and inform user of user code
...
```

This login step is exactly what I'm referring to here - the user has to be already logged in for this to work, otherwise when you go to the https://www.twitch.tv/activate website, enter the code and click on "Activate", it'll prompt you to login first.

The good news is that this login step can be handled by a user and their normal browser, although it'd be cool to figure out how the login process works from the smart TV, to avoid dealing with the OAuth2 flow entirely. Also, I'd need to think of a way to handle the redirect URI, using a localhost URL and some kind of a quick server listener could work, but I'd need to test it.

I kinda ran out of drops to test on for this week, but will try to tinker around with the idea on the weekend, and hopefully resume testing around next Tuesday.

**Comment by DevilXD** [comment]
> it'd be cool to figure out how the login process works from the smart TV, to avoid dealing with the OAuth2 flow entirely

A quick test to this (replacing the client ID and user agent with Smart TV ones) gives me a 5023 and implies the same protected login endpoint is used instead. Will continue testing on the weekend.

**Comment by DevilXD** [comment]
Had a not-so-busy day today for a chance: https://github.com/DevilXD/TwitchDropsMiner/commit/3892dfe59e8835486966cd668c9e128c36b7cd95

The OAuth2 validation endpoint returns `expires_in` at `0`, meaning the `refresh_token` can be ignored and this token should never expire, unless one removes "Twitch for TV" from their connections of course. That can be found here, in the "Other connections" section: https://www.twitch.tv/settings/connections, and will appear only if you actually authorize the "device" (miner in this case) of course. Can't confirm if this can claim drops yet, but it was able to successfully load the inventory and check status of 100+ channels with no errors, so hopefully it will.

@aeongdesu Feel free to test and see if that's what you've meant / wanted.

@rdavydov Feel free to take a look at the code. Again, no integrity is added or used here, android login required no integrity, and I hope this one doesn't do so as well. You're free to implement the same logic ofc, please just don't steal the same code 1-to-1 🙂 I'm using aiohttp an an already-made system to expire a request you'll probably need to figure out (or ignore as the expiration time is half an hour), so it'll require some big changes from your side anyway. I recommend same headers though.

**Comment by aeongdesu** [comment]
That's what I wanted and it works, Thank you! :)
