### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by shen890208** [DevilXD/TwitchDropsMiner#109]
How to modify an unbound account in the source code can also automatically enter the live broadcast room
![微信截图_20221225224236](https://user-images.githubusercontent.com/120549339/209472419-9990e3a2-5924-4524-9601-10fd0496f127.png)

**Comment by DevilXD** [comment]
Hello o/

Unfortunately, I don't support "unbound account", nor are willing to provide any instructions on how to circumvent it. Your account needs to be linked to a campaign to be able to mine it - period and no further discussion is needed here. For more context on this stance, please see: #84
