### ISSUE TITLE
[Feature] Re-Pickup Drop Mining

### ISSUE THREAD

**Issue by p-rintz** [DevilXD/TwitchDropsMiner#11]
Hi there,

thanks for the program again. Its working really well so far since version 10.

One feature Id love to see is that the program will pickup new campaigns without needing to be restarted when it has finished all drops.

Right now the program will stop mining the drops and need to be closed and started again when it finishes all campaigns it has seen during restart.

**Comment by DevilXD** [comment]
Hello o/

Yes, this so called "infinite mining" mode was somewhere in my plans. The part of the code that's responsible for refreshing the inventory is currently tied to the watch loop (and runs every 60 cycles, so every hour), meaning that if there's no channels being watched, no inventory will be refreshed. I should be able to remedy this by moving it into it's own task that won't have to rely on a channel being watched, and then the rest of the machinery should be able to pick it up from there - when the inventory is refreshed, it tries to select a game if there isn't one selected already, so it should work.

I'll try to make it a part of `v11` in the nearest future.

**Comment by DevilXD** [comment]
This is now available in `v11`: https://github.com/DevilXD/TwitchDropsMiner/releases
