### ISSUE TITLE
[Feature Request] Is it posible, to make it for docker?

### ISSUE THREAD

**Issue by Chase-V** [DevilXD/TwitchDropsMiner#111]
It would be perfect.

**Comment by DevilXD** [comment]
Hello o/

Not sure why you'd need to use Docker for this at all - this is a personal miner, meant to be ran whenever you're using your PC only. Not as something running 24/7 on some kind of a server. If you want a Docker container, you'll have to make your own - all building instructions can be found here: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running
