### ISSUE TITLE
Request to move drop time

### ISSUE THREAD

**Issue by spaumx** [DevilXD/TwitchDropsMiner#112]
The readme says that you send a request 1 time per minute to advance the drop time, can you tell me what kind of request this is?

**Comment by DevilXD** [comment]
It's a base64-encoded JSON payload, sent to whatever Spade URL your account is assigned to at the time.

Why do you need that though, and what do you mean by "move drop time"? The drops cannot be advanced more often than once per minute, sending requests more frequently will just result in the same drop progress being returned multiple times, making it appear "stuck in place".
