### ISSUE TITLE
[Feature Request] Show start date for next drop in the same campaign in inventory

### ISSUE THREAD

**Issue by Eniff** [DevilXD/TwitchDropsMiner#126]
Some campaigns have different start dates for the drops inside them and I believe it would be a useful addition the include the progress start date in the inventory tab for the next unclaimed drop that is yet unavailable.

**Comment by DevilXD** [comment]
Hello o/

This sounds reasonable, but it goes both ways - some drops can end before the campaign does as well, and that's where one has to display two rows of information: end date and progress. I don't really want to "bloat" the inventory screen with two rows under reach drop, so if anything, this addition would have to be subtle.

Maybe something like this: the progress is displayed as usual, for drops that can be earned/progressed. If they can't be progressed yet, the label will display a starting date instead. If the end date would differ from the campaign's end date, the progress text will change to an alternative text showing said date, upon mouse over. Sounds good?

**Comment by Eniff** [comment]
Hello,

Yes, that sounds good. I also don't want to bloat the interface, if it can be implemented without taking up more space with only updating the already present date box, as you suggest, that would be great.

Thanks for your work, this application is really practical!

**Comment by DevilXD** [comment]
A poor man's version of this feature was actually implemented at the beginning of June 2023, but at the time, I had a work-related project coming up that needed my attention more, so this feature was left quite unfinished. 15 months later though, I've decided to revisit this topic and finish it properly.

https://github.com/DevilXD/TwitchDropsMiner/commit/66c361103fc2d8c0a93ef875976c7fb4244968d5 implements the new display, if the start or end times differ, they will be shown underneath the drop's progress on the inventory tab.
