### ISSUE TITLE
[Feature Request] Valorant Drops

### ISSUE THREAD

**Issue by t4bletop** [DevilXD/TwitchDropsMiner#129]
Riot Games has many Twitch Drops events for Valorant, would it be possible to add Valorant Twitch Drop campaigns to the miner? Thank you!

**Comment by DevilXD** [comment]
Hello o/

Any campaign that's available on the https://www.twitch.tv/drops/campaigns page should be visible in the application, assuming you've added it's game to the priority list, linked your account, haven't excluded it and reloaded the application state. If you'd like them to appear in the inventory overview tab, you'd need to setup the filters properly: tick everything and untick "linked only", hit Refresh, then search for the campaign you want.

Please let me know if this solves your issue.

**Comment by DevilXD** [comment]
I'm assuming my previous message solves this.
