### ISSUE TITLE
Expand the tray icon tooltip box if possible

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#130]
![image](https://user-images.githubusercontent.com/7162375/218022617-b5501579-dec4-4f77-932b-9df8d7c4096c.png)

Currently it's somewhat hard to read, and it's very useful since it saves a TON of clicks.

**Comment by DevilXD** [comment]
Unfortunately, I don't have any control over the size of the tooltip box, only it's contents. In your case, you have to very long strings: "Marbles on Stream" as the game name, and "5 Community Coins" as the drop reward name, and it simply wraps the words beyond the new lines I use. All I could really do is shorten the text and add `...` placeholders instead, but I think that's just going to look ugly, so it has to stay as is.
