### ISSUE TITLE
Request Function

### ISSUE THREAD

**Issue by 1003999458** [DevilXD/TwitchDropsMiner#133]
Is it possible to mine 2 games together at the same time？

**Comment by DevilXD** [comment]
Hello o/

It is a Twitch limitation to be able to progress drops using only one channel at a time. Multiple drops can be progressed, but only if that's possible via watching said single channel (for ex. multiple active campaigns for the same game). Attempting to watch two different channels, or even watching the same channel "twice", from two different places/devices, won't speed up or allow for multiple drops to be progressed.

You have to use the priority list to specify which one of the two games you'd like to progress first.

Does this answer your question?

**Comment by DevilXD** [comment]
It's been two weeks and no answer has been given, so I'm assuming it does and this can be closed now.
