### ISSUE TITLE
Ramdisk causes an error

### ISSUE THREAD

**Issue by RouRouX** [DevilXD/TwitchDropsMiner#140]
![image](https://user-images.githubusercontent.com/21698543/220026102-25ca1d98-da59-4c3f-94bb-da61d4ca6fa4.png)
version  v15

V14 works well
V15 does not work

**Comment by RouRouX** [comment]
函数不正确
Incorrect function

**Comment by DevilXD** [comment]
Hello o/

Are you building the application yourself, or using the one from the official releases?

**Comment by RouRouX** [comment]
> Hello o/
> 
> Are you building the application yourself, or using the one from the official releases?

official releases   
https://github.com/DevilXD/TwitchDropsMiner/releases

**Comment by Walter-o** [comment]
Try fully extracting the program before running it.

The error message referencing `T:\\TEMP` seems to suggest it is extracting the program live and that sometimes doesn't go well.

**Comment by RouRouX** [comment]
My friend also uses win server 2022. It works normally and is not a problem with the system.
I also try to find out my own reasons again. If I solve it, I will reply here.

**Comment by RouRouX** [comment]
Problem solved
reason:
I used ramdisk software, and the temp directory is memory virtual.
After setting the following options, the error report disappears.

![image](https://user-images.githubusercontent.com/21698543/221088896-dd230c49-a0f6-4969-b30a-586853db3392.png)
