### ISSUE TITLE
Fatal Error Issue 

### ISSUE THREAD

**Issue by Stiphr** [DevilXD/TwitchDropsMiner#143]
![image](https://user-images.githubusercontent.com/68784883/220220033-fddccbd0-a6b2-4c31-842f-c3f8463b1399.png)

Giving this error (Random timing)

System:
AWS RDP
Windows Server 2022

**Comment by GreenFox66** [comment]
I had the same problem on windows 10

**Comment by DevilXD** [comment]
This is a duplicate of #138.

**Comment by ZeorymerX** [comment]
the same problem
