### ISSUE TITLE
Option to disable notifications it doesn't save changes

### ISSUE THREAD

**Issue by Shofuu** [DevilXD/TwitchDropsMiner#145]
Hello!
Maybe it's already a known problem, but I'll post it just in case. 🙂
Testing the latest dev version, when unchecking the new "Tray notifications" option and restarting the app, the option is checked again.

Workaround: Open the Settings.json file and manually change the `"tray_notifications": true"` line to `false` and save the changes.

**Comment by DevilXD** [comment]
Hello o/

That shouldn't happen, I'll look into it. Thank you reporting 🙂

**Comment by DevilXD** [comment]
Silly error on my side, I forgot to call get. Fixed in dev per https://github.com/DevilXD/TwitchDropsMiner/commit/dbc99376a51e0db3c23750640603597d9b1388f3.
