### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Kira-Ada** [DevilXD/TwitchDropsMiner#149]
Hi i'm dumb, can you guys help me with installing new language? i am stuck at the point of downloading file...

**Comment by DevilXD** [comment]
Hello o/

What exactly are you trying to do? This application comes with existing languages already included, are you trying to add a new one?

**Comment by Kira-Ada** [comment]
ah yes, today i saw some languages got updated and decided to try them out, didn't find how to download\install them manually, then i just downloaded latest version of app again and copy-pasted in the existing folder with file replacement. Or i should deleted cash\cookies files as well?

**Comment by DevilXD** [comment]
I mean, that could work. If you're not getting any errors, that should work. You only really needed to overwrite the language files, not the entire app - just so you know for the future.

Did you get it to work then?

**Comment by Kira-Ada** [comment]
Yeah that's what i tried to do, download lang files and i didn't find how to do that xd

and file replacement straight from altest .zip didn't really do anything so i checked the .zip and it has same languages with me (no turkish or russian languages), i mean it's not really necessary and i just wanted to check them out for fun xd but i just wonder what i do wrong..
![image](https://user-images.githubusercontent.com/115879318/221410609-e4290907-76fe-4be0-a3a8-102972a9f0b1.png)

**Comment by DevilXD** [comment]
I don't know what did you download, but if you want those two languages, you need to use the latest master. Pretty sure neither of these are available in the latest release, although I may be wrong. 

Try adding the language files from this zip: https://github.com/DevilXD/TwitchDropsMiner/archive/refs/heads/master.zip

**Comment by Kira-Ada** [comment]
ah that's why
yeah i downloaded latest release version of the app

thank you!

**Comment by DevilXD** [comment]
I'm assuming this one is solved by now.
