### ISSUE TITLE
next release?

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#156]
When can I get the new release? I found in the chrome extension that they already fixed the problem

**Comment by DevilXD** [comment]
Next official release will happen when it's ready. For now, you can use the source version, or compile your own executable per the guide: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

Does this answer your question, or do you need help with building it?

**Comment by matarife123** [comment]
yes, thank you very much, you do a great job
