### ISSUE TITLE
Problem with Host Proxy

### ISSUE THREAD

**Issue by Cairl** [DevilXD/TwitchDropsMiner#157]
I'm a user from China and I'm not very familiar with how the proxy works. Sometimes we use host proxy to access Twitch, and although this method works fine in the browser, it seems TwitchDropsMiner is unable to log in and use this method properly. I would like to hear your advice on this matter and would also like to thank you for creating such a useful tool.

**Comment by DevilXD** [comment]
Hello o/

Only the HTTP proxy is supported. If you're using a local proxy, the proxy url should look something like `http://127.0.01:XXXXX` where `XXXXX` is the port your HTTP proxy functions at. Are you using any particular proxy software?

**Comment by Cairl** [comment]
很感谢能得到回复，虽然我希望软件未来能支持更多代理模式，不过倒也不是必须的。目前除了希望尽快更新到新版本以解决报错问题之外，我没有其他所求了。给作者一个赞👍🏻
