### ISSUE TITLE
Can I open more than one client?

### ISSUE THREAD

**Issue by oneole** [DevilXD/TwitchDropsMiner#159]
i want to help my friends idle

**Comment by DevilXD** [comment]
There's discussion about this feature in #31. In general, it's technically possible, but it's not supported right now. The existing double run check is there to avoid launching the same instance twice, with the side effect of not allowing multiple separate instances either. If I can figure out a better way of dealing with accidental double launch, it may becomes simpler. For now, it has to stay.

**Comment by oneole** [comment]
Thank you
