### ISSUE TITLE
[Feature Ideas] Discord Webhook Integration, Streamer Watchlist, Easier install/start

### ISSUE THREAD

**Issue by yukaiin** [DevilXD/TwitchDropsMiner#161]
Hey, I was previously using [this](https://github.com/TychoTheTaco/Twitch-Drops-Bot) bot, which stopped getting updates. 
Would love to see your bot getting some of the features like the discord webhook or the streamer watchlist for auto claiming and watching community points from specific streamers. 
It's not like they are super important but it's definetly nice to have. 
Would also love to see an easier install. Had the old bot start with my raspberry pi which is basically impossible with your bot.

**Comment by DevilXD** [comment]
Hello o/

> discord webhook

Sounds cool, but not sure how that'd be needed here. Just use the application GUI to check on the progress instead?

> streamer watchlist for auto claiming and watching community points from specific streamers

See #128 and #70.

> Would also love to see an easier install. Had the old bot start with my raspberry pi which is basically impossible with your bot.

I think you've got it a little bit wrong. This project started specifically as a personal miner with a user-friendly GUI, for Windows only. Personal means it's for a single account only, where it launches together with your system to do the stream-keeping work for you, and then closes together with your system closing at the end of the day. Not designed for linux or any kind of a remote server (even though I've managed to somehow add linux support to it, by straight up disabling some windows-specific features), and not designed for 24/7 usage (even though it should hold out at least 24h non-stop runtime with no errors).

If you're looking for a console-based miner that you can run on a server, that may or may not already have the features you've mentioned here, try this one: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

**Comment by yukaiin** [comment]
Yeah i know I'm abusing it a little bit. I don't think there is a bot rn that is perfect for my use. I was running it for me and sometimes on friend on my raspberry pi 24/7. With the webhook integration I was able to track the earned drops on all my devices. 
But hey the bot got the basic feature I really need so I can't complain. Thanks for creating it you've done some good work. And maybe I try adding the streamer watchlist myself.

**Comment by DevilXD** [comment]
The one I linked has linux support, can do points-only watching and may have webhook integration, not sure on that last part. My miner has a nice GUI and is more user friendly, otherwise the two projects are pretty much the same.
