### ISSUE TITLE
Ignore Linked Account System

### ISSUE THREAD

**Issue by whyphyrl** [DevilXD/TwitchDropsMiner#162]
Is it possible to like ignore that the twitch  acc has to be link the the Drop's game? Like in this repo https://github.com/TychoTheTaco/Twitch-Drops-Bot 

so that it just farms every game even those i dont have atm but maybe in the future

**Comment by DevilXD** [comment]
This was already requested, and the answer is still "absolutely not". See #84 for an explanation.
