### ISSUE TITLE
Waiting for an ONLINE channel...

### ISSUE THREAD

**Issue by Zhanyee** [DevilXD/TwitchDropsMiner#166]
My bot don't recognize any online streams anymore. besides having a lot of channels online.

![image](https://user-images.githubusercontent.com/127443718/227280272-066f7448-3f0c-4537-b749-5cb4365bd131.png)

**Comment by DevilXD** [comment]
Hello there o/

That's weird. Have you tried restarting the application?

**Comment by Zhanyee** [comment]
> 

Yeah, I have downloaded it again, have updated it from the "setup" and "build", but anything has worked for around 2 hours. 
Now that the channel "Rainbow6" is online this is farming again, but the bot is not recognizing other channels.
But even when I had put Rainbow6 in the black list, the bot wasn't find any other channel for the other games.

**Comment by DevilXD** [comment]
> the bot wasn't find any other channel for the other games.

The application will only find channels for campaigns that can currently be progressed now or within the next hour. The progression conditions are:

- the campaign state is "active" or "upcoming" with less than 1 hour left on it's start time  
- the campaign status is "linked" and thus drops can be claimed  
- there's either an ACL added to the campaign, or at least one online channel with drops enabled available

Please try fiddling around with the Inventory tab filters to find the campaign you're interested in mining. When you do, ensure the first two of the points above apply. For a good measure, you can take a screenshot of the campaign and send it here for a double verify by me.

Also, please show me your entire Settings tab contents.

**Comment by LIL-JABA** [comment]
I have a similar issue

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/82034934/1f558eb2-79c1-44ff-871a-ccdd934bf3a2)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/82034934/24c9b359-6beb-49cc-8982-f6be691e1a55)
