### ISSUE TITLE
loyalty points

### ISSUE THREAD

**Issue by LemonStop** [DevilXD/TwitchDropsMiner#167]
hello, can i use this program to get loyalty points for a specific channel?
Even if they don't open the drop

**Comment by DevilXD** [comment]
Hello o/

I'm not entirely sure what you mean by "loyalty points". If you mean just the Channel Points, then the answer is yes and no.

Yes about them being earned while mining is in progress, no about the drop availability. This is a drops-focused application, where channel points are merely a convenience thing you're getting as a byproduct of mining, and that's where it ends. There's no plans to add any functionality that'd focus in getting the points without mining a drop at the same time.

Does this answer your question?
