### ISSUE TITLE
Is there a way to disable channel points in the app?

### ISSUE THREAD

**Issue by TeKno200** [DevilXD/TwitchDropsMiner#181]
Let me explain, it may sound strange but I would like to know if there is any way to not earn points with the application, most of the drops I receive are from channels that I don't usually watch and as I mentioned in other topics a 24/7 Console to earn channel points

**Comment by DevilXD** [comment]
Hello o/

The channel points are earned through the same mechanism that allows one to earn drops, so no - there is no way to avoid earning channel points entirely. You'd need to find a channel which has those disabled, and then only use that one for earning the drops. I'm not entirely sure if they can be disabled at all though.

The application will automatically claim the "bonus points" that appear every 15 minutes, that give +50 extra points each. But still, disabling this wouldn't prevent you from earning points at all, it'd just mean you earn less per whatever period of watching you go with.
