### ISSUE TITLE
[Bug report]Can't Automatically loot drops(GQL error)

### ISSUE THREAD

**Issue by Thomas-yz** [DevilXD/TwitchDropsMiner#183]
The error code was like:

_09:48:55: ERROR: Exception in task_
_09:48:55: Traceback (most recent call last):_
_09:48:55:   File "utils.py", line 96, in wrapper_
_09:48:55:   File "twitch.py", line 1332, in process_drops_
_09:48:55:   File "inventory.py", line 202, in claim_
_09:48:55:   File "inventory.py", line 120, in claim_
_09:48:55:   File "inventory.py", line 136, in claim_
_09:48:55:   File "twitch.py", line 1534, in gql_request_
_09:48:55: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]_

The game was like, I can loot infinite gifts for every 15 minutes I watch, but every 15 minutes, I have to click the same button to claim the reward. I wonder have you encountered this case yet, and I'm not sure if I misoperated the app, but there lies a bug anyway.

The game is called [Out Of The Park Baseball](https://www.twitch.tv/ootpdevelopments), not so popular.

**Comment by DevilXD** [comment]
There's literally a pinned issue about it, since 16th of February: #138

Use the dev build where this is already fixed, while waiting for the next release.

**Comment by Thomas-yz** [comment]
Many thanks, I'm trying your latest code.

**Comment by Thomas-yz** [comment]
It's now collecting drops automatically, many thanks.
