### ISSUE TITLE
Question: Channel-specific drops

### ISSUE THREAD

**Issue by Exolor** [DevilXD/TwitchDropsMiner#186]
Hello, Rust for example has generic drops (drops from every streamer that has them enabled) and streamer drops that you can get only from the specific streamer channel. 

Can the program handle this?
Thanks.

**Comment by DevilXD** [comment]
Hello o/

Yes, ACL (access control lists, as Twitch calls them) are supported. Each campaign has an ACL of channels the campaign can be progressed with, and when such a campaign is considered for mining, only those channels are used for that purpose.

The ACLs are displayed on the inventory tab, under "Allowed Channels". You can see that section on the picture from the README:

![pic](https://user-images.githubusercontent.com/4180725/164298315-81cae0d2-24a4-4822-a056-154fd763c284.png)
