### ISSUE TITLE
GQL stream tags are sometimes missing?

### ISSUE THREAD

**Issue by rhyskoedijk** [DevilXD/TwitchDropsMiner#193]
First of all, thanks for making this tool, it's been super helpful. :)

I've noticed that the GQL response doesn't include all stream tags for **_some_** channels.
For some channels it does, but others it doesn't. I ended up making a hacky workaround to get this to work for in the current Rust campaign by making ``Stream::drops_enabled`` check if `title` contains the text "drops" whenever `tags` doesn't contain the drops enabled tag. Ugly, but it works.

Do you have any idea as to what might be causing this? Is it a limitation of GQL itself?

Example: https://www.twitch.tv/hjune (only the "English" tag is detected)

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/123988/e5c59aa4-7845-4a93-9f92-27521c9c2c0e)

GQL response:
````json
{
    "data": {
        "user": {
            "id": "121111915",
            "profileURL": "https: //www.twitch.tv/hjune",
            "displayName": "hJune",
            "login": "hjune",
            "profileImageURL": "https://static-cdn.jtvnw.net/jtv_user_pictures/7610c39060476845-profile_image-150x150.png",
            "broadcastSettings": {
                "id": "121111915",
                "title": "[DROPS] CLONE LOCKER - THE BIG DAY !drops !rivals !rustoria !leaderboard !newvid !tiktok !youtube !hjune2",
                "game": {
                    "id": "263490",
                    "displayName": "Rust",
                    "name": "Rust",
                    "__typename": "Game"
                },
                "__typename": "BroadcastSettings"
            },
            "stream": {
                "id": "42199747531",
                "viewersCount": 28429,
                "tags": [
                    {
                        "id": "6ea6bca4-4712-4ab9-a906-e3336a9d8039",
                        "localizedName": "English",
                        "__typename": "Tag"
                    }
                ],
                "__typename": "Stream"
            },
            "__typename": "User"
        }
    },
    "extensions": {
        "durationMilliseconds": 60,
        "operationName": "VideoPlayerStreamInfoOverlayChannel",
        "requestID": "01H0MA3SHQ5WZMWM8VZN1RRA15"
    }
}
````

**Comment by DevilXD** [comment]
Hello o/

Please see #189 for more discussion on this matter. I ended up pushing a temporary fix, but the core issue is in the missing tags as you found, yes. I'm closing this as a duplicate, but please feel free to direct all your findings to that issue instead.
