### ISSUE TITLE
No available channels to watch. Waiting for an ONLINE channel...

### ISSUE THREAD

**Issue by ThaxTen** [DevilXD/TwitchDropsMiner#194]
As a yesterday Rust drops has been started i just setup the program it was working for first 5 item then its just stops automaticly i couldnt understand why all the channels is online but underneath of the drop icon there is cross could you please help me??
![asfwrfg](https://github.com/DevilXD/TwitchDropsMiner/assets/133902142/2e948200-9070-46aa-a6b9-bd3601aa6410)
![safasf](https://github.com/DevilXD/TwitchDropsMiner/assets/133902142/a4413076-43d2-43e9-af21-25344b9031c8)
![asfwd](https://github.com/DevilXD/TwitchDropsMiner/assets/133902142/5cc6fedf-4a0b-49d7-8426-835dc53cd6b9)

**Comment by Stxtics** [comment]
Same issue here, have tried clearing cache and cookies.

**Comment by Stiphr** [comment]
Compile and use new master build

**Comment by DevilXD** [comment]
This is a duplicate of #189, please check out the discussion there.
