### ISSUE TITLE
Says "Waiting for an ONLINE channel..."

### ISSUE THREAD

**Issue by killsinful** [DevilXD/TwitchDropsMiner#196]
![Screenshot 2023-05-17 135640](https://github.com/DevilXD/TwitchDropsMiner/assets/74270447/de36d152-5412-46cd-a6fc-2fb42f5d0de2)

**Comment by DevilXD** [comment]
Please, this is like the 10th issue I'm closing as a duplicate. Check for existing ones before you make a new one: #189.
