### ISSUE TITLE
cant claim twitch drop.

### ISSUE THREAD

**Issue by hadesboy7** [DevilXD/TwitchDropsMiner#201]
cant claim drop then bot stopped.

**Comment by hadesboy7** [comment]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/122109712/0a58efdc-bfe5-4204-b1eb-91db38a58f63)

**Comment by DevilXD** [comment]
Hello o/

I'll need to see the whole traceback to be able to help you. But before you do that, please ensure this isn't related to #138 or #189, as those have an already existing issue tracker, and this issue would thus be a yet another duplicate I'll have to close.
