### ISSUE TITLE
No available channels to watch. Waiting for an ONLINE channel...

### ISSUE THREAD

**Issue by Anerostel** [DevilXD/TwitchDropsMiner#202]
Miner will show "No available channels to watch. Waiting for an ONLINE channel..." in the output, even though the channel that is associated with the campaign is online and streaming. 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134044599/14e4c69c-e64a-4918-bbc8-bfd5c6003b2b)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134044599/e2f9ec7f-7b6f-48c5-abfe-57f004721c10)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/134044599/e5df5f79-6e5c-4713-a95a-bb3071ad2d1c)

**Comment by DevilXD** [comment]
This is a duplicate of #189.
