### ISSUE TITLE
System freezing

### ISSUE THREAD

**Issue by nwvh** [DevilXD/TwitchDropsMiner#211]
Hello, when I turned on Run on system startup and rebooted, the system became unusable for like 5 minutes. Everything was so slow, apps didn't opened and all I could do was to wait and stop the application. After that it stopped.

OS: Win 10 x64
RAM: 16G
GPU: 1050ti
CPU: i5 7th gen 4c/4t

**Comment by DevilXD** [comment]
Hello o/

Without any logs, I am unable to diagnose your issue. Does this happen only on system startup, and not when running it normally? Please try adding a `--log` and `-vvv` as run options and then post the resulting `log.txt` file, that should be created next to the executable.

Also, I'll need the exact version of the application you're running. The version is displayed in the application's window title bar.

**Comment by DevilXD** [comment]
Since no further information was provided, I'm closing this.
