### ISSUE TITLE
[Feature Request]Multiple accounts

### ISSUE THREAD

**Issue by Suz1e** [DevilXD/TwitchDropsMiner#22]
I have used your software and it feels great, but I have several Twitch accounts and there is no way to do it at the same time, can you add a few more accounts together?

**Comment by DevilXD** [comment]
Hello o/

You should be able to just launch multiple instances of the application, by putting the executable in separate folders (so they end up with separate cookies file). If no more than one instance would start, you can try adding a `--no-run-check` command line switch, to disable the duplicate instance check. There's currently no plans to add multi-account support for now, but this issue can remain open, in case others would like to chime in on the matter.

**Comment by Suz1e** [comment]
thanks, i'll try it

**Comment by Suz1e** [comment]
How to add command line switches

**Comment by DevilXD** [comment]
Command line parameters can be provided via a simple shortcut. Just create a shortcut to each executable in each folder, and add the parameter after the path. Here's a simple guide that explains it better: https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/

**Comment by Suz1e** [comment]
![QQ截图20220619100021](https://user-images.githubusercontent.com/52779408/174462785-2af7c7a3-0f27-432e-9a38-f114c24624d9.png)
![QQ截图20220619100034](https://user-images.githubusercontent.com/52779408/174462786-f5fa3e20-269c-44b4-a5bf-52d35d50a92f.png)
I set the parameters （-no-run-check）, but it prompts an error

**Comment by DevilXD** [comment]
It's `--no-run-check` - notice the double dash at the beginning. Yours has only one, thus it doesn't work.
