### ISSUE TITLE
saying no active campaigns when i linked them allready and they are active

### ISSUE THREAD

**Issue by Glox2kk** [DevilXD/TwitchDropsMiner#223]

**Comment by DevilXD** [comment]
Hello o/

What exactly is your issue? It's hard to tell, there's not much description to it.

**Comment by Glox2kk** [comment]
so wheni run it just tells me that there are no active campions and there are active campions for rust and i link my twitch and rust and all that and it keeps giving me the messge there are no active campions

**Comment by Glox2kk** [comment]
it keeps this messge No active campaigns to mine drops for. Waiting for an active campaign..

**Comment by Glox2kk** [comment]
but link it and all that

**Comment by DevilXD** [comment]
Please check out #208, #203 and #198, to see if the steps and explanations provided there could help resolve your issue.

**Comment by DevilXD** [comment]
I'm assuming this can be considered resolved now.
