### ISSUE TITLE
Cannot connect to Twitch

### ISSUE THREAD

**Issue by zelda0079** [DevilXD/TwitchDropsMiner#224]
https://i.imgur.com/3CR4FJW.png
Sometime cannot connect to twitch, and the gift icon shows all is "X".

**Comment by DevilXD** [comment]
Hello o/

The gift icon can be ignored for now, as I can see you're using the "after temp fix" v16 version. There's nothing much I can help here, as that error message will pop up if your PC is currently having internet connection problems. I am not responsible for the quality or availability of your internet connection. Sometimes, a firewall on your PC can be blocking the connection too. There may be multiple causes of this.

Are you using a VPN? Proxy? Do you need to login to your internet connection? If you're using a laptop, even something as simple as turning off WiFi or being too far from the router can cause connection issues and this message to appear. It's perfectly normal.

**Comment by zelda0079** [comment]
> Hello o/
> 
> The gift icon can be ignored for now, as I can see you're using the "after temp fix" v16 version. There's nothing much I can help here, as that error message will pop up if your PC is currently having internet connection problems. I am not responsible for the quality or availability of your internet connection. Sometimes, a firewall on your PC can be blocking the connection too. There may be multiple causes of this.
> 
> Are you using a VPN? Proxy? Do you need to login to your internet connection? If you're using a laptop, even something as simple as turning off WiFi or being too far from the router can cause connection issues and this message to appear. It's perfectly normal.

No VPN and no proxy, I use wifi but other connection is working normally.
You can see the screenshot, the miner try so many time in one second.

**Comment by DevilXD** [comment]
> the miner try so many time in one second.

There are cases where this may happen, but they all have the same cause - unstable connection. There's nothing I can do to help here, I'm not responsible for your internet connection availability.

**Comment by deathart** [comment]
Hello i am same problème and my connection is perfect, i have this probleme since 2-3 days, before i am not this problème.

Sorry for my english

**Comment by DevilXD** [comment]
Please try launching the miner with `-vvv --log` options, wait for it to get into the problem state, then post the resulting `log.txt` here.

**Comment by zelda0079** [comment]
> 請嘗試使用選項啟動礦工`-vvv --log`，等待它進入問題狀態，然後`log.txt`在此處發布結果。



> -vvv --log

I don't know why, no this issue today.

**Comment by lnx00** [comment]
I just had the same issue, but it fixed itself after restarting the miner 2 times.

This was pretty weird though, since I doubt that it was caused by my internet connection. I have a stable ethernet connection (Uncensored, No VPN/Proxy and nothing else that could affect the connection) and visiting twitch on a browser worked fine too.

**Comment by DevilXD** [comment]
Since there's no further issues, this can be closed now.
