### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by Nollasko** [DevilXD/TwitchDropsMiner#225]
sup, need help with ukrainian translation?

**Comment by DevilXD** [comment]
Hello o/

All translations are created by volunteers wanting to contribute to the project. If you'd like to contribute, you'd need to clone this repository, launch the application from source to let it create the default `English.json` translation, and then translate all strings in it. The resulting translation can then be tested by running from source again and selecting the new translation file, and then a PR can be made to incorporate the translation into the project.

If all of this sounds too technical for you, I can also "manually" provide you the current `English.json` for translation purposes, which you can then translate and send back by attaching it as an attachment here. This skips the PR and testing phases, relying entirely on me to do the testing part of the translation, which I'm okay with, provided I can find the time for all of this (my time is quite scarce). The PR route would be significantly faster, but then again, I don't know how familiar you are with the tools and possibilities Github and git provide here.

**Comment by Nollasko** [comment]
I think I'm doing something wrong🤔
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/8c79569e-e1c1-49f0-a484-e97f1db2bf3d)

**Comment by Nollasko** [comment]
How do I test it? Changing language requires restart, but program always starts in english

**Comment by Nollasko** [comment]
How do I test it? Language changing requires restart, but program always starts in english

**Comment by Nollasko** [comment]
Here, .json can't be uploaded here

[Українська.txt](https://github.com/DevilXD/TwitchDropsMiner/files/11763836/default.txt)
