### ISSUE TITLE
Linux

### ISSUE THREAD

**Issue by Tsprnay** [DevilXD/TwitchDropsMiner#228]
is there a way launch on linux ? without graphical environment

**Comment by DevilXD** [comment]
Without graphical environment? No, there's none. This is a standard user application you can launch, use and interact with. For more information, please see the project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

Does this answer your question?

**Comment by Tsprnay** [comment]
that would be great if you add no graphical environment function. Like i can do all my settings on my pc and then move it to linux with all settings

**Comment by DevilXD** [comment]
Neither that, nor moving between systems is currently supported, and never will be. The project goals clearly state why it will never be possible.

I think this is clear now - if not, please reread the project goals.
