### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by hakutzu** [DevilXD/TwitchDropsMiner#236]
Is there any way to update if there's any changes after you git clone and build the app yourself?

**Comment by guihkx** [comment]
You can run `git pull` to get the latest changes from here.

**Comment by hakutzu** [comment]
Thank you, Didn't know that, Appreciate it, Have a great week!

**Comment by DevilXD** [comment]
Newest master branch builds are also available in https://github.com/DevilXD/TwitchDropsMiner/releases, as a pre-release.

Sure, enjoy :slightly_smiling_face:
