### ISSUE TITLE
ValueError: Namespace DBus not available

### ISSUE THREAD

**Issue by JustCauseWhyNot** [DevilXD/TwitchDropsMiner#239]
Log <details> 
```
❯ ./Twitch\ Drops\ Miner\ \(by\ DevilXD\)
Traceback (most recent call last):
  File "main.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "twitch.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "gui.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pystray/__init__.py", line 64, in <module>
  File "pystray/__init__.py", line 56, in backend
  File "pystray/__init__.py", line 28, in appindicator
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pystray/_appindicator.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pystray/_util/gtk.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pystray/_util/notify_dbus.py", line 24, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace DBus not available
[8386] Failed to execute script 'main' due to unhandled exception!
```
</details>
I'm running gentoo if that makes any difference. Not sure what I'm supposed to do.

**Comment by guihkx** [comment]
The system tray icon feature needs dbus to work (it uses AppIndicator). Do you have dbus installed at all?

Maybe you can try tweaking the [`PYSTRAY_BACKEND` environment variable](https://pystray.readthedocs.io/en/latest/usage.html#selecting-a-backend) to use a system tray implementation other than `appindicator`.

**Comment by JustCauseWhyNot** [comment]
Interesting it still doesn't work after installing libappindicator, and libayatana-appindicator. I'll see if I can get the `PYSTRAY_BACKEND` variable set, and if that'll fix the issue. And yes I do have dbus installed.

**Comment by JustCauseWhyNot** [comment]
It did work when I set `❯ env PYSTRAY_BACKEND=xorg ./.local/bin/Twitch\ Drops\ Miner/Twitch\ Drops\ Miner\ \(by\ DevilXD\)`. Thank you for your help!

**Comment by JustCauseWhyNot** [comment]
Side question. Am I boned if I disconnected a game from my twitch account, and now can't reconnect due to a 30 day wait limit especially since the drop I want to get is on July 2nd? I've contacted the games support so hopefully they can help me, but not holding my breath. Just curious if you'd have any idea on how screwed I am. Thank you for this awesome program!

**Comment by guihkx** [comment]
> Interesting it still doesn't work after installing libappindicator

That library is actually included in the final binary created by PyInstaller, so installing them in your machine shouldn't be needed.

> And yes I do have dbus installed.

Now that surprises me. I guess it's probably related to a different, missing dependency then... Ugh.

> It did work when I set `❯ env PYSTRAY_BACKEND=xorg ./.local/bin/Twitch\ Drops\ Miner/Twitch\ Drops\ Miner\ \(by\ DevilXD\)`. Thank you for your help!

That's great, but keep in mind that some features of the app (e.g. system tray support, desktop notifications), might be heavily limited by the Xorg backend.

I've been experimenting with an AppImage package of the app, so if you want to give it a shot you can grab the latest build [from here](https://github.com/guihkx/TwitchDropsMiner/actions/runs/5347993782) (download the `Twitch.Drops.Miner.Linux.AppImage` artifact at the bottom of the page).

If you want to inspect the changes, they are in my [appimage](https://github.com/guihkx/TwitchDropsMiner/tree/appimage) branch.

>Side question. Am I boned if I disconnected

Sorry, no clue about that one...

**Comment by JustCauseWhyNot** [comment]
>That library is actually [already included](https://github.com/DevilXD/TwitchDropsMiner/blob/a7c3925e53f211fc032dde169220b01b1e55d89a/build.spec#L47-L50) in the final binary created by PyInstaller, so installing them in your machine shouldn't be needed.

Well that does explain why installing them didn't make a difference.

>Now that surprises me. I guess it's probably related to a different, missing dependency then... Ugh. 

It could be a missing useflag somewhere as well. I'm assuming you don't know what useflags are for gentoo. They're just certain flags I can set through package manager (portage) on what gets built and what doesn't. So something prob didn't get built that's typically compiled through every other distros repos.

>That's great, but keep in mind that some features of the app (e.g. system tray support, desktop notifications), might be heavily limited by the Xorg backend

I'm using dwm, and haven't used a systray patch so I don't really mind not having that functionality. But it's good to know the possible shortcomings.

> I've been experimenting with an AppImage package of the app, so if you want to give it a shot you can grab the latest build [from here](https://github.com/guihkx/TwitchDropsMiner/actions/runs/5347993782) (download the Twitch.Drops.Miner.Linux.AppImage artifact at the bottom of the page).

I'll give it a shot potentially. The only reason I might not is that now that I got the current package working right now I might not end up needing to try out appimage. And I don't use any appimages on my pc. Not against them just haven't needed too yet.

>Sorry, no clue about that one...

No worries it was just a shot in the dark question just in case you did know.

**Comment by DevilXD** [comment]
> Am I boned if I disconnected a game from my twitch account, and now can't reconnect due to a 30 day wait limit

The answer to this is - probably. There's normally no need to disconnect an account, and even if so, reconnecting the same account should be possible to do so immediately. The 30 days delay is most likely caused by an attempt to connect a different account to the same game account, and exists because of the possibility of abuse. The linking requirement is one of those intentional things that try to limit said abuse, and applies even if you're not trying to do anything wrong.

For more of these "intentional things", please check out project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

**Comment by JustCauseWhyNot** [comment]
>The answer to this is - probably

I appreciate you saying that fr. I'm hoping the games support team can help me as I'm not even trying to link 2 different account but the same one. But oh well certainly not the end of the world.

>There's normally no need to disconnect an account, and even if so, reconnecting the same account should be possible to do so immediately

It does say when I try and re-link that the linking was successful, but in actuality it's not. And it is the same two accounts I'm trying to re-link. I disconnected due to [this issue](https://github.com/DevilXD/TwitchDropsMiner/issues/203#issuecomment-1555646195) I was having.

>The linking requirement is one of those intentional things that try to limit said abuse, and applies even if you're not trying to do anything wrong

All I want are some camos from a twitch drop. I'm certainly not trying to abuse anything.

**Comment by DevilXD** [comment]
If you're relinking the same account, it should work right away, without having to wait any amount of time.

Also, the miner has no real way to recognize abuse, so there's no way for me to change this. In all cases where you'd run into a linking issue where you have to wait 30 days, 90% of the time it's someone trying to do something funky. The remaining 10% you happened to find yourself in, has to just pay the price of the miner preventing funky things from happening, as it was designed to do.

**Comment by JustCauseWhyNot** [comment]
I was able to get the account relinked without the games support intervening. Not sure why it worked, but it pretty much just asked me to update twitch login, and it linked. It wasn't doing that before so idk what changed.
