### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Suz1e** [DevilXD/TwitchDropsMiner#24]
Hello, I'm a blogger, I want to discuss something with you, can you leave it on twitch or telegram?

**Comment by DevilXD** [comment]
Hello o/

I'm usually available via Discord at `DevilXD#4437`, but you can also message me via [my Twitch](https://www.twitch.tv/devilxd), yes. If none of these two would work for you, I can give you my email so you can send a message to me instead. Up to you.

**Comment by Suz1e** [comment]
i added yours Discord
