### ISSUE TITLE
BUG/HELP : App saying no available stream when stream are online

### ISSUE THREAD

**Issue by RoyaLProg** [DevilXD/TwitchDropsMiner#246]
![Screenshot_26](https://github.com/DevilXD/TwitchDropsMiner/assets/63088010/8b09cfb7-b493-4d78-9476-9a6420c798d4)

did i do something wrong ?

**Comment by RoyaLProg** [comment]
Also it say there is no drop when there is ?

**Comment by DevilXD** [comment]
Please see #245, as the same explanation applies here as well.
