### ISSUE TITLE
Windows thinks its a virus

### ISSUE THREAD

**Issue by Kimarnic** [DevilXD/TwitchDropsMiner#249]
I'm trying to use the latest development version and I cant use it because Windows thinks it's a virus
**0x800700E1 "File contains virus and cannot be copied"**
Last build date: 2023-07-05 19:48:43+00:00

**Comment by DevilXD** [comment]
This is a duplicate of #217. You'll have to use an antivirus that's more intelligent with it's detections, or build the dev version yourself.
