### ISSUE TITLE
Can't i replace the client_id with my client_id ?

### ISSUE THREAD

**Issue by TravelSir** [DevilXD/TwitchDropsMiner#252]
i register a twitch developer account, and create an application. so i replace the smartbox client_id with my client_id.
it can access oauth, but gql request response 401. plz tell me how to get the correct client_id.

**Comment by DevilXD** [comment]
Hello there o/

This project isn't built with `CLIENT_ID` replacement in mind. Specifically, changing anything about it will break everything. This isn't some kind of a Twitch API wrapper, and you cannot use a "developer account" `CLIENT_ID` in it,

What exactly are you trying to do?
