### ISSUE TITLE
Suggestion: Refresh Button for new campaigns

### ISSUE THREAD

**Issue by Diseraph** [DevilXD/TwitchDropsMiner#253]
Apologies if you arleady had something in place and I'm just blind. 

I noticed that the campaigns don't seem to automatically update in the Inventory until I press Reload in the Settings. I was wondering if there was a way to update the inventory without having to disconnect all the current drops, or have a time/date of when last synced. 

Also thank you very much all your hard work :) It is very appreciated!!

**Comment by DevilXD** [comment]
The inventory auto-updates itself every 60 minutes. The "Reload" button on the Settings tab, exists mainly to allow the changed settings to instantly apply, but can be used to manually trigger a reload as well, yes. There's no need to do so, as it's done automatically for you every 60 minutes anyway.

Does this answer your question?

**Comment by Diseraph** [comment]
yes this is fine. knowing it updates every hour helps a lot. thank you very much
