### ISSUE TITLE
 Why does the following error prompt appear when I open the code on vscode and run npm install, and some dependencies cannot be installed?

### ISSUE THREAD

**Issue by 1279494766** [DevilXD/TwitchDropsMiner#256]
PS C:\Users\Administrator\Desktop\2023.7.15\TwitchDropsMiner-master> npm i
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\Administrator\Desktop\2023.7.15\TwitchDropsMiner-master/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\Desktop\2023.7.15\TwitchDropsMiner-master\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Local\npm-cache\_logs\2023-07-22T00_53_49_480Z-debug-0.log
PS C:\Users\Administrator\Desktop\2023.7.15\TwitchDropsMiner-master>

**Comment by guihkx** [comment]
This is not an npm project.

Please read the official build instructions here: https://github.com/DevilXD/TwitchDropsMiner/wiki

**Comment by 1279494766** [comment]
Okay, thank you very much for your answer!
