### ISSUE TITLE
The inventory shows the game, but does not drop

### ISSUE THREAD

**Issue by LegendAdmin** [DevilXD/TwitchDropsMiner#26]
The log shows "No active campaigns to mine drops for. Waiting for an active campaign..."
![image](https://user-images.githubusercontent.com/29401874/176134202-9b65dec0-ea91-4d8a-9dc6-b2e08fb3e1aa.png)
![image](https://user-images.githubusercontent.com/29401874/176134359-8140d47a-8108-4be4-a744-19dea256d6e9.png)

**Comment by LegendAdmin** [comment]
Solved, it turns out that I need to add it manually in the settings myself.

**Comment by LegendAdmin** [comment]
> For `v12`, the "Priority Only" setting will start as unchecked, that'll make it mine all available campaigns by default (priority list will still be mined first tho). I can see that some kind of information pointing to the Setting tab would be useful.

After you said that I realized that the latest version I downloaded is `v11`, is `v12` a version under development?
But I see that the picture in the README is `v12`.

**Comment by DevilXD** [comment]
Yes, `v12` is currently still in development. It's available from the master repo branch, via "Advanced Usage" section of the README, although you'd need to either run it from source, or build the executable yourself though.
