### ISSUE TITLE
Feature Request: Disable Auto-Claiming of Drops

### ISSUE THREAD

**Issue by Paradox-77** [DevilXD/TwitchDropsMiner#262]
Is disabling auto-claim for drops possible? This way I could claim them when I wanted since the game I play activates the perks instantly.

**Comment by DevilXD** [comment]
Hello o/

An interesting suggestion. Just curious, which game / campaign does this happen for?

**Comment by Paradox-77** [comment]
The game in question is Albion Online, if you have an account with only one character (You can have 3 on the same account) it automatically redeems it to that char if you are online at the time it was claimed.

**Comment by DevilXD** [comment]
I see. The suggestion is fair, but v16 is already pretty packed on the amount of issues that need to be solved for it, so this will receive a low priority. But I'll add it eventually.

**Comment by Paradox-77** [comment]
Okay I understand, I'll make a PR myself if I have the time to do so.

**Comment by RheaAyase** [comment]
I don't see such an option, there are also campaigns that ask you to pick "one of n" claims - with auto claim you can't choose the preferred claim.

**Comment by DevilXD** [comment]
> there are also campaigns that ask you to pick "one of n" claims - with auto claim you can't choose the preferred claim.

This is the first time I'm hearing about such campaigns. If that's really a new kind of campaign and you'd like me to support it properly, please open a separate issue for it.
