### ISSUE TITLE
Drops show end time as start time

### ISSUE THREAD

**Issue by Bamboozul** [DevilXD/TwitchDropsMiner#265]
![Screenshot 2023-08-07 170441](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/8724f2c4-71c5-4bec-8546-59e8e4a7a00b)

![Screenshot 2023-08-07 170457](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/7cec4c88-0a41-42da-8178-389720f48d9e)

**Comment by DevilXD** [comment]
Hello o/

Which version of the application are you using? You seem to be using an older version, which could've had a bug with displaying those incorrectly. The current English translation uses just "Starts:" and "Ends:", without the "at" part added to it:
https://github.com/DevilXD/TwitchDropsMiner/blob/ab9a8312ce2b745ce81a10a2ecb2f1d1b9492ecd/translate.py#L349-L350

Please ensure you have the latest version (dev or pre-release) and see if it still happens there.

**Comment by Bamboozul** [comment]
> Hello o/
> 
> Which version of the application are you using? You seem to be using an older version, which could've had a bug with displaying those incorrectly. The current English translation uses just "Starts:" and "Ends:", without the "at" part added to it:
> 
> https://github.com/DevilXD/TwitchDropsMiner/blob/ab9a8312ce2b745ce81a10a2ecb2f1d1b9492ecd/translate.py#L349-L350
> 
> Please ensure you have the latest version (dev or pre-release) and see if it still happens there.

I'm using the latest dev version "Twitch Drops Miner v16.dev.ab9a831 (by DevilXD)"

![Screenshot 2023-08-07 205506](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/c1984280-8a1a-4c3a-84bc-2007c80e6a90)

**Comment by DevilXD** [comment]
Hmm, actually, nevermind. This is a WIP feature from #126, and it does not have a translation key (yet). The strings are hardcoded, and the "ends" string also happen to say "Starts at":
https://github.com/DevilXD/TwitchDropsMiner/blob/ab9a8312ce2b745ce81a10a2ecb2f1d1b9492ecd/gui.py#L1431-L1433

This is a trivial fix, at least naming-wise.

**Comment by DevilXD** [comment]
https://github.com/DevilXD/TwitchDropsMiner/commit/137f540d62560524a9a511a7793616e6d4478e68

Please try out the latest master.

**Comment by Bamboozul** [comment]
> [137f540](https://github.com/DevilXD/TwitchDropsMiner/commit/137f540d62560524a9a511a7793616e6d4478e68)
> 
> Please try out the latest master.

Perfect.

![Screenshot 2023-08-07 210816](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/f51019c3-5316-4b6e-aeda-88796a7ab889)
