### ISSUE TITLE
No available channels to watch. Waiting for an ONLINE channel...

### ISSUE THREAD

**Issue by Malu007-YT** [DevilXD/TwitchDropsMiner#269]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/106349326/a9eefdba-a522-45ad-adca-2b99252c2bd1)

**Comment by Malu007-YT** [comment]
?__?

**Comment by Diekion** [comment]
It does not work with the current Rocket League campaign. 🤷‍♂️
I use the latest from Dev from a few days ago.
One to get manually, it's a few days.

**Comment by Malu007-YT** [comment]
I tried multiple times without success, but I found another method to do what I wanted ;) thank you very much the same

**Comment by DevilXD** [comment]
v15 isn't stable anymore since February this year. Use latest master branch code, build your own executable, or use the pre-built pre-release version available on the Releases tab.
