### ISSUE TITLE
Windows Defender detects "Bearfoos.A!ml" trojan and quarantines it

### ISSUE THREAD

**Issue by mashirochan** [DevilXD/TwitchDropsMiner#270]
I know next to nothing about computer security, so I'm not quite sure what exactly any of this means, except that any sort of web-connected automation programs are frequently tagged as viruses. Is this another one of those cases..?

I've been using the program for a couple days now, running it on startup minimized to the tray, and it was working fine with no issues. Today, however, as soon as I booted up my computer, Windows Defender flagged it as a trojan and quarantined it. No other viruses are found on my system with multiple scans.

![ApplicationFrameHost_vB4QCUeMBm](https://github.com/DevilXD/TwitchDropsMiner/assets/11561006/9be0d91a-ce46-4b82-b647-06e4bd5a8940)

**Comment by DevilXD** [comment]
This is a duplicate of #13, #137, #209, #217 and #249. You can refer to either of them for an explanation, nothing changed in that regard.
