### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by Bamboozul** [DevilXD/TwitchDropsMiner#271]
I'm trying to test the Arabic translation, but the app failed to load after I logged in.

```
Traceback (most recent call last):
21:58:58:   File "D:\User\Downloads\Compressed\TwitchDropsMiner\main.py", line 175, in main
21:58:58:     await client.run()
21:58:58:   File "D:\User\Downloads\Compressed\TwitchDropsMiner\twitch.py", line 768, in run
21:58:58:     await self._run()
21:58:58:   File "D:\User\Downloads\Compressed\TwitchDropsMiner\twitch.py", line 810, in _run
21:58:58:     await self.fetch_inventory()
21:58:58:   File "D:\User\Downloads\Compressed\TwitchDropsMiner\twitch.py", line 1648, in fetch_inventory
21:58:58:     _("gui", "status", "adding_campaigns").format(counter=f"({i}/{len(campaigns)})")
21:58:58: KeyError: 'Counter'
```

**Comment by DevilXD** [comment]
Hello there o/

There's no Arabic translation available in the app. If you're trying to add your own translation, it seems that you've replaced one of the format fields by accident, specifically: `{counter}` was replaced by `{Counter}` (first letter was capitalized), leading to this error.

The relevant translation key, per what the error says, is `"gui" -> "status" -> "adding_campaigns"`, so that's where you should be able to find the messed up translation string, and fix it.

Please let me know if you'd be having any further troubles.

**Comment by Bamboozul** [comment]
> Hello there o/
> 
> There's no Arabic translation available in the app. If you're trying to add your own translation, it seems that you've replaced one of the format fields by accident, specifically: `{counter}` was replaced by `{Counter}` (first letter was capitalized), leading to this error.
> 
> The relevant translation key, per what the error says, is `"gui" -> "status" -> "adding_campaigns"`, so that's where you should be able to find the messed up translation string, and fix it.
> 
> Please let me know if you'd be having any further troubles.

Thank you for pointing me to where the issue is. Also, would it be possible to add support for RTL languages?

![1](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/b63a1426-0a71-4d75-9700-f75a2b2e5021)

![2](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/97f9759c-31d3-4acd-baa4-ea5ad7a23211)

![3](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/23e7f72f-a42b-4f82-b9c6-3744541c805c)

![4](https://github.com/DevilXD/TwitchDropsMiner/assets/101983929/cd3d669e-c180-400c-b3e0-8154d1083537)

And, as you can see in the last image, the text in "How It Works" and "Getting Started" is not showing properly, and the size of those sections is limited.

**Comment by Bamboozul** [comment]
Also, wouldn't it be easy to avoid these mistakes in the future by hosting this project on a translation service like [Crowdin](https://crowdin.com/) or [Hosted Weblate](https://hosted.weblate.org/)?

**Comment by DevilXD** [comment]
I'm not interested in either of those options, translations are already an extra feature that was "glued in" to the application, so you have to use the existing system. LTR languages were never expected nor tested, nor the application was ever prepared to support them in any remote way, so they won't be supported.

Regarding text being cut off, you can insert new lines with `\n`, the limit should only be horizontal, but not vertical.

**Comment by Bamboozul** [comment]
> I'm not interested in either of those options, translations are already an extra feature that was "glued in" to the application, so you have to use the existing system. LTR languages were never expected nor tested, nor the application was ever prepared to support them in any remote way, so they won't be supported.
> 
> Regarding text being cut off, you can insert new lines with `\n`, the limit should only be horizontal, but not vertical.

Got it.
