### ISSUE TITLE
Inventory is blank and status is always idle

### ISSUE THREAD

**Issue by Parapando** [DevilXD/TwitchDropsMiner#273]
v15 and v16 can't see any games, everything i did was a miss, disabling/enabling priority only didn't changed anything, linked only too, manually entered games (Tom Clancy's Rainbow Six Siege) also had no effect, it seems like this app doesn't work at all for me for some reason.
![Screenshot_34](https://github.com/DevilXD/TwitchDropsMiner/assets/69468857/3835d8e8-4fff-4294-8e4a-1f8e1f933518)
![Screenshot_37](https://github.com/DevilXD/TwitchDropsMiner/assets/69468857/c5236f10-e444-42d5-9a64-26f2acb5dee3)
![Screenshot_36](https://github.com/DevilXD/TwitchDropsMiner/assets/69468857/94a457ff-9b62-4c81-8a89-a83073eaae66)
![Screenshot_35](https://github.com/DevilXD/TwitchDropsMiner/assets/69468857/8e806872-760a-4d26-bb1b-ec907a23cd2a)

**Comment by DevilXD** [comment]
This is most likely related to #264, and thus a duplicate. Please refer to instructions there.

**Comment by Parapando** [comment]
It looks like there is no any way to fix it right now, anyway thank for the good app, good luck
