### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#276]
the latest version doesn't work at all, can't even claim the 50 points

![Sin título](https://github.com/DevilXD/TwitchDropsMiner/assets/110930030/a052b99b-f9c1-46a0-9714-672d33e65dc5)

![Sin título](https://github.com/DevilXD/TwitchDropsMiner/assets/110930030/68920948-00c4-47a4-bf00-f642904f298b)

**Comment by OffensiveExile** [comment]
Currently it works on my machine with the latest repo updates and building it myself.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/13441775/32aaa6bc-a38e-4c01-8cc5-7c776b5914f1)

**Comment by matarife123** [comment]
It works for me at times, then it stays like this:
![Sin título](https://github.com/DevilXD/TwitchDropsMiner/assets/110930030/2246bde7-bd9d-4365-a824-e5b8bdfd6561)

**Comment by DevilXD** [comment]
The last pic refers to an existing issue: #110, so that's already acknowledged. Other than that, you're left with reading what you can find in #264, as that's where the recent Client ID change comes from. Let's keep the discussion there.
