### ISSUE TITLE
Gathering channels stuck

### ISSUE THREAD

**Issue by existful** [DevilXD/TwitchDropsMiner#277]
Build: d5410b2 (self build)

TDM stucks on: Status Gathering channels.

![TDM_STATUS_GC](https://github.com/DevilXD/TwitchDropsMiner/assets/63012845/d1afb90f-24d2-4aa2-a28c-ede65f04479a)
![TDM_INVENTORY](https://github.com/DevilXD/TwitchDropsMiner/assets/63012845/c80221d7-7097-44b3-8da1-ff018feec802)
![TDM_SETTINGS](https://github.com/DevilXD/TwitchDropsMiner/assets/63012845/ad3ca40b-0aad-491d-ac74-d9a1b9be3ae6)

running with run_dev.bat console (y) and no errors.

Update:
![TDM_OUTPUT](https://github.com/DevilXD/TwitchDropsMiner/assets/63012845/07b080cb-8035-4a3b-a78e-87c65fdf5e26)

- No Firewall/Network issue.

Kind regards.

**Comment by DevilXD** [comment]
This is due to a change introduced in #264, thus making this a duplicate. Please refer to discussion there.
