### ISSUE TITLE
App fully stopped working

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#281]
App stopped working some minutes ago, now only gives this error everytime.

18:23:14: Fatal error encountered:
18:23:14: 
18:23:14: Traceback (most recent call last):
18:23:14:   File "main.py", line 175, in main
18:23:14:   File "twitch.py", line 765, in run
18:23:14:   File "twitch.py", line 906, in _run
18:23:14:   File "channel.py", line 269, in update_stream
18:23:14:   File "channel.py", line 258, in get_stream
18:23:14:   File "channel.py", line 47, in from_get_stream
18:23:14:   File "channel.py", line 39, in __init__
18:23:14: TypeError: 'NoneType' object is not iterable
18:23:14: 
18:23:14: Exiting...
18:23:14: 
18:23:14: Application Terminated.
18:23:14: Close the window to exit the application.

**Comment by gmorks** [comment]
getting the same error, built it from dev

**Comment by Js41637** [comment]
The app is crashing because its trying to see if a channel has the drops enabled tag however the GQL API Operation that the app uses no longer returns the tags and they're now null.

Not sure if there's another Operation that returns all the info in a single request. You'll probably need to make a seperate request to the `RealtimeStreamTagList` or `StreamTagsTrackingChannel` operation which both return tags for a channel.

**Comment by Qiaofanxing** [comment]
Yeah, I had the same problem.

**Comment by ProCasual** [comment]
Yep, seems twitch changed something and it's busted again... dev is amazing at fixing this app every time that happens. Really appreciate their work. Would be so great if we could auto-update the app too as sometimes I don't notice it's not working. That feature would get a donation from me.

**Comment by 2eyan9** [comment]
I had the same problem.
![36f7bb54a62f896e2af613fb0daae84](https://github.com/DevilXD/TwitchDropsMiner/assets/36217197/7674b96d-80c7-4032-8584-2eeba376f396)

**Comment by stijndp** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/264#issuecomment-1672740509
Not 2 weeks ago...

Maybe as a temporary solution the channel with the most viewers could be chosen? Without knowing, that will have the highest chance of having drops.
And after x time it can be checked if indeed progress is made.

**Comment by i20i** [comment]
I had the same problem too.

15:16:35: Fatal error encountered:
15:16:35: 
15:16:35: Traceback (most recent call last):
15:16:35:   File "main.py", line 175, in main
15:16:35:   File "twitch.py", line 765, in run
15:16:35:   File "twitch.py", line 906, in _run
15:16:35:   File "channel.py", line 269, in update_stream
15:16:35:   File "channel.py", line 258, in get_stream
15:16:35:   File "channel.py", line 47, in from_get_stream
15:16:35:   File "channel.py", line 39, in __init__
15:16:35: TypeError: 'NoneType' object is not iterable

**Comment by knuthen** [comment]
After not working yesterday, the miner resumed to work again as of now. Running [d5410b2](https://github.com/DevilXD/TwitchDropsMiner/commit/d5410b2aa5ee6148ca3e01e04addd29a1ff4db91) with the @guihkx fix

**Comment by gmorks** [comment]
> After not working yesterday, the miner resumed to work again as of now. Running [d5410b2](https://github.com/DevilXD/TwitchDropsMiner/commit/d5410b2aa5ee6148ca3e01e04addd29a1ff4db91) with the @guihkx fix

I build it today, and those errors are from today

**Comment by pw1602** [comment]
```diff
diff --git a/channel.py b/channel.py
index 313708d..581d219 100644
--- a/channel.py
+++ b/channel.py
@@ -50,7 +50,7 @@ class Stream:
             game=settings["game"],
             viewers=stream["viewersCount"],
             title=settings["title"],
-            tags=stream["tags"],
+            tags=stream["tags"] or [],
         )
```
I've made changes like above and it's working. Drops are progressing without problems and claimed without problems too. Tested on TES Online drop.

**Comment by knuthen** [comment]
I checked in with a friend who is running the same build as I and for him it seems to works as well.
I also tested the latest two commits both running both build and unbuild. Everything is working on my end.

**Comment by gmorks** [comment]
maybe something changed over twitch, just launch it not changing anything and it's working... weird

**Comment by 2eyan9** [comment]
> I had the same problem. ![36f7bb54a62f896e2af613fb0daae84](https://user-images.githubusercontent.com/36217197/262226663-7674b96d-80c7-4032-8584-2eeba376f396.png)

A few hours later, I reopened the .exe file and found that the issue had disappeared.

**Comment by Danzo51196** [comment]
> A few hours later, I reopened the .exe file and found that the issue had disappeared.During that time, I built the latest version and was prompted to use the newest cookies.

Can confirm this.

**Comment by pw1602** [comment]
> Did someone receive a Trojan:Win32/Bearfoos.A!ml alert after compile .exe?
> I've made this changes but don't work for me.

No alert at all. I've checked again and without those changes it's still not working for me, but with changes it works. I am up to date with master branch.

**Comment by OffensiveExile** [comment]
> Did someone receive a Trojan:Win32/Bearfoos.A!ml alert after compile .exe?
> 
> I've made this changes but don't work for me.
> 
> ```
> > -            tags=stream["tags"],
> > +            tags=stream["tags"] or [],
> ```
> 
> ![Screenshot_4](https://user-images.githubusercontent.com/56942557/262360126-ce2ac3ef-ac97-4dac-8116-5eb1bcd049e6.png) ![Screenshot_5](https://user-images.githubusercontent.com/56942557/262360133-b8e4c003-de33-49b6-b804-10a2c48c0fca.png)

The beauty about open source projects is that you can always check the code whenever you want and even recent commits: https://github.com/DevilXD/TwitchDropsMiner/commits/master

It's most likely a false positive due to how Python compiles the scripts.

**Comment by SufferMeNow** [comment]
> ```diff
> diff --git a/channel.py b/channel.py
> index 313708d..581d219 100644
> --- a/channel.py
> +++ b/channel.py
> @@ -50,7 +50,7 @@ class Stream:
>              game=settings["game"],
>              viewers=stream["viewersCount"],
>              title=settings["title"],
> -            tags=stream["tags"],
> +            tags=stream["tags"] or [],
>          )
> ```
> 
> I've made changes like above and it's working. Drops are progressing without problems and claimed without problems too. Tested on TES Online drop.

It works for me too. Thanks.

**Comment by Diseraph** [comment]
I'm very new to how open source stuff works. How do I take advantage of teh smart cookies in here who are affecting the source code?

**Comment by stijndp** [comment]
> I'm very new to how open source stuff works. How do I take advantage of teh smart cookies in here who are affecting the source code?

You can use the following [guide](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running) describing the process.  

Preferably DevilXD tests the change, checks it in and kicks off a build. Or gives checkin permissions to someone trusty to follow his goals, spirit and quality of the project while his time is being stolen by the pesky fact of life called a job.

**Comment by notNSANE** [comment]
I'll rettest with new cookies. Perhaps it might be a regional issue? Worth checking.

**Comment by DevilXD** [comment]
It's too late to debug this issue like that, I'd think. The tags array was a remainder from the times where Twitch could provide the "Drops Enabled" tag via that array, but since that's no longer the case, and no other tags were being checked, it's currently a useless piece of code that only slows down the program. One more thing to take care of during #220, and that's it.
