### ISSUE TITLE
windows defender

### ISSUE THREAD

**Issue by NaniDaFuck** [DevilXD/TwitchDropsMiner#284]
windows defender detects the new exe as trojan 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/70827970/b9a197bf-34c2-4573-a7dd-e0165042485c)

**Comment by DevilXD** [comment]
This is a duplicate of #270, #249, #217, #209 and #13. I should put out a note in the README for this.

**Comment by NaniDaFuck** [comment]
got u 
i know that would happen sometimes
