### ISSUE TITLE
Error On Linux Cant Run

### ISSUE THREAD

**Issue by MehmetCanWT** [DevilXD/TwitchDropsMiner#286]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/52177084/09086cfc-7aac-47fe-8d5c-61129e238371)
Giving me this error when i trying to run linux script

**Comment by guihkx** [comment]
Are you trying to run it on a headless Linux server? If you are, that might be why.

As the README states, the app requires a working display server to run on Linux.

**Comment by TheLovinator1** [comment]
Should probably work if this is WSL2. I don't have WSL2 (or Linux) but try `PYSTRAY_BACKEND=xorg ./Twitch`?

**Comment by DevilXD** [comment]
@MehmetCanWT As I said, this isn't a console application - you can't run it without a display. This is a personal application, meant to be ran on your personal computer, that has to have a display for it to function. No display setups are not supported.
