### ISSUE TITLE
No games found

### ISSUE THREAD

**Issue by Rebirth92** [DevilXD/TwitchDropsMiner#288]
Hello,
I was using your tool for a few weeks now.
It has just stopped working. 
I cannot find any more games in the search bar.
See attached image.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/143839847/5f50d423-060f-4732-8860-38dc4337bb40)

I am currently logged in. So that is working as should.
Any ideas?
Thank you in advance. And for you amazing tool!
Kind regards, Jens

**Comment by DevilXD** [comment]
v15 is not supported anymore. Please read the download description before downloading anything. Use the development build instead.
