### ISSUE TITLE
In how many channels can you recieve points at the same time?

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#289]
I have a very specific channel that I need to recieve points at all times. But sometimes it just stops recieving points and I panic. I read that there's a cap on how many channels can you get points, so having that channel, a channel I just watch (and I don't care about points) AND a channel I need the drops (and I don't care about the points either...), apparently it's starting to become a real issue.

I'm sure this info isn't shared anywhere on Twitch so I'm asking here, sorry for the off-topic.

**Comment by DevilXD** [comment]
Hello o/

I'm definitely not certain about this information, but I've heard that - when it comes to earning channel points - the limit is 2 channels at a time. However, I wasn't able to verify this personally. The limit on drop earning is still 1 at a time, so there's no point in introducing any advanced logic in the miner to handle watching two channels at a time, but you should be able to use the miner *and* watch that specific channel of yours, at the same time and earn points for both.

**Comment by notNSANE** [comment]
The issue is that at some point (due to reloads or disconnects) the first channel stops earning points.

So I have to ask, it's possible for this app to disable earning points? @DevilXD 

The alternative would be to use another account and browser to actually watch and interact with twitch... Which causes many other issues.

**Comment by DevilXD** [comment]
Earning points is tied to the same spade event that triggers drop progression: `"minute-watched"`. It would be possible to disable the automatic claiming of the extra 50 points every 15 minutes, but not earning of the points entirely, since that'd also prevent earning drops.
