### ISSUE TITLE
Antivirus False Positive

### ISSUE THREAD

**Issue by josephisticated** [DevilXD/TwitchDropsMiner#292]
Seems like windows defender gives a false positive.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/53388005/88ccd5be-d82b-497e-998e-918d20fea99a)

**Comment by guihkx** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/291#issuecomment-1704043363

**Comment by josephisticated** [comment]
> [#291 (comment)](https://github.com/DevilXD/TwitchDropsMiner/issues/291#issuecomment-1704043363)

Oh, didn't see that, sorry.

**Comment by DevilXD** [comment]
It turns out there already is a note about this in README, people just don't read...
![obraz](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/ee5d2693-3b2f-47f8-a612-8832b87c5f12)
