### ISSUE TITLE
Does not detect the Rust twitch drops

### ISSUE THREAD

**Issue by y1keee** [DevilXD/TwitchDropsMiner#299]
I can see Rust in the priority list but the miner does not start to watch Rust streams

**Comment by DevilXD** [comment]
Hello o/

There's two reasons this might be happening:

- You're using v15, which became not stable / obsolete around February this year. v16 is still in development, but a pre-release version of it is available, that can solve the issue of not watching certain streams.
- Your Twitch account isn't linked with the game, and campaigns with missing or invalid linking status, aren't considered as valid mining targets, even if they're added to the Priority list.

Please ensure these two points does not apply to your situation, and if so, correct them appropriately - use the v16 pre-release version, or ensure the campaign linking status says "Linked", either on the Twitch campaigns page, or by finding and checking the campaign status in the Inventory tab of the miner.

**Comment by y1keee** [comment]
Im using the latest release version and my account is linked i can even see Rust there in the priority list but its the only game where the miner does not work

**Comment by jbfreels** [comment]
This is happening to me as well. 

Oddly enough, if I go watch a rust streamer with my account and then close twitch and open the drop miner then it watches the one streamer I was watching but shows no other streamers.

**Comment by DevilXD** [comment]
This sounds a lot like #189. Please ensure you're using the latest version of the miner. Note that v15 is not stable anymore, so you'll have to use the latest master branch build, or the pre-release version available in downloads.

**Comment by y1keee** [comment]
Im using the version that you published 3 days ago i mean the miner works great for every game except rust

**Comment by jbfreels** [comment]
Just updated to make sure 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/5649291/0002b404-ea09-4d91-a9ab-63f62b0767a7)

Now the "watch a channel first to have it watch that channel" doesn't work, I was v16.dev.3fa9568 previously.

**Comment by DevilXD** [comment]
> "watch a channel first to have it watch that channel" doesn't work,

Because you don't need to do that, ever since https://github.com/DevilXD/TwitchDropsMiner/commit/70035cde36dc1c225e4ebedfbfc8cec7d0d30994 was pushed out over 3 weeks ago. Check everything else that can prevent the campaign from being mined: linking status and priority list.

**Comment by DevilXD** [comment]
I've detailed out how to verify the linking status here: #198.

**Comment by jbfreels** [comment]
Thanks, mine said it was connected, so I unlinked and then did it again and now it is working.
