### ISSUE TITLE
Is it possible to use on vds with ubuntu 20.04?

### ISSUE THREAD

**Issue by daeeros** [DevilXD/TwitchDropsMiner#300]
I mean like i dont have ui or something, only console, it can be work like it? I try run it like bash with ./TtvMiner but getting -bash: ./bot: cannot execute binary file: Exec format error

**Comment by guihkx** [comment]
>I mean like i dont have ui or something, only console

The README page [states this](https://github.com/DevilXD/TwitchDropsMiner#project-goals):

>This means that features such as:
>- It being possible to run it without a GUI, or with only a console attached.
>..., are most likely not going to be a feature, ever.

As for this error in particular:

>./bot: cannot execute binary file: Exec format error

Are you trying to run this on a Raspberry Pi or something like that? The binary provided here is built for x86-64 processors, not aarch64. Your only option for now would be [building and running from source](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running).

**Comment by daeeros** [comment]
> > Я имею в виду, будто у меня нет пользовательского интерфейса или чего-то в этом роде, только консоль.
> 
> На странице README [указано следующее](https://github.com/DevilXD/TwitchDropsMiner#project-goals) :
> 
> > Это означает, что такие функции, как:
> > 
> > * Его можно запустить без графического интерфейса или только с подключенной консолью. 
> >   ..., скорее всего, никогда не станут особенностью.
> 
> Что касается этой ошибки, в частности:
> 
> > ./bot: невозможно выполнить двоичный файл: ошибка формата Exec
> 
> Вы пытаетесь запустить это на Raspberry Pi или что-то в этом роде? Представленный здесь двоичный файл создан для процессоров x86-64, а не aarch64. Единственным вариантом на данный момент будет [сборка и запуск из исходного кода](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running) .

Thank you, yes i try tu run from oracle cloud with Ampere processors. It like arm, have a nice day <3
