### ISSUE TITLE
Notify when cookie expire

### ISSUE THREAD

**Issue by kevingrillet** [DevilXD/TwitchDropsMiner#304]
Hello,
I'm running TwitchDropsMiner on a raspberry pie and one day the cookie did expire, it did stop working for 2 weeks during my holidays since I was not going on Twitch I did not see the problem :(

I'm restarting TwitchDropsMiner every day, so it could be possible to detect a cookie issue.

Would it be possible to send a mail when cookie expire with link & code to login again? This may help prevent this happening without noticing ;)

**Comment by DevilXD** [comment]
Hello o/

I see no point in adding an email feature to the miner. You're not supposed to "just leave it for 2 weeks" unattended. Please familiarize yourself with the project goals as well, as it may tell you why this is a NoFix from me: https://github.com/DevilXD/TwitchDropsMiner#project-goals
