### ISSUE TITLE
Campaign incorrectly labeled as unlinked

### ISSUE THREAD

**Issue by mdk25** [DevilXD/TwitchDropsMiner#309]
There is currently a campaign for Overwatch 2 that appears disconnected on Twitch:

![connection](https://github.com/DevilXD/TwitchDropsMiner/assets/2078479/a8ac5403-4b1b-486f-aa9b-619a099348c7)

No amount of reconnecting or refreshing fixes this. However, the connection already exists, as evidenced not only by Battle.net but by a different campaign for the same game:

![connection2](https://github.com/DevilXD/TwitchDropsMiner/assets/2078479/d42a5a23-8cea-4538-9e16-e39feea73cc7)

While this seems like a bug in the Twitch campaign listing, it still allows the drop to be obtained manually. Unfortunately, the miner filters it out:

![inventory](https://github.com/DevilXD/TwitchDropsMiner/assets/2078479/f93bcd7b-6757-4cdd-9043-a5a012446054)

Ideally there would be a way to allow the miner to ignore the connection status, since it apparently can't be fully trusted.

**Comment by DevilXD** [comment]
> Ideally there would be a way to allow the miner to ignore the connection status

This is not in the plans anywhere in the future.

Regarding the issue itself, please perform a clean reconnect. To do this:

• Disconnect the accounts. For Twitch, use [the Connections page](https://www.twitch.tv/settings/connections), find the affected game and click on "Disconnect". For the affected game, go to it's designated account control panel, and try finding an account disconnect option there. Disconnecting at least one side is necessary, disconnecting both is recommended. If you're not able to disconnect both sides, you may run into re-linking errors later - just keep that in mind.
• Log out of the accounts - for Twitch, mouse over your profile avatar in the top-right side of the page, and click on "Log Out" on the bottom of the popup list. For the affected game, you'll need to find a logout option somewhere on it's account management page. Ensure you're logged out by refreshing the page and/or restarting the browser - you should only see a non-logged-in state on both sides.
• Initiate the linking - depending on the affected game, you now need to initiate the linking process again. Usually, it's done from the game account management page, so login into the game's page and click on "Connect to Twitch" there. You should be redirected to Twitch, and required to login there during the linking process. Alternatively, you can log into Twitch first, and then initiate the linking from there, logging into the game account during the process. Either of these two methods can be tried and used, and it only depends on the affected game.
• Finish the linking process - if no errors come into play, you should be good to go, with both accounts linked together.

Essentially, re-logging into each account first, before attempting to re-link, ensures fresh authorization tokens and no hidden errors will result in the process staying in an invalid state. Please give it a try and let me know how it went.

**Comment by mdk25** [comment]
A clean reconnect is not an option in this case, as Battle.net states that a reconnect is not available until 7 days after a disconnect, and at that point it would be too late. I could try it after this campaign, but it may not be necessary, as most previous campaigns have not exhibited this problem. For now, it seems the only other option is to hope it works manually in my browser at 4am.

This example aside, I've also had several cases in the last couple years where I've wanted to mine drops for games that I don't yet own or play, but expect to in the future. It's nice to have them all currently sitting in my inventory, awaiting the connection of an account that will eventually exist. You could argue that I should have created accounts for these games from the start, but that seems like an arbitrary prerequisite when it's not required by Twitch.

**Comment by spuukii** [comment]
> You could argue that I should have created accounts for these games from the start, but that seems like an arbitrary prerequisite when it's not required by Twitch.

Incorrect. This *is* a requirement for Twitch, and how drops have always worked. If you claim a drop with an unlinked account, the drop is no longer valid. There have been numerous posts and PSAs on the internet about this:

https://www.reddit.com/r/animalroyale/comments/qgghvg/psa_for_twitch_drops_link_your_account_before_you/
https://www.reddit.com/r/elderscrollsonline/comments/mjfp7t/how_to_get_twitch_drops_after_theyve_been_claimed/
https://www.bungie.net/en/Forums/Post/258175087

Some games have an external page that will allow you to refresh your connection after the fact to get re-linking done, while others don't.

**Comment by mdk25** [comment]
Ok. I can't speak to the implementation of individual games, especially if they used the old drop system. It's clear that Twitch intended to support linking accounts after claiming drops and built their UI with that in mind, but perhaps it's a regularly broken feature.

They do mention this:
> How long do I have to link my account to get my Drop Rewards?
> Most developers will fulfill the reward if you link your account within 14 days of the relevant Drops campaign ending. If the reward is only usable for a limited time (e.g. beta event), then other time restrictions may apply.

It probably would be smart of them to surface this time limit for unlinked drops instead of hiding it in the FAQ.

**Comment by mdk25** [comment]
> This cooldown is only for new/other twitch accounts, not if you unlink-relink the same account [[source](https://us.forums.blizzard.com/en/overwatch/t/overwatch-contenders-league-2023-schedule-earn-skins/805389/1177)].

I see, good to know, assuming this forum post is correct.

> But in the case of the Mercy drop, it won't help. The drop is broken for some/all? [[source](https://us.forums.blizzard.com/en/overwatch/t/overwatch-contenders-league-2023-schedule-earn-skins/805389/1160)]

Yeah, this is not surprising. It seems likely that the required connection was just misconfigured when the campaign was created.

IMO it remains the case that it would be useful to be able to mine this drop ahead of them fixing the problem with the connection, which may or may not happen by the end of the campaign.

**Comment by DevilXD** [comment]
> IMO it remains the case that it would be useful to be able to mine this drop ahead of them fixing the problem with the connection

This will never ever be added. Please see the project goals: https://github.com/DevilXD/TwitchDropsMiner#project-goals

Regarding doing the clean reconnect, you should be able to just re-link without waiting. If you really fear it's going to put you in the 7 days long cooldown state, you can still try following the clean reconnect steps list, but without doing the disconnect step. Re-logging during the linking process is the most important part, as the most common cause for broken inter-account connections, is having a stale session token.

**Comment by mdk25** [comment]
As mentioned above, there is no point in reconnecting, as the problem is with the campaign. The connection between my account and Battle.net remains perfectly fine. Twitch confirmed this to me in an email yesterday.

Anyway, it's your project, so your choice. Since the functionality is supported by Twitch and quite useful, I implemented it myself. I appreciate that your code is clean and easy to work with.
