### ISSUE TITLE
Drop progress not counting

### ISSUE THREAD

**Issue by nwho99** [DevilXD/TwitchDropsMiner#310]
Hi,

I am not earning drop progress despite the app saying I have:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/77857949/e1e0a4e1-ef66-4dbe-9d21-b563612101f8)

My actual drop progress on Twitch:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/77857949/de29f50a-eb64-41e1-b7a6-536f85d2a096)

Restarting the app reflects my actual drop progress until it starts watching/mining again in which case it'll go up on the app but nothing actually counts towards my progress.

Build: [6b9aabb](https://github.com/DevilXD/TwitchDropsMiner/commit/6b9aabb2522f0d11c7c0dec56cfd6a0d159fc195)
Environment: Ubuntu 20.04 Xfce

**Comment by DevilXD** [comment]
Hello. Was this meant to be closed? Did you figure it out, or still need help?

**Comment by nwho99** [comment]
It was a dupe of [#301](https://github.com/DevilXD/TwitchDropsMiner/issues/301)

**Comment by DevilXD** [comment]
I see. Well then.
