### ISSUE TITLE
Detection by MalwareByte

### ISSUE THREAD

**Issue by DaCrazyRaccoon** [DevilXD/TwitchDropsMiner#313]
I've recently started to have problem opening Twitch Drops Miner as it is stopped everytime by my MalwareByte.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/79057902/8ce050aa-d5f9-4d21-853a-56635edf50ea)
 I know the application works when disabling MalwareByte but would prefer if I didn't have to. In the included pic, it shows the location of the "problem" and the reason for its quarantine (RTP Detection).
 
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/79057902/01205a57-e62c-493e-881f-e248ca8e5d44)
Here's a picture of what happens if I open Twitch Drops Miner anyway.

**Comment by spuukii** [comment]
This is due to Pyinstaller. It's in the README.

> To achieve a portable-executable format, the application is packaged with PyInstaller into an EXE. Some non-mainstream antivirus engines might report the packaged executable as a trojan, because PyInstaller has been used by others to package malicious Python code in the past. These reports can be safely ignored. If you absolutely do not trust the executable, you'll have to install Python yourself and run everything from source.

Per the README, if you want to avoid the issue then install Python and run everything from source.
