### ISSUE TITLE
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by falcon56321** [DevilXD/TwitchDropsMiner#318]
_websocket.c
      aiohttp/_websocket.c(1475): warning C4996: 'Py_OptimizeFlag': deprecated in 3.12
      aiohttp/_websocket.c(3042): error C2039: 'ob_digit': bir '_longobject' \x81yesi degil
      C:\Python312\include\cpython/longintrepr.h(87): note: '_longobject' bildirimine bakin
      aiohttp/_websocket.c(3097): error C2039: 'ob_digit': bir '_longobject' \x81yesi degil
      C:\Python312\include\cpython/longintrepr.h(87): note: '_longobject' bildirimine bakin
      aiohttp/_websocket.c(3238): error C2039: 'ob_digit': bir '_longobject' \x81yesi degil
      C:\Python312\include\cpython/longintrepr.h(87): note: '_longobject' bildirimine bakin
      aiohttp/_websocket.c(3293): error C2039: 'ob_digit': bir '_longobject' \x81yesi degil
      C:\Python312\include\cpython/longintrepr.h(87): note: '_longobject' bildirimine bakin
      aiohttp/_websocket.c(3744): error C2039: 'ob_digit': bir '_longobject' \x81yesi degil
      C:\Python312\include\cpython/longintrepr.h(87): note: '_longobject' bildirimine bakin
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

All done!

**Comment by DevilXD** [comment]
Hello. I'm not sure what am I looking at here. `aiohttp` doesn't need to be built from wheels. What's your operating system / platform you're trying to install this on?

**Comment by falcon56321** [comment]
> Hello. I'm not sure what am I looking at here. `aiohttp` doesn't need to be built from wheels. What's your operating system / platform you're trying to install this on?

I'm trying to install it on Windows operating system and Ghost Specter is Windows 10 22h2 version on my own computer. I was using Windows Atlas before the format, it was fine, but now it gives this error.

**Comment by DevilXD** [comment]
This bug might be beyond my influence, as it refers to a dependency I don't maintain. If a simple `pip install aiohttp<4.0` results in that error, please file an issue under the https://github.com/aio-libs/aiohttp/ project instead.

**Comment by JustArtiom** [comment]
Visual Studio C++ Build tools are missing, you need to download them!

**Comment by DevilXD** [comment]
According to https://github.com/aio-libs/aiohttp/issues/7229, Python 3.12 *is* supported, but not in the latest PyPi version of the library. The support only exists in the latest development build. This gives you two options:

- Install that build instead - see the comments under the linked issue.  
- Use Python 3.11.

Besides this, as I said, this is an "outside issue" that I cannot help more with, other than what the above says.
