### ISSUE TITLE
Re-shadows when you flip up and down the treasure trove.

### ISSUE THREAD

**Issue by fgr178707** [DevilXD/TwitchDropsMiner#319]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/109357981/1741d654-99c2-451d-9a82-eeace5850724)
Re-shadows when you flip up and down the treasure trove.

**Comment by DevilXD** [comment]
Hello.

There's nothing I can do to prevent this visual issue, as it's an internal Tkinter limitation to display it in such a way. Solving this would mean rewriting the entire GUI in a different library, something that isn't planned for now.
