### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by nwvh** [DevilXD/TwitchDropsMiner#32]
Hello, would it be possible to create something like lang.json file where you could edit every text used in GUI so it could be used to translate the script for another language(s)? Thanks

**Comment by DevilXD** [comment]
Hello o/

An interesting concept. Unfortunately, it's not easily doable in an automatic way. Translation would have to be an opt-in feature, that'd have to be manually targeted at every field that'd need to be translated - it'd just require work to design, code in and setup the translation backend.

What is the demand on this feature? Is this something you're interested in only, or is there more people who'd like the app to be translated? If anything, I'd appreciate some other people commenting on this issue if they'd be interested in this becoming a thing.

**Comment by DevilXD** [comment]
After some personal discussion with another user, I've decided to go ahead and implement this as a feature. Chinese translation will be available together with the `v12` release.

**Comment by DevilXD** [comment]
This is now available as a feature in `v12`: https://github.com/DevilXD/TwitchDropsMiner/releases
