### ISSUE TITLE
Dependent drops

### ISSUE THREAD

**Issue by apollo2k4** [DevilXD/TwitchDropsMiner#323]
The program does not respond correctly to companies in which the time of the previous event is associated with the time of the next one. The program counts time to 100%, and then starts in a circle. Current companies on which you can check now – Honkai: Star Rail or Dead by Daylight
![img](https://i.imgur.com/rGP1joL.png "Example")

**Comment by DevilXD** [comment]
Hello. Which version of the application are you using? Also, what does "starts in a circle" mean?

**Comment by apollo2k4** [comment]
I use dev build 2dd7a57344c9169428d3c8865e753af5f2d5e7d0
Time reaches 00:00 and starts again without receiving a reward and so on in a circle.
I didn't keep track when Twitch counted this time (on image), this company was spinning with me all day. Before that, there was the same problem with the Honkai and to get it correctly, I had to disable the program and run it in the browser.

**Comment by DevilXD** [comment]
Please try launching the application with the `-vvv` option, let it progress the drop a little, then post the resulting output that's printed out inside the application. Additionally, please attach a picture from the application window main tab, specifically, what's the drop progress and the available channels list / current watching channel.

**Comment by EffortlessFury** [comment]
Having the same issue with Star Rail.

```15:04:42: INFO: Websocket[0] connecting...
15:04:42: INFO: Websocket[0] connected.
15:04:53: CALL: Maintenance task waiting until: 15:34:53 (Points)
15:04:58: Watching: Putupau
15:04:58: INFO: Websocket[1] connecting...
15:04:58: INFO: Websocket[2] connecting...
15:04:58: INFO: Websocket[3] connecting...
15:04:58: INFO: Websocket[4] connecting...
15:04:58: INFO: Websocket[5] connecting...
15:04:58: INFO: Websocket[6] connecting...
15:04:58: INFO: Websocket[7] connecting...
15:04:58: INFO: Websocket[2] connected.
15:04:58: INFO: Websocket[3] connected.
15:04:58: INFO: Websocket[5] connected.
15:04:58: INFO: Websocket[7] connected.
15:04:58: INFO: Websocket[1] connected.
15:04:58: INFO: Websocket[4] connected.
15:04:58: INFO: Websocket[6] connected.
15:05:08: CALL: No drop update from the websocket received
15:05:08: CALL: Drop progress from active search: Credit*20000 (Honkai: Star Rail, 9/15)
15:05:32: INFO: Elly goes OFFLINE
15:05:34: CALL: Channel update from websocket: Elly
15:06:07: CALL: No drop update from the websocket received
15:06:07: CALL: Drop progress from active search: Credit*20000 (Honkai: Star Rail, 10/15)
15:06:15: INFO: zackrawrr goes OFFLINE
15:06:16: CALL: Channel update from websocket: zackrawrr
15:06:43: INFO: LenaGames goes OFFLINE
15:06:44: CALL: Channel update from websocket: LenaGames
15:07:06: CALL: No drop update from the websocket received
15:07:06: CALL: Drop progress from active search: Credit*20000 (Honkai: Star Rail, 11/15)
15:07:34: CALL: Elly stays OFFLINE
```

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/1612977/54933f93-2264-4aae-b471-3dc208709718)

**Comment by yeagerca** [comment]
Symptoms are the same as #301 and #310 using windows zip from recent dev build [67cfc66](https://github.com/DevilXD/TwitchDropsMiner/commit/67cfc6603d43de732cad3b9898b7a72b658bc31e) (12 hours ago) as well as whatever I was using pre-update. Miner counts progress up to 100% then waits because it didn't actually make progress. In the attached screenshots I watched manually to earn the drops at which point they were not auto-collected.

![honkai not collecting](https://github.com/DevilXD/TwitchDropsMiner/assets/93017663/d0f3c15d-e4b8-4192-9ad4-a2c750ed9bb9)

![honkai not collecting 2](https://github.com/DevilXD/TwitchDropsMiner/assets/93017663/8698341a-37f0-4f31-9bd3-85115e64931c)

**Comment by apollo2k4** [comment]
08:36:22: Logging level: CALL
08:36:23: INFO: Checking login
08:36:23: INFO: Restoring session from cookie
08:36:24: INFO: Login successful, user ID: xxxxxxxxxxxx
08:36:24: INFO: Websocket[0] connecting...
08:36:25: INFO: Websocket[0] connected.
08:36:39: CALL: Maintenance task waiting until: 09:06:39 (Points)
08:36:39: Watching: Skermz
08:36:39: INFO: Websocket[1] connecting...
08:36:40: INFO: Websocket[1] connected.
08:36:47: INFO: Tokki goes OFFLINE
08:36:48: CALL: Channel update from websocket: Tokki
08:36:51: CALL: No drop update from the websocket received
08:36:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 4/60)
08:37:47: CALL: Channel update from websocket: KyleTG, game changed: Dead by Daylight -> Crab Game
08:37:52: CALL: No drop update from the websocket received
08:37:52: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 5/60)
08:38:49: CALL: Tokki stays OFFLINE
08:38:51: CALL: No drop update from the websocket received
08:38:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 6/60)
08:39:45: Earned points for watching:  10, total: 30
08:39:45: Claimed bonus points: 50
08:39:46: Earned points for watching:  50, total: 80
08:39:47: INFO: KyleTG status has been updated (🎁: ❌ -> ❌)
08:39:51: CALL: No drop update from the websocket received
08:39:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 7/60)
08:40:51: CALL: No drop update from the websocket received
08:40:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 8/60)
08:41:51: CALL: No drop update from the websocket received
08:41:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 9/60)
08:42:51: CALL: No drop update from the websocket received
08:42:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 10/60)
08:43:51: CALL: No drop update from the websocket received
08:43:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 11/60)
08:44:44: Earned points for watching:  10, total: 90
08:44:51: CALL: No drop update from the websocket received
08:44:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 12/60)
08:45:50: CALL: No drop update from the websocket received
08:45:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 13/60)
08:46:50: CALL: No drop update from the websocket received
08:46:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 14/60)
08:47:50: CALL: No drop update from the websocket received
08:47:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 15/60)
08:48:50: CALL: No drop update from the websocket received
08:48:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 16/60)
08:49:44: Earned points for watching:  10, total: 100
08:49:50: CALL: No drop update from the websocket received
08:49:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 17/60)
08:50:20: CALL: Channel update from websocket: KyleTG
08:50:50: CALL: No drop update from the websocket received
08:50:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 18/60)
08:51:50: CALL: No drop update from the websocket received
08:51:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 19/60)
08:52:21: INFO: KyleTG status has been updated (🎁: ❌ -> ❌)
08:52:50: CALL: No drop update from the websocket received
08:52:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 20/60)
08:53:50: CALL: No drop update from the websocket received
08:53:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 21/60)
08:54:45: Earned points for watching:  10, total: 110
08:54:45: Claimed bonus points: 50
08:54:46: Earned points for watching:  50, total: 160
08:54:50: CALL: No drop update from the websocket received
08:54:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 22/60)
08:55:50: CALL: No drop update from the websocket received
08:55:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 23/60)
08:56:50: CALL: No drop update from the websocket received
08:56:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 24/60)
08:57:50: CALL: No drop update from the websocket received
08:57:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 25/60)
08:58:50: CALL: No drop update from the websocket received
08:58:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 26/60)
08:59:44: Earned points for watching:  10, total: 170
08:59:50: CALL: No drop update from the websocket received
08:59:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 27/60)
09:00:50: CALL: No drop update from the websocket received
09:00:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 28/60)
09:01:50: CALL: No drop update from the websocket received
09:01:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 29/60)
09:02:02: CALL: Channel update from websocket: Gremlin
09:02:50: CALL: No drop update from the websocket received
09:02:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 30/60)
09:03:50: CALL: No drop update from the websocket received
09:03:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 31/60)
09:04:03: INFO: Gremlin status has been updated (🎁: ❌ -> ❌)
09:04:44: Earned points for watching:  10, total: 180
09:04:50: CALL: No drop update from the websocket received
09:04:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 32/60)
09:05:50: CALL: No drop update from the websocket received
09:05:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 33/60)
09:05:59: INFO: MayoguiPlay goes OFFLINE
09:06:00: CALL: Channel update from websocket: MayoguiPlay
09:06:39: CALL: Maintenance task waiting until: 09:36:39 (Reload)
09:06:50: CALL: No drop update from the websocket received
09:06:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 34/60)
09:07:50: CALL: No drop update from the websocket received
09:07:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 35/60)
09:08:01: CALL: MayoguiPlay stays OFFLINE
09:08:50: CALL: No drop update from the websocket received
09:08:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 36/60)
09:09:45: Earned points for watching:  10, total: 190
09:09:45: Claimed bonus points: 50
09:09:45: Earned points for watching:  50, total: 240
09:09:50: CALL: No drop update from the websocket received
09:09:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 37/60)
09:10:50: CALL: No drop update from the websocket received
09:10:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 38/60)
09:11:02: INFO: chubbabubs goes OFFLINE
09:11:03: CALL: Channel update from websocket: chubbabubs
09:11:10: INFO: Antra goes OFFLINE
09:11:11: CALL: Channel update from websocket: Antra
09:11:50: CALL: No drop update from the websocket received
09:11:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 39/60)
09:12:24: CALL: Channel update from websocket: 얄네, game changed: Dead by Daylight -> Just Chatting
09:12:51: CALL: No drop update from the websocket received
09:12:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 40/60)
09:13:04: CALL: chubbabubs stays OFFLINE
09:13:11: CALL: Antra stays OFFLINE
09:13:50: CALL: No drop update from the websocket received
09:13:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 41/60)
09:14:24: INFO: 얄네 status has been updated (🎁: ❌ -> ❌)
09:14:45: Earned points for watching:  10, total: 250
09:14:50: CALL: No drop update from the websocket received
09:14:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 42/60)
09:15:50: CALL: No drop update from the websocket received
09:15:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 43/60)
09:16:51: CALL: No drop update from the websocket received
09:16:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 44/60)
09:17:51: CALL: No drop update from the websocket received
09:17:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 45/60)
09:18:30: CALL: Channel update from websocket: 얄네
09:18:51: CALL: No drop update from the websocket received
09:18:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 46/60)
09:19:44: Earned points for watching:  10, total: 260
09:19:50: CALL: No drop update from the websocket received
09:19:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 47/60)
09:20:31: INFO: 얄네 status has been updated (🎁: ❌ -> ❌)
09:20:50: CALL: No drop update from the websocket received
09:20:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 48/60)
09:21:50: CALL: No drop update from the websocket received
09:21:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 49/60)
09:22:50: CALL: No drop update from the websocket received
09:22:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 50/60)
09:23:50: CALL: No drop update from the websocket received
09:23:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 51/60)
09:24:44: Earned points for watching:  10, total: 270
09:24:45: Claimed bonus points: 50
09:24:45: Earned points for watching:  50, total: 320
09:24:51: CALL: No drop update from the websocket received
09:24:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 52/60)
09:25:51: CALL: No drop update from the websocket received
09:25:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 53/60)
09:26:51: CALL: No drop update from the websocket received
09:26:51: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 54/60)
09:27:50: CALL: No drop update from the websocket received
09:27:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 55/60)
09:28:50: CALL: No drop update from the websocket received
09:28:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 56/60)
09:29:44: Earned points for watching:  10, total: 330
09:29:50: CALL: No drop update from the websocket received
09:29:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 57/60)
09:30:50: CALL: No drop update from the websocket received
09:30:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 58/60)
09:31:50: CALL: No drop update from the websocket received
09:31:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 59/60)
09:32:50: CALL: No drop update from the websocket received
09:32:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 60/60)
09:33:50: CALL: No drop update from the websocket received
09:33:50: CALL: Drop progress from active search: Charm - Hatch Micro Playset (Dead by Daylight, 60/60)

![img](https://i.imgur.com/bvshrJR.png "Progress")

**Comment by DevilXD** [comment]
The key point from the log is this part:

> Drop progress from active search

"Active (drop) search" is a mechanic, where the miner sends a "minute watched" event to the Twitch's Spade edge server, but receives no drop progress update back, within the next 10 seconds. This usually happens when:

- The channel is switched to a different one - the next 5 minutes of watching doesn't have the progress reported, but it still counts.  
- Twitch, for some unknown reason, decides to stop reporting drop progress, or reports the exact same drop progress, for the next couple hours or so. (see #15)  
- Twitch keeps reporting progress for a drop we aren't actually mining (different game, already mined, etc.)  
- The channel being watched (unfortunately) doesn't have the drops enabled in their settings dashboard.

If there's no progress update shortly after the event is sent like that, the miner takes a look at it's current inventory, and then makes a "good guess" at which drop it can be mining right now. It then increases the progress on that drop by 1 minute, just like a real websocket update would, and continues on. There's no limit on how far this can increase the progress of a drop, with or without it being reflected on the twitch website. Essentially, it can "lie" to you about making progress, with the intention that the progress is still tracked properly in the above 3/4 cases, just isn't reported to the miner. The 4th case was so-far handled by the "drops enabled" tag, which isn't a thing anymore, so this pretty much boils down to the #301 issue.

I may actually have a "may help" solution for #301, but I'm currently still testing it. If I can get it to work today, I'll push out a change and let you know under #301 about it. This one is getting closed as a duplicate.
