### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by Drahonn** [DevilXD/TwitchDropsMiner#324]
When I ran the program and it retrieved all the drops from the inventory.
After that I get this in the console:

19:16:38: Fatal error encountered:
19:16:38: 
19:16:38: Traceback (most recent call last):
19:16:38:   File "main.py", line 158, in main
19:16:38:   File "twitch.py", line 764, in run
19:16:38:   File "twitch.py", line 905, in _run
19:16:38:   File "channel.py", line 277, in update_stream
19:16:38:   File "channel.py", line 262, in get_stream
19:16:38: TypeError: 'NoneType' object is not iterable
19:16:38: 
19:16:38: Exiting...
19:16:39: 
19:16:39: Application Terminated.
19:16:39: Close the window to exit the application.

I built the latest version from the repository.

**Comment by zelda0079** [comment]
Me too, I also tried to get a new cookie, same result.

**Comment by DevilXD** [comment]
Thanks for letting me know. This is an artifact of the last commit. https://github.com/DevilXD/TwitchDropsMiner/commit/f990aeea38aa89e0ca168b6267f70d8fa9aadd2c should fix this issue.

**Comment by DevilXD** [comment]
@FiLoUx70 This looks like you've failed to sync the repository properly, and part of your files are new, part of your files are old. Can't help you much with that, other than tell you to ensure proper sync, or re-download the entire repo from scratch if you're unsure what else to do,

**Comment by FiLoUx70** [comment]
@DevilXD Indeed, I did a reinstallation, it works perfectly, sorry for the “useless” message! :)
