### ISSUE TITLE
Value error: Time data

### ISSUE THREAD

**Issue by azraeldestiny01** [DevilXD/TwitchDropsMiner#325]
10:42:36: Fatal error encountered:
10:42:36: 
10:42:36: Traceback (most recent call last):
10:42:36:   File "main.py", line 175, in main
10:42:36:   File "twitch.py", line 768, in run
10:42:36:   File "twitch.py", line 810, in _run
10:42:36:   File "twitch.py", line 1601, in fetch_inventory
10:42:36:   File "twitch.py", line 1602, in <dictcomp>
10:42:36:   File "utils.py", line 88, in timestamp
10:42:36:   File "_strptime.py", line 568, in _strptime_datetime
10:42:36:   File "_strptime.py", line 349, in _strptime
10:42:36: ValueError: time data '2023-10-18T07:53:19.554Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
10:42:36: 
10:42:36: Saliendo...
10:42:37: 
10:42:37: La aplicación se ha detenido.
10:42:37: Por favor, cierre la aplicación.

**Comment by DevilXD** [comment]
This is already resolved in the latest master via #314.
