### ISSUE TITLE
No progress

### ISSUE THREAD

**Issue by zelda0079** [DevilXD/TwitchDropsMiner#326]
I am trying to idle the EVE online drop
No progress shows in my twitch
and then I try to refresh the inventory page after 2 minutes,
it is still 31% (the 31% is idled by broswer)
https://i.imgur.com/MjbMnP9.png

However, the twitch does not show the progress even I idle the twitch drop by broswer...
But the twitch drop progress is increased.

**Comment by zelda0079** [comment]
latest version

**Comment by DevilXD** [comment]
This is a duplicate of #301.
