### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Totesfleisch** [DevilXD/TwitchDropsMiner#328]
16:42:46: Fatal error encountered:
16:42:46: 
16:42:46: Traceback (most recent call last):
16:42:46:   File "main.py", line 158, in main
16:42:46:   File "twitch.py", line 764, in run
16:42:46:   File "twitch.py", line 913, in _run
16:42:46:   File "twitch.py", line 1703, in get_live_streams
16:42:46: TypeError: 'NoneType' object is not subscriptable
16:42:46: 
16:42:46: Exiting...
16:42:47: 
16:42:47: Application Terminated.
16:42:47: Close the window to exit the application.

Just downloaded the newest Version, before that i used one from a couple Weeks ago, and all was fine, now it doesnt work anymore and i get this Error. Usually i copy over my Settings and Cookies, but even without either i get the same Error.

**Comment by DevilXD** [comment]
I see. Which games have you added to the Priority list?

**Comment by matarife123** [comment]
![Sin título](https://github.com/DevilXD/TwitchDropsMiner/assets/110930030/3286649c-ac2b-4df5-bd8b-51fe90303552)

**Comment by matarife123** [comment]
> I see. Which games have you added to the Priority list?

Funny, when I added "Guessr.tv" it gave me this error.

**Comment by DevilXD** [comment]
There's a game with a name like that?

**Comment by Totesfleisch** [comment]
> I see. Which games have you added to the Priority list?

    "language": "English",
    "priority": [
        "The Elder Scrolls Online",
        "HUMANKIND",
        "Warframe",
        "Halo Infinite",
        "For Honor",
        "Overwatch 2",
        "PUBG: BATTLEGROUNDS",
        "PAYDAY 2",
        "FIFA 23",
        "Apex Legends",
        "The Crew: Motorfest",
        "Rocket League",
        "Vampire: The Masquerade - Bloodhunt",
        "Elite: Dangerous",
        "BattleBit Remastered",
        "New World",
        "Sea of Thieves",
        "Rust",
        "Diablo IV",
        "World of Warcraft",
        "Conan Exiles",
        "Cyberpunk 2077",
        "Arena Breakout",
        "Crossfire",
        "Stream Raiders",
        "STALCRAFT",
        "Starsiege: Deadzone",
        "World of Warships",
        "The First Descendant",
        "SYNCED",
        "Riders Republic",
        "Assassin's Creed Mirage",
        "Veiled Experts",
        "Ghostbusters: Spirits Unleashed",
        "Warhaven",
        "Party Animals",
        "AK-xolotl",
        "Operation Valor",
        "Warhammer Age of Sigmar: Realms of Ruin",
        "Gord",
        "UNITED 1944",
        "Disney Speedstorm",
        "My Hero Ultra Rumble",
        "DC Dual Force",
        "Infestation: The New Z",
        "Project: Arena",
        "Cult of the Lamb",
        "Project Winter",
        "Freestyle Football R",
        "From Space",
        "EVE Online",
        "BAPBAP",
        "Marbles on Stream",
        "Black Desert",
        "Hellcard",
        "Warhammer Online: Age of Reckoning",
        "Crossout",
        "Epic Seven",
        "KartRider: Drift",
        "Eternal Return",
        "Conqueror's Blade",
        "NARAKA: BLADEPOINT",
        "Lost Ark",
        "ArcheAge",
        "SMITE"



However i got the same Error by having an empty Prio List and having "Priority only" disabled.

Adding to that though, i just added the Game mentioned by matarife to the exclusion List, and now it works again.

**Comment by matarife123** [comment]
> > I see. Which games have you added to the Priority list?
> 
> ```
> "language": "English",
> "priority": [
>     "The Elder Scrolls Online",
>     "HUMANKIND",
>     "Warframe",
>     "Halo Infinite",
>     "For Honor",
>     "Overwatch 2",
>     "PUBG: BATTLEGROUNDS",
>     "PAYDAY 2",
>     "FIFA 23",
>     "Apex Legends",
>     "The Crew: Motorfest",
>     "Rocket League",
>     "Vampire: The Masquerade - Bloodhunt",
>     "Elite: Dangerous",
>     "BattleBit Remastered",
>     "New World",
>     "Sea of Thieves",
>     "Rust",
>     "Diablo IV",
>     "World of Warcraft",
>     "Conan Exiles",
>     "Cyberpunk 2077",
>     "Arena Breakout",
>     "Crossfire",
>     "Stream Raiders",
>     "STALCRAFT",
>     "Starsiege: Deadzone",
>     "World of Warships",
>     "The First Descendant",
>     "SYNCED",
>     "Riders Republic",
>     "Assassin's Creed Mirage",
>     "Veiled Experts",
>     "Ghostbusters: Spirits Unleashed",
>     "Warhaven",
>     "Party Animals",
>     "AK-xolotl",
>     "Operation Valor",
>     "Warhammer Age of Sigmar: Realms of Ruin",
>     "Gord",
>     "UNITED 1944",
>     "Disney Speedstorm",
>     "My Hero Ultra Rumble",
>     "DC Dual Force",
>     "Infestation: The New Z",
>     "Project: Arena",
>     "Cult of the Lamb",
>     "Project Winter",
>     "Freestyle Football R",
>     "From Space",
>     "EVE Online",
>     "BAPBAP",
>     "Marbles on Stream",
>     "Black Desert",
>     "Hellcard",
>     "Warhammer Online: Age of Reckoning",
>     "Crossout",
>     "Epic Seven",
>     "KartRider: Drift",
>     "Eternal Return",
>     "Conqueror's Blade",
>     "NARAKA: BLADEPOINT",
>     "Lost Ark",
>     "ArcheAge",
>     "SMITE"
> ```
> 
> However i got the same Error by having an empty Prio List and having "Priority only" disabled.
> 
> Adding to that though, i just added the Game mentioned by matarife to the exclusion List, and now it works again.

it's true WTF XD

**Comment by DevilXD** [comment]
This should now be fixed by https://github.com/DevilXD/TwitchDropsMiner/commit/1d2698872138e6dfb4f4625e678ba6db136917d9.

**Comment by Totesfleisch** [comment]
Tested both removed from Exclusion and in Prio List, indeed fixed! Thanks for the quick Work!
