### ISSUE TITLE
Progress bar does not reflect the actual progress on Twitch. Seem like we failed to update the minute watched event to Twitch?

### ISSUE THREAD

**Issue by 997133091** [DevilXD/TwitchDropsMiner#331]
Although the Progress bar in the twitchdropsminer shows I'm progressing, but the twitch Inventory page does not progress and still stay at the original progress percentage. 

version: 2023-10-19 20:12:19+00:00

**Comment by zelda0079** [comment]
Not working for new twitch drop now
https://github.com/DevilXD/TwitchDropsMiner/issues/301

**Comment by DevilXD** [comment]
Duplicate of #301.
