### ISSUE TITLE
The miner is mining a drop that's already claimed

### ISSUE THREAD

**Issue by zelda0079** [DevilXD/TwitchDropsMiner#334]
![](https://live.staticflickr.com/65535/53282564485_5e0aa70f81_o.png)
![](https://live.staticflickr.com/65535/53282566005_a6aa17342c_o.png)
But it only occurs on fishing planet twitch drop.

**Comment by DevilXD** [comment]
Hello there o/

This is weird. Are you sure you are logged in on the same account, both in the browser and the miner?

**Comment by scryptio** [comment]
I am getting this, too for several drop campaigns. This might be related to #301 and the current twitch changes. Their site got a problem, too I guess because currently progress can only be viewed (for recent drops as it seems) in the Inventory and not via the Profile Container top right anymore.

**Comment by DevilXD** [comment]
Drop claim status isn't easily deterministic, based only on the inventory. A campaign isn't returned by the inventory, if it isn't started yet - only the campaigns page returns it. Once it's started, it appears in the inventory, with progress attached to it. Once it's finished, it disappears from the inventory again, and goes back to existing only in the campaigns page. This means there's no real difference between a campaign which isn't started yet, and one that has been already finished.

To determine between these two states, I use the list of benefits claimed recently, and assume that if a benefit is claimed while a campaign was active at the time, then the drop can be marked as claimed too. This could potentially mark unclaimed drops as claimed though, but not the other way around. Ref comment from the code:

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/f5e615db-f584-4731-a339-c26267bbf999)

I'll take a closer look at this logic, once the new campaigns estabilish themselves more and more. Right now, I'm still seeing the old kind of campaigns being available, so don't really have anything reliable to test on.

**Comment by DevilXD** [comment]
I took a look at this, and there doesn't seem to be anything out of order. Please ensure you're using the latest dev version of the miner. If this issue appears again, I'd like to see your inventory page and how's the progress displayed there vs in the miner.

**Comment by DevilXD** [comment]
Does this issue still happen to anyone?

**Comment by DevilXD** [comment]
Closing because of no response.
