### ISSUE TITLE
My Farmer isn't finding any campaigns

### ISSUE THREAD

**Issue by Zhanyee** [DevilXD/TwitchDropsMiner#336]
The farmer is not finding any active campaigns for 3 months other than Smite, despite there being several campaigns that my account is connected to, it has not watched anything other than Smite while ignoring the other games for 3 months.

I tried reinstalling, I tried relogging, I tried using the old launcher, I tried using v16, but nothing worked.

I even checked Twitch to see if my account was connected to the other games, but even though it was connected, nothing worked.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/127443718/30e785ab-bceb-4eea-8970-2e4e8e6db70f)

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/127443718/228d75d3-b13f-42ec-a290-c5943563e7f5)

**Comment by Zhanyee** [comment]
Even my inventory isn't showing anything

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/127443718/f6f7bcd2-299e-4c67-9924-3fe5012f7092)

**Comment by DevilXD** [comment]
Hello o/

I see. Are you using the latest development version of the miner? The latest dev fix was as recent as 4 days ago. Deleting the `cookies.jar` file and logging again might help too.

Also, please take a look at the inventory and campaign pages, and let me know what do you see. Inventory should show in-progress campaigns. If there are none, you may start a new campaign by watching a stream of choice for ~5 minutes, then checking the inventory page again. The campaigns page should tell you if your account is connected to a particular campaign, or isn't.

https://www.twitch.tv/drops/inventory
https://www.twitch.tv/drops/campaigns

**Comment by Zhanyee** [comment]
I've watched for a few minutes and it is showing again, but I'll have to watch every game every time for the farmer to work from now on?

I'm using the version from 4 days ago.

**Comment by DevilXD** [comment]
> I'll have to watch every game every time for the farmer to work from now on?

I'm not sure what you mean. The miner cannot "magically" skip the watching part and give you the drops, you still have to wait their allocated amount of time to receive them.

**Comment by Skay100** [comment]
He means that games don't appear on the list unless he goes to twitch, launches a channel that's participating and then miner will have that game once progress is non-0%.

**Comment by DevilXD** [comment]
I see. The latest version of the miner should work for that though. The last time this was happening was a year ago, in #264, but it was resolved by changing the Client ID to mobile web one. Again, please ensure you're using the latest version of the miner, and also, please delete the `cookies.jar` file and login again within the miner.

To confirm the miner is seeing the campaigns, use the Inventory view and setup the filters like so:

![filters](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/d1b5b512-a95a-4cc7-b6d2-d87a58441a81)

This will show you all campaigns available to the miner.

**Comment by Skay100** [comment]
Yeah "Upcoming" specifically is not working for me on newest dev build, it also randomly stopped working on the previous one.

**Comment by DevilXD** [comment]
I've investigated this "issue", and concluded that Twitch just doesn't return "upcoming" campaigns anymore. If they aren't returned by the API, then I cannot "magically" get this information otherwise. This essentially means that the "Upcoming" filter in the inventory became quite useless now.

This is most likely related to the recent Twitch drops changes. More information can be found in #301.

Just to summarize, the current campaigns view returns 90 campaigns, 14 of which are `"EXPIRED"` and the rest of them are `"ACTIVE"`. There's no campaigns with `"UPCOMING"` status. If one with a status like that will ever be returned again, it'll show up in the miner automatically. Otherwise, I'm not removing any logic related to them, as everything works mostly the same way regardless.
