### ISSUE TITLE
Building on linux

### ISSUE THREAD

**Issue by MuffinzCat** [DevilXD/TwitchDropsMiner#341]
So I didn't really have an idea where to ask this, since I've tried to find documentation on it.
Basically I have a linux server running on an old desktop of mine, but it has a quieter PSU than my desktop, which runs windows.
I tried finding a build script, or instructions on what to do, but I couldn't find anything. I also tried WINE, but that didn't work either.
I was wondering if it's possible to either explain how to make a linux build, or if there's a possibility to get a linux build script of some sort?

**Comment by DevilXD** [comment]
Hello o/

Please note that TDM can only run on a machine with a display. If this Linux server has a display, then all you need is to follow the setup instructions here: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

Alternatively, you can just use the pre-built executable available in the Releases: https://github.com/DevilXD/TwitchDropsMiner/releases

**Comment by DevilXD** [comment]
I'm assuming this has been answered/resolved by now.
