### ISSUE TITLE
After the event reward is completed, the next reward will not be automatically carried out

### ISSUE THREAD

**Issue by fgr178707** [DevilXD/TwitchDropsMiner#351]
I've been stuck on the current page for over 5 minutes.
Must software reboot
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/109357981/df492b88-a5b9-4dad-97f6-92fc207ebea4)

Every 60 seconds it sends a request to the server.
But the reward is 0:00:00 and I have to click refresh in the settings to continue.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/109357981/402d9735-7c11-4a4d-b3fd-88ca739c20ce)

**Comment by DevilXD** [comment]
Please see #301.
