### ISSUE TITLE
Feature Request: Save inventory filter in config

### ISSUE THREAD

**Issue by LeaLangley** [DevilXD/TwitchDropsMiner#359]
Save the inventory filter in the configuration so that people like me, who only want to see specific drops, don't have to switch to it every time they start.

**Comment by DevilXD** [comment]
Hello. Which "specific drops" are you interested in, specifically?

**Comment by DevilXD** [comment]
Didn't mean to close this, my bad.

**Comment by LeaLangley** [comment]
hey , no worries.
i always uncheck "Expired" so i get a list of drops i still could farm.
so i thought it would be a nice idea if the inventory filters could get saved for the next launch of this tool.

**Comment by DevilXD** [comment]
Showing expired campaigns has been made the default [two weeks ago](https://github.com/DevilXD/TwitchDropsMiner/commit/725d54a1ca29405013e52649671ac25003453694), in an attempt to match what the Twitch webside shows, and to provide some useful feedback information to the user about what happened to their campaign that they were mining just now, or about what they've missed. Once a campaign expires, the Twitch website stops reporting it as available, but keeps it on display in the inventory view, for about further 24-48 hours, before it disappears completely. If a campaign would last only a few hours, and the user wasn't around at the time (and couldn't mine anything), they'd have simply missed the campaign entirely, and wouldn't know about it, until they'd toggle on the "Expired" filter.

I see no real need for saving the inventory filters. The inventory tab isn't required to be used in every-day use of the application. The in-app inventory view could entirely not exist, and the miner would still work as it's supposed to do so. The inventory view was added mainly as a convenience tool, to relieve you from using the Twitch website, which has no way to filter the content down to the campaigns you'd be interested in the most. Besides, the filters were never intended to be saved anyway, and adding all the framework required to enable that feature costs more time and effort, than unticking a single checkbox every so often.

How many expired campaigns do you have to scroll through, that has prompted you to ask for this feature to exist? I can just reverse the https://github.com/DevilXD/TwitchDropsMiner/commit/725d54a1ca29405013e52649671ac25003453694 commit, and everyone will go back to how it was before, knowing the fact that they could've missed on a campaign and won't know it.

**Comment by LeaLangley** [comment]
I love to use the inventory view in the miner, and I respect that others might have different filter interests. And that's why I thought saving the user's filter choice locally as a setting to be used on the next start would be a great idea. So everyone can choose their own flavor of what they want to be displayed without having to check/uncheck filters. Everyone could make their own filter settings.

**Comment by DevilXD** [comment]
This is easier to do: https://github.com/DevilXD/TwitchDropsMiner/commit/1e31957388869c56e2b21da38d11cc20dbde7cc2

Since no saving will be added, this is "fixed" via a commit revert and WontFix for now.
