### ISSUE TITLE
couple questions

### ISSUE THREAD

**Issue by josephisticated** [DevilXD/TwitchDropsMiner#36]
in the priority list, does it do it in order?
does it claim the drops automatically?
how do I use flags like `--tray` ?
if it does in order in priority list, will it stop the current one and go back to a more prioritized one once its available?

thanks a lot ❤️

**Comment by DevilXD** [comment]
Hello o/

> in the priority list, does it do it in order?

Yes, the games towards the top will be attempted to be mined first, if possible. If not, any game further down the list will be attempted, until the list is exhausted. If the "priority only" option is unchecked, the application will even attempt to mine games that are not on the list (that you have the account linked with), but you can disable this by checking the option (the default).

> does it claim the drops automatically?

Of course, it's in the application description on the main repo page: https://github.com/DevilXD/TwitchDropsMiner Just scroll down and read up.

> how do I use flags like `--tray` ?

You can create a shortcut to the application, and then add any flags you want after the file path. Sort of like this:
![obraz](https://user-images.githubusercontent.com/4180725/187609514-9b95d8e3-4ab8-4f80-be16-0acd4b89deb7.png)

> if it does in order in priority list, will it stop the current one and go back to a more prioritized one once its available?

Yes, this is considered as a part of the switch condition. The application only mines the games lower down the list, if the ones above them cannot currently be mined. If this condition changes, it switches back to mining higher priority ones.

Is there anything else I can answer you?

**Comment by josephisticated** [comment]
Thanks a lot for the awesome software, that's all I guess ❤️
