### ISSUE TITLE
Please add the game World of Tanks to the list.

### ISSUE THREAD

**Issue by MauserM1932** [DevilXD/TwitchDropsMiner#364]
Please add the game World of Tanks to the list.

**Comment by Kofiur** [comment]
World of Tanks is added to the list.

**Comment by DevilXD** [comment]
The miner works automatically. The list of games is constructed based on the campaigns that are currently active. Besides, the Priority list is a simple text field input - you can just type in the name of any game to add it. So no, no hard-coded game names will ever be added.
