### ISSUE TITLE
Won't mine "Deceive Inc."

### ISSUE THREAD

**Issue by jaredkotoff** [DevilXD/TwitchDropsMiner#369]
I have `Deceive Inc.` in my Priority list and there are streamers with the drop enabled but the bot is farming in a lower priority stream. 
There are also no channels listed in the Main tab with the game which makes it looks like three's an issue with this game. 
Is it the `.` in the name that's causing an issue?

**Comment by DevilXD** [comment]
Hello o/

The dot should make no difference. Please ensure you're using the latest version of the miner, and that you've restarted or reloaded the miner after modifying the priority list contents. Please also ensure the miner is able to find at least one online channel that is able to progress the higher priority game - if this condition isn't met, the next game off the list is considered.

If it still won't work, please attach a picture of what you see in the Inventory tab of the miner, as well as the main tab and it's channels list.

**Comment by jaredkotoff** [comment]
@DevilXD 
>  Please ensure you're using the latest version of the miner, and that you've restarted or reloaded the miner after modifying the priority list contents.

Yep! This game has been on my list for sometime. I did reload and even move it up to the top to test though. I also `git pull` each time i run the bot, so currently running [81d4e7b](https://github.com/DevilXD/TwitchDropsMiner/commit/81d4e7bc3cad38e5fe84cf2a87339dc7366e59b0)

> Please also ensure the miner is able to find at least one online channel that is able to progress the higher priority game - if this condition isn't met, the next game off the list is considered.

This is what seems like is happening but U don't know why when there *is* a channel that is live with drops.

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/3268576/ec41f7ca-228b-4fe8-9c34-0fad5fbf442f)

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/3268576/23a0f211-ae2c-420c-9ec8-43c6e43b5029)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/3268576/54a483f1-f185-4bda-8a16-7d7dc66ef7d3)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/3268576/2ef400ae-ae3b-41f6-b0e1-3290bc949235)

**Comment by jaredkotoff** [comment]
Hrmm, I linked my account and now its working 😑

**Comment by DevilXD** [comment]
Correct, a campaign is only considered as a valid mining target, if your Twitch account is linked to the campaign's game. Not linked games/campaigns aren't considered.

**Comment by jaredkotoff** [comment]
@DevilXD why though? I often want to get drops that I plan to get in the future. This could be a good option to add to the Settings tab

**Comment by DevilXD** [comment]
@jaredkotoff Because that goes against the project goals. For more information, you can read more here: https://github.com/DevilXD/TwitchDropsMiner#project-goals
