### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by TikGaming** [DevilXD/TwitchDropsMiner#370]
hi, how to loggin ? 
![Screenshot_1](https://github.com/DevilXD/TwitchDropsMiner/assets/14997868/7e3c3506-7fb9-4c59-913b-fea93d5e4e60)

**Comment by DevilXD** [comment]
A wild shot, since #80 doesn't throw an error anymore, it may still prevent successful connections to be made. Does disabling IPv6 help?

**Comment by DevilXD** [comment]
No idea then. If the issue persists, please create a new issue to describe your problem.
