### ISSUE TITLE
Can i get still get the reward from drops even if i haven't owned the game?

### ISSUE THREAD

**Issue by MrFutureV** [DevilXD/TwitchDropsMiner#375]
i know that sounds like a dumb question,but i just wonder like if I obtained drops without purchasing the game, will I still receive rewards from Twitch drops in the game if I buy it later?

**Comment by DevilXD** [comment]
Hello o/

From the Twitch Drops FAQ: https://help.twitch.tv/s/article/mission-based-drops?language=en_US

> To earn a Drops reward, you will need to be logged into Twitch. To be eligible to receive the Drop rewards in-game, you will need to have your game account linked to your Twitch account. If an account connection is required, you will see a message asking you to connect your game account after you have claimed the Drop.

> Tip: You can still claim rewards and then connect your account afterwards.

In other words, yes - it's possible. However, I'm not sure about the timeframe of the drops between you claiming then, and then buying the game, linking your account and receiving them in-game. I wouldn't bet on more than couple of days delay here - after that, the drops are lost, even if you claimed them. The old drops system gave the game developer up to two weeks to handle the drop rewards from each campaign, after which the campaign just disappeared.

Also, it's worth noting here that the miner won't consider games you haven't linked your account to as a valid mining target. Having an existing link is a requirement for the miner to mine the campaign of a game of your choice.

**Comment by MrFutureV** [comment]
> Hello o/
> 
> From the Twitch Drops FAQ: https://help.twitch.tv/s/article/mission-based-drops?language=en_US
> 
> > To earn a Drops reward, you will need to be logged into Twitch. To be eligible to receive the Drop rewards in-game, you will need to have your game account linked to your Twitch account. If an account connection is required, you will see a message asking you to connect your game account after you have claimed the Drop.
> 
> > Tip: You can still claim rewards and then connect your account afterwards.
> 
> In other words, yes - it's possible. However, I'm not sure about the timeframe of the drops between you claiming then, and then buying the game, linking your account and receiving them in-game. I wouldn't bet on more than couple of days delay here - after that, the drops are lost, even if you claimed them. The old drops system gave the game developer up to two weeks to handle the drop rewards from each campaign, after which the campaign just disappeared.
> 
> Also, it's worth noting here that the miner won't consider games you haven't linked your account to as a valid mining target. Having an existing link is a requirement for the miner to mine the campaign of a game of your choice.

hey thx for explaning，i get it :D
