### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by AlexBarlas** [DevilXD/TwitchDropsMiner#376]
Do I need to keep the channels open in order to track progress? Example I have an active campaign but the % stays the same 70% of 240 minutes... even if I click refresh after 1 minute or 15 minutes..

Also, It shows as X Not linked but my twitch account is linked.

**Comment by SimonAkers** [comment]
Hi, in my experience the progress should update as normal, as if you were watching the stream yourself.

Are you using the latest development version? The Twitch API changes occasionally which breaks old versions, the latest updates to the repo should work right now. The latest release version is not functional to my knowledge.

**Comment by DevilXD** [comment]
Hello @AlexBarlas,

Please ensure you're using the latest development version of the miner. The latest release version isn't supported anymore, and some of the older dev versions won't progress the campaigns properly, and instead cause exactly what you're reporting. The issue was fixed by this commit: https://github.com/DevilXD/TwitchDropsMiner/commit/bb51bf740070d867d7973fbe6c014b347b349064. Let me know if the latest version solves your issue.

**Comment by biast12** [comment]
Hey @DevilXD, i'm not sure i understand your comment, i have both tried the latest dev build and the latest commit and both don't seem to work for me, i can see under inventory that there's active campaigns but they aren't watching, any way you can link to the exact build you mean so i can have a try?

with that did i also notice a bug (not sure if it's already reported or not), when you're in your inventory does it only display things if you got show exclusive enabled, for an example, if i select `Not linked` then it's not showing anything, but if i select `Not linked` and `Exclusive` then is displays both `Not linked` and `Exclusive`

**Comment by AlexBarlas** [comment]
Hi @DevilXD, It was working fine yesterday and today my windows defender decided it doesn't like the app due to a virus and deleted the .exe file and I can't download it again either (chrome blocks the download with a "virus found" label).. I tried downloading the dev-build and building the .exe myself but I'm being hit with a "No module named 'yarl' found" when I run build.dat and pip install yarl yields a "Could not build wheels for multidict

**Comment by biast12** [comment]
Hey @AlexBarlas you can add an exclusion for the app in your windows defender, you can read move about how here: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26

**Comment by DevilXD** [comment]
> my windows defender decided it doesn't like the app due to a virus and deleted the .exe file and I can't download it again either (chrome blocks the download with a "virus found" label)

1. Don't use Windows Defender as your antivirus - I can recommend ESET myself, but even BitDefender is smarter than that.
2. If you absolutely have to stick with Windows Defender, add it as a scanning exception.

> I tried downloading the dev-build and building the .exe myself but I'm being hit with a "No module named 'yarl' found" when I run build.dat and pip install yarl yields a "Could not build wheels for multidict

`build.bat` won't work without the virtual environment setup first - for that, use the `setup_env.bat` before building. If you'd be running into permission errors, running the scripts as Administrator may help. Alternatively, you can follow the [manual instructions](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions) as well.

If you'd mess up the venv setup, or somehow still get errors about missing modules, remember than you can always delete the `env` folder and recreate it by running `setup_env.bat` again.

**Comment by DevilXD** [comment]
Are you still having issues running the miner? If not, this issue can be closed I guess.
