### ISSUE TITLE
Can this software add custom channels?

### ISSUE THREAD

**Issue by hrmlsr** [DevilXD/TwitchDropsMiner#38]
If some dorps say like "To continue the progress, go to a participating live channel including /XXX",then this software will only mine the channel XXX,but other channels maybe also have drops.
Can this software add custom channels use name or url?

**Comment by DevilXD** [comment]
Hello o/

Not really, no. I've never seen an information like that though, there's no drops that have to be partially mined across different channels that I know of. Best you can do is use the "Switch" button to select a particular channel from the channel list, but it'd have to be already there for that to work.

Do you have an example of a drop / campaign where the drop is you're talking about? I'd like to take a closer look.

**Comment by hrmlsr** [comment]
![QQ图片20220910173819](https://user-images.githubusercontent.com/32532458/189477875-9f91ada6-5572-4cc1-9d09-ec2f61625feb.png)
![QQ图片20220910174250](https://user-images.githubusercontent.com/32532458/189477947-62c4ba95-8b12-45a3-b584-01a2fe8f4a6f.png)
This drop said "You're earning toward the rewards on [/thisheep](https://www.twitch.tv/thisheep)",but it can drop in any channel wtih a tag "worldofwarships",for example "https://www.twitch.tv/angelplays"

**Comment by DevilXD** [comment]
The campaign you've mentioned has a disabled ACL:
![obraz](https://user-images.githubusercontent.com/4180725/189484001-6063434f-dae7-40e0-a59b-7c2e8b41ea83.png)

Your issue sounds exactly like #37, please check out the discussion there. Please also confirm that the application is working properly now, and the "Allowed Channels" section on the Inventory tab of the application says "All" for the campaign in question.

**Comment by hrmlsr** [comment]
![QQ图片20220910205854](https://user-images.githubusercontent.com/32532458/189484468-a05f5e30-b725-4f00-a688-bbfe8836583c.png)
![QQ图片20220910205850](https://user-images.githubusercontent.com/32532458/189484470-6c10408d-fbf5-4d86-8ba6-c0566d965738.png)
![QQ图片20220910210150](https://user-images.githubusercontent.com/32532458/189484562-32002397-1bdb-43a0-a31f-6f1ca37376da.png)
hisheep  was lived 3 day ago，and I get zhe drop in other channel today.
![QQ图片20220910210742](https://user-images.githubusercontent.com/32532458/189484839-d47660b2-e3a7-4488-ba5e-8247118f09e0.png)

**Comment by DevilXD** [comment]
Okay, but this doesn't matter. I told you to see the discussion under [#37](https://github.com/DevilXD/TwitchDropsMiner/issues/37)

Is it mining properly now?

**Comment by hrmlsr** [comment]
I got all drops by web browser already.
Next reward progress will begin on Sep 16,I will try then.

**Comment by DevilXD** [comment]
When you see a situation like this happen next time, please use the "Reload" (刷新) button on the Settings (设置) tab, to see if this solves your issue.

**Comment by hrmlsr** [comment]
![QQ图片20220916191018](https://user-images.githubusercontent.com/32532458/190626341-785c95db-2a04-48c9-87c3-7872a8788fcb.png)
![QQ图片20220916191011](https://user-images.githubusercontent.com/32532458/190626347-17797dce-4208-494f-bf52-15e3a1cdd0a8.png)
![QQ图片20220916191015](https://user-images.githubusercontent.com/32532458/190626353-1b022f89-abb3-4db9-aaa0-01acbd16f0eb.png)
It's the same,what should I do now?

**Comment by DevilXD** [comment]
![obraz](https://user-images.githubusercontent.com/4180725/190629513-35a5b7be-93f7-4e3c-87f6-8f3745904091.png)

Notice how your picture mentions only the "thisheep" channel, while mine says "All". As I've already told you, please use the "Reload" button when this happens next time, to see if that fixes your issue:
![obraz](https://user-images.githubusercontent.com/4180725/190629954-9226b155-b7a0-436c-aa01-649c7def09e1.png)

**Comment by hrmlsr** [comment]
![QQ图片20220916205830](https://user-images.githubusercontent.com/32532458/190644501-37d8b00f-8546-410c-b5a8-a92902766de9.png)
I am sure I did that many times,but nothing changed.
![QQ录屏2022091621103220229162112331](https://user-images.githubusercontent.com/32532458/190646994-2e24e790-7030-4696-96e6-5bdf3ea652c2.gif)

**Comment by DevilXD** [comment]
I am unable to reproduce the issue on my end, the campaign allows all channels for me.

Please restart the application and check the Inventory tab, to ensure the "Allowed channels:" says "All" now, like on my picture:
![obraz](https://user-images.githubusercontent.com/4180725/190656741-3d408d60-d9b2-4456-b08d-c3c5eb51d2ac.png)

If it still doesn't, then you'll have to check on the https://www.twitch.tv/drops/campaigns page and ensure that this particular campaign really does allow all channels there. Before doing so, I recommend ensuring that you're using the same account between the website and the application - the accounts cannot differ. There is a possibility Twitch is doing some kind of regional or selective treatment where the ACL isn't disabled, which would result in the issue you're experiencing.

If neither of those would help, then unfortunately I am unable to help you, as this issue does not appear on my side - without being able to reproduce it, I cannot fix it.

**Comment by DevilXD** [comment]
I made a test change for the upcoming `v13` release, that could help your issue - I doubt it, but it could. You can try it out by getting the unofficial `v13.dev` release from this comment: https://github.com/DevilXD/TwitchDropsMiner/issues/40#issuecomment-1249482503

Please try it out and report back on your findings. I also expect you to confirm everything I've explained in the previous message too, of course.

**Comment by hrmlsr** [comment]
This release show as all channels,it maybe worked.I will try it next week.Thanks.

**Comment by DevilXD** [comment]
Hello o/

If this would happen to you again, please open another issue.
