### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by slowtanking** [DevilXD/TwitchDropsMiner#380]
Please forgive me if this has been answered already, I was unable to find it.  New to this Miner and just started trying to use it today.  From first launch it provides me with a fatal error and I have no idea how to resolve it.  Thanks for any help.
![Miner Error](https://github.com/DevilXD/TwitchDropsMiner/assets/153357010/7d90194c-a839-4fb9-b148-fc20ec80d3de)

**Comment by DevilXD** [comment]
v15 is not supported since almost a year now. Use the latest development build instead.
