### ISSUE TITLE
[Feature] In/Exclude specific Channels, Drops of a game, Items of a drop

### ISSUE THREAD

**Issue by rudowinger** [DevilXD/TwitchDropsMiner#381]
Aside from Games to include, exclude, it would be nice to have a similar selection available for:

- Priority Channels
- Priority Drops
- Priority Items

"Text" match like Priority Games would be great

**Comment by DevilXD** [comment]
Hello o/

Priority Channels goes against the [project goals](https://github.com/DevilXD/TwitchDropsMiner#project-goals), in the sense that this is a drop-oriented application, and any valid channel that is able to progress a drop is just as good as any other that can do the same thing. You can switch between channels manually if you'd really want to, at least until the application decides to switch away from it.

Priority Drops aren't really needed - just make sure you setup your Priority list properly, and the drop from the game you care about the most will be mined first. That's all.

Priority Items falls under the above as well. Regarding excluding drops, there already is an open issue for pretty much the same thing: #170.

With that, this entire issue is a NoFix and a Duplicate, so I'm closing it as such.

**Comment by rudowinger** [comment]
Hi!
#170 woulr even be a better solution!

Thinking of the Use Case:

Game
- Team Red Drop
-- Guy 1 Drop
-- Guy 2 Drop

... where one only wants Guy 2 Drop

So tickboxes to drops would be awesome!
