### ISSUE TITLE
Cannot connect to Twitch, retrying in...

### ISSUE THREAD

**Issue by GitThisAcc** [DevilXD/TwitchDropsMiner#383]
Hello 😃 

On a freshly installed Windows 11 machine, in the same room and same network - the application isn't able to run.. for some reason.
I deleted the settings/cookies/cache - nothing changes:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/13767589/0c5828a5-ac23-49d6-b265-bb1731b53483)

Disabled IPv6 on that machine, exception in Windows Defender/Firewall.
The machine is able to connect to m.twitch.tv with Edge and Firefox without problems.
I use the prebuild exe from this repo.

**Comment by DevilXD** [comment]
What about accessing https://id.twitch.tv/oauth2/validate ? The page should load into a JSON payload that looks like this:
![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/7c0582e5-d851-45d9-b87a-aaaab8c22e40)

**Comment by DevilXD** [comment]
Then if you'd try the fork without Docker, it'd still not work - as I said, the fork has no functional difference, the same URLs are accessed, etc.

Fork or not, the issue appears to be somewhere else. But nothing more comes to my mind right now.

**Comment by DevilXD** [comment]
Looks kinda like a DNS issue to me. Maybe try a `ipconfig /flushdns`? Set your DNS server to `1.1.1.1` temporarily?
