### ISSUE TITLE
Code in exe detected as trojan Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by ProCasual** [DevilXD/TwitchDropsMiner#384]
Executable is being detected as (presumably) false positive for trojan Wacatac.B!ml by Windows Security:

![image](https://github.com/DevilXD/TwitchDropsMiner/assets/127465731/b259f10f-125f-4849-95b4-db8491d61462)

**Comment by DevilXD** [comment]
This is a duplicate of #335, #333, #315, #284, #270, #249, #217, #209 and #13. Please do some minimum searching of the closed issues before reporting new ones, next time.
