### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by Kannumberone** [DevilXD/TwitchDropsMiner#385]
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/153576731/0f05d5bf-b634-477d-9236-0ecdebec4d66)

**Comment by Kannumberone** [comment]
I dont know how use #314 method
If it’s not difficult for you, can you send me the finished exe?
@DevilXD

**Comment by schmic** [comment]
@Kannumberone download the latest build here: https://github.com/DevilXD/TwitchDropsMiner/releases/tag/dev-build

v15 is not working anymore

**Comment by DevilXD** [comment]
Don't use v15. Read the description carefully.
