### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by Leetoi** [DevilXD/TwitchDropsMiner#388]
10:24:20: Fatal error encountered:
10:24:20: 
10:24:20: Traceback (most recent call last):
10:24:20:   File "main.py", line 158, in main
10:24:20:   File "twitch.py", line 765, in run
10:24:20:   File "twitch.py", line 807, in _run
10:24:20:   File "twitch.py", line 1604, in fetch_inventory
10:24:20:   File "twitch.py", line 1605, in <dictcomp>
10:24:20:   File "utils.py", line 112, in timestamp
10:24:20:   File "_strptime.py", line 568, in _strptime_datetime
10:24:20:   File "_strptime.py", line 349, in _strptime
10:24:20: ValueError: time data '2023-12-12T12:20:22.167Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
10:24:20: 
10:24:20: Exiting...
10:24:20: 
10:24:20: Application Terminated.
10:24:20: Close the window to exit the application.

Help pls

**Comment by SimonAkers** [comment]
Hi, I see that you have closed this issue as completed. For future reference if anyone sees this thread, this has to do with a bug that was fixed in #314. Just make sure you're using the latest development version (e.g. the current master branch) and it should work.
