### ISSUE TITLE
Authentication Issue: V16 Auto-Login Attempting Without Inputting Credentials (Unable Due to Grayed-Out Fields)

### ISSUE THREAD

**Issue by Nicklordzero** [DevilXD/TwitchDropsMiner#396]
I've been digging into the Windows application for the project, and it's been a bit of a head-scratcher. For some reason, all the buttons are just sitting there, taunting me in shades of gray, and I can't seem to make a move. Figured I'd drop you a line and see if we could team up to troubleshoot this hiccup.

Any chance you could lend a hand and help me figure out what's going on? I've got my sights set on claiming those rust drops, and the sooner we can iron out this issue, the better. Your expertise would be a game-changer here, and I'm genuinely looking forward to getting back on track. Thanks a bunch!

**Comment by DevilXD** [comment]
Hello o/

First of all, please provide some more explanation to the issue. The title mentions "grayed out fields". There's no fields involved in the logic process, besides the "Login" button of the login form. If it's grayed out, that means the application isn't actively trying to login. Status of the login process is displayed in the login form as well. The login process involves inputting the displayed code, on a page that's open after clicking the Login button - you don't input any actual credentials (login or password).

If you're having problems with logging in, the best way to resolve them is to delete the `cookies.jar` file, and then start the miner. It should try again to reauthenticate the miner afterwards.

Please let me know if that solves your issue.

**Comment by DevilXD** [comment]
Closing because of no response.
