### ISSUE TITLE
Drops not working for "not linked" campaigns...

### ISSUE THREAD

**Issue by Xrdem** [DevilXD/TwitchDropsMiner#399]
Tittle says it all..I don't know where log file is but here some screenshots
![Capture](https://github.com/DevilXD/TwitchDropsMiner/assets/116120205/e0f4de94-11e2-4ee7-8acf-fa49e54cf52c)
![Capture2](https://github.com/DevilXD/TwitchDropsMiner/assets/116120205/5e0806a3-e251-4e15-904f-7044ca1df804)

**Comment by DevilXD** [comment]
Having your account linked is a requirement for the miner to even consider a campaign worth mining, as you cannot claim drops for a game you don't have linked. I'm assuming you're simply confused about this. This is mentioned in the miner on the Help tab, in the 2nd point of the instructional.

**Comment by Xrdem** [comment]
I don't know that but you could add option to miner "mine not linked campaign" ..Maybe some other time somebody play you never know..

**Comment by DevilXD** [comment]
I don't know that, but you could read the project goals and don't bother me with features that will never be implemented. This topic was already brought up endless times in the past.

https://github.com/DevilXD/TwitchDropsMiner#project-goals
