### ISSUE TITLE
Endless connection to Twitch

### ISSUE THREAD

**Issue by sgholley** [DevilXD/TwitchDropsMiner#400]
There is a VDS server on Windows 2012 R2, if you run through the exe file, there is an endless download, and if you try through python, it does not start at all. Is there some kind of guide or solution? I looked through all the questions and did not find a solution. Run_dev not run

**Comment by DevilXD** [comment]
Hello.

> there is an endless download

> it does not start at all.

None of these descriptions are helpful for diagnosing your issue in any way. Please provide some actually meaningful information regarding what you're having an issue with. A screenshot of what you see if often sufficient.

What "download" are you referring to? There's nothing the miner "downloads", maybe besides the images that are displayed in the application, that are cached locally.

**Comment by sgholley** [comment]
> Hello.
> 
> > there is an endless download
> 
> > it does not start at all.
> 
> None of these descriptions are helpful for diagnosing your issue in any way. Please provide some actually meaningful information regarding what you're having an issue with. A screenshot of what you see if often sufficient.
> 
> What "download" are you referring to? There's nothing the miner "downloads", maybe besides the images that are displayed in the application, that are cached locally.

I use a translator to communicate, so I'm sorry for the inaccuracy. If you run it via exe, then the log says failed to connect to Twitch attempt....
From another question, I realized that the problem was with the SSL certificate, so I tried to download the Sourse version. But I am completely unable to run the run_dev file. In the console, write run with the y/n console and after selecting it, it just closes and nothing happens.

**Comment by sgholley** [comment]
![Screenshot (2)](https://github.com/DevilXD/TwitchDropsMiner/assets/49320291/1f380f51-7383-4786-93c7-8be783c4959e)
error in setup_env

**Comment by sgholley** [comment]
the bulid folder is empty after all bulid startup processes.bat and after 1 launch, nothing further happens

**Comment by sgholley** [comment]
when running run_dev and turning on the console, it throws an error and closes
![Screenshot (17)](https://github.com/DevilXD/TwitchDropsMiner/assets/49320291/7689103b-19dc-46d3-ac14-07fa424659e2)

**Comment by DevilXD** [comment]
The cause for your issues is clearly printed out to you:

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/2ec1007c-fb83-4363-8af4-908efcd5d539)

As for why is that needed - it looks like `aiohttp` or one of it's dependencies, was never meant to be ran on a Windows Server, so there's no pre-built binaries provided. You can still install the module though, but it has to be built locally, and that's what you'll need the VC++ v14+ for.

**Comment by sgholley** [comment]
Need download VC++?

**Comment by DevilXD** [comment]
Use the link provided to you by the error message.

**Comment by sgholley** [comment]
And you will not be able to implement disabling the SSL certificate protocol in the exe as described by the people in #386. You can immediately put a monument for this

**Comment by sgholley** [comment]
> Воспользуйтесь ссылкой, указанной в сообщении об ошибке.

because he writes to me that MS C++ is not supported

**Comment by DevilXD** [comment]
Even though the outcome appears to be the same, #386 is a different issue from this one - not sure why you're bringing it up, it does not apply here.

> MS C++ is not supported

I cannot help you then. The error comes from installing one of the dependencies, `multidict` by the looks of it. You can google it and then try to follow some instructions there: https://www.google.com/search?q=multidict+visual+c%2B%2B

Alternatively, try searching the existing multidict issues for this exact problem: https://github.com/aio-libs/multidict/issues

**Comment by sgholley** [comment]
Solved the problem. I found the instructions on the forums and did everything. I share it here in case someone gets into the same situation. The server is running on Windows 2012 R2.

To install Microsoft Visual C++ 14.0, you can download the [Microsoft Build Tools for Visual Studio 2017](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15), install and open it, select: Workloads → Visual C++ build tools
If above still not resolve your issue, you can try to switch to Individual components, scrolling down the list of Individual components, there was a section titled Compilers, build tools, and runtimes. Under that section there was a VC++ 2015.3 v140 toolset for desktop (x86,x64) option and select it
![UECWk](https://github.com/DevilXD/TwitchDropsMiner/assets/49320291/a9e3965d-3c93-4d24-a8c4-1761d41c4309)
