### ISSUE TITLE
How to fix? Latest version... 15  ValueError: time data '2023-11-04T13:20:54.534Z' does not match format '%Y-%m-%dT%H:%M:%SZ'

### ISSUE THREAD

**Issue by Chita199853** [DevilXD/TwitchDropsMiner#409]
How to fix? Latest version... 15 
 ValueError: time data '2023-11-04T13:20:54.534Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/16305613/a749f1be-338c-4be2-ab6f-e55909b23338)

**Comment by DevilXD** [comment]
Where did you even get this. I removed the option to download v15, because it's dead for over half a year now.

![picture](https://github.com/DevilXD/TwitchDropsMiner/assets/4180725/dcdeb216-523e-4528-b800-3006cec85a43)

Closing as yet another duplicate.
