### ISSUE TITLE
Facing Issue while running in Pi 5

### ISSUE THREAD

**Issue by Stiphr** [DevilXD/TwitchDropsMiner#413]
System: Raspberry Pi 5 8GB
Os: Pi Os x64

showing this when i use `pip install -r requirements.txt`

`(env) rgxpi@rgxpi:~/Downloads/TwitchDropsMiner-master $ pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Collecting aiohttp<4.0,>=3.9
  Using cached aiohttp-3.9.1-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (1.3 MB)
Collecting Pillow
  Using cached pillow-10.2.0-cp311-cp311-manylinux_2_28_aarch64.whl (4.3 MB)
Collecting pystray
  Using cached pystray-0.19.5-py2.py3-none-any.whl (49 kB)
Collecting PyGObject
  Using cached PyGObject-3.46.0.tar.gz (723 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  Ã pip subprocess to install build dependencies did not run successfully.
  â exit code: 1
  â°â> [44 lines of output]
      Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple, https://www.piwheels.org/simple
      Collecting setuptools
        Using cached https://www.piwheels.org/simple/setuptools/setuptools-69.0.3-py3-none-any.whl (819 kB)
      Collecting wheel
        Using cached https://www.piwheels.org/simple/wheel/wheel-0.42.0-py3-none-any.whl (65 kB)
      Collecting pycairo
        Using cached pycairo-1.25.1.tar.gz (347 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: pycairo
        Building wheel for pycairo (pyproject.toml): started
        Building wheel for pycairo (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        Ã Building wheel for pycairo (pyproject.toml) did not run successfully.
        â exit code: 1
        â°â> [15 lines of output]
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-aarch64-cpython-311
            creating build/lib.linux-aarch64-cpython-311/cairo
            copying cairo/__init__.py -> build/lib.linux-aarch64-cpython-311/cairo
            copying cairo/__init__.pyi -> build/lib.linux-aarch64-cpython-311/cairo
            copying cairo/py.typed -> build/lib.linux-aarch64-cpython-311/cairo
            running build_ext
            Package cairo was not found in the pkg-config search path.
            Perhaps you should add the directory containing `cairo.pc'
            to the PKG_CONFIG_PATH environment variable
            Package 'cairo', required by 'virtual:world', not found
            Command '['pkg-config', '--print-errors', '--exists', 'cairo >= 1.15.10']' returned non-zero exit status 1.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for pycairo
      Failed to build pycairo
      ERROR: Could not build wheels for pycairo, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã pip subprocess to install build dependencies did not run successfully.
â exit code: 1
â°â> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by Stiphr** [comment]
New issue

python main.py
Traceback (most recent call last):
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/pystray/_appindicator.py", line 24, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/main.py", line 26, in <module>
    from twitch import Twitch
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/twitch.py", line 38, in <module>
    from gui import GUIManager
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/gui.py", line 21, in <module>
    import pystray
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/pystray/__init__.py", line 64, in <module>
    Icon = backend().Icon
           ^^^^^^^^^
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/pystray/__init__.py", line 56, in backend
    return candidate()
           ^^^^^^^^^^^
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/pystray/__init__.py", line 28, in appindicator
    from . import _appindicator as backend; return backend
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/pystray/_appindicator.py", line 27, in <module>
    gi.require_version('AyatanaAppIndicator3', '0.1')
  File "/home/rgxpi/Downloads/TwitchDropsMiner-master/env/lib/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available
****

**Comment by Stiphr** [comment]
nvm fixed

**Comment by Stiphr** [comment]
fixed

**Comment by TeddJohnson** [comment]
do you wanna share how it was fixed?

**Comment by Stiphr** [comment]
It was temporary fix and it's keep crashing at the end I sold my raspberry Pi 5 and bought Lenovo think tiny
