### ISSUE TITLE
Any way to set config files directory?

### ISSUE THREAD

**Issue by fireph** [DevilXD/TwitchDropsMiner#425]
I would like to run TwitchDropsMiner but have all the config files (settings.json/cookies.jar/cache) in a different folder from the executable. Is this currently possible? I am using the PyInstaller executable.

**Comment by DevilXD** [comment]
Hello o/

What's the reason for why you'd need to split those files like that? I do not see one, that's why this hasn't been done yet, nor any means of making this possible were implemented.

**Comment by fireph** [comment]
I am running the app inside of a docker container and trying to mount the config files to be persistent.

**Comment by DevilXD** [comment]
Running this thing inside a docker container is not supported. Running the miner on a remote server is not supported either. This is a personal miner, intended to run on your personal PC. I cannot help you for that matter.

Please see the project goals for reasoning about this decision: https://github.com/DevilXD/TwitchDropsMiner#project-goals

There are other projects out there that may work out better for you, than this project.
