### ISSUE TITLE
Rebuilt new version now i'm getting this error.

### ISSUE THREAD

**Issue by hakutzu** [DevilXD/TwitchDropsMiner#426]
![PlhONPM 1](https://github.com/DevilXD/TwitchDropsMiner/assets/20157910/12a3d1d3-682d-4cfc-9ed5-0aabdca8d441)

**Comment by guihkx** [comment]
You have to update the dependencies ([see step #3 in specific](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running#manual-instructions)).

**Comment by DevilXD** [comment]
Correct. You can also just delete the `env` folder, and then run `setup_env.bat` again, to recreate the virtual environment with all the correct packages installed.

**Comment by DevilXD** [comment]
I'm assuming the issue has been resolved by now.
