### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by guihkx** [DevilXD/TwitchDropsMiner#427]
Why it's a positive thing:

>You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

[Source](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

If you're unsure of what license to choose, [choosealicense.com](https://choosealicense.com/) and  [tldrlegal.com](https://www.tldrlegal.com/) are great resources.

**Comment by DevilXD** [comment]
> no one may reproduce, distribute, or create derivative works from your work.

I never really planned for a license to be included. The law only applies if I'd take my time to actually seek legal resolve, which I've had no need for so far.

What do you think about an MIT license for this project? I don't want to make it too restrictive.

**Comment by guihkx** [comment]
That's understandable, but having a clear license is also good to avoid ambiguity with contributions coming from third-party.

I'm not a lawyer, and so for example I have no idea of under what license my contributions were made against, or even if I actually "own them". lol

And it's not that I personally care about them, but other future contributors might...

>What do you think about an MIT license for this project? I don't want to make it too restrictive.

I always go with MIT for my personal projects, so for me that's a good choice.

**Comment by DevilXD** [comment]
> I have no idea of under what license my contributions were made against, or even if I actually "own them". lol

According to https://choosealicense.com/no-permission/, you retain all ownership rights to all code modifications you've introduced, and per [Github ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service):

> You grant us and our legal successors the right to store, archive, parse, and display Your Content, and make incidental copies, as necessary to provide the Service, including improving the Service over time. This license includes the right to do things like copy it to our database and make backups; show it to you and other users; parse it into a search index or otherwise analyze it on our servers; share it with other users; and perform it, in case Your Content is something like music or video.  
> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).

That's about it. Technically, you retain the right to "take away" your contribution at any time, and I'm legally obligated to allow you to do so, for example by removing all of your changes.

I guess I'll be adding the MIT license then.

**Comment by DevilXD** [comment]
https://github.com/DevilXD/TwitchDropsMiner/commit/d7c2c8d5c3fd8e258c90e70275bfe0fe0722f586 implements the license addition.

**Comment by guihkx** [comment]
Thanks for the clarification on that, very interesting.

I guess l can close this one now. :)
