### ISSUE TITLE
Drops campaigns that can't be linked/connected until the drop is earned

### ISSUE THREAD

**Issue by gibbed** [DevilXD/TwitchDropsMiner#432]
Is there a way to force the application to progress a campaign that won't allow linking until the drop is earned?

The upcoming HELLDIVERS 2 campaign requires you to have acquired the drop before linking can occur.

**Comment by DevilXD** [comment]
> Is there a way to force the application to progress a campaign that won't allow linking until the drop is earned?

No, and there won't be, as it's against the project goals. Please see the project goals here: https://github.com/DevilXD/TwitchDropsMiner#project-goals

> The upcoming HELLDIVERS 2 campaign requires you to have acquired the drop before linking can occur.

You will have to earn this drop the usual way, as this miner won't allow earning progress for a drop unless the account is linked first. Also, the https://www.twitch.tv/drops/campaigns page shows the "Connect" button like for any other campaign, so you should be able to link your account just fine. If the game developer specifically disallows the completion of the linking process for any reason, then that's beyond the scope of this project. If you'd be having troubles linking, performing a clean reconnect may help: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

**Comment by gibbed** [comment]
Yeah, I did see the project goals; since this was an edge case I figured I'd ask despite that.

The Connect button for this campaign takes you to a page that blocks linking/connecting without having earned the drop.

Thanks for the quick response!

**Comment by DevilXD** [comment]
I'm assuming this is a single-time occurrence, as any further drops will come after you already have your account linked. A single one hour drop shouldn't be that much of a pain to get.
