### ISSUE TITLE
Unable to detect “Escape from Tarkov Arena” connect

### ISSUE THREAD

**Issue by portal-cat** [DevilXD/TwitchDropsMiner#445]
Hello there! 

Currently, the connect of "Escape from Tarkov Arena" on Twitch is the same as the connect with "Escape from Tarkov." However, Twitch is not accurately displaying the connection for "Escape from Tarkov Arena," which leading to the software's inability to initiate the drops activity. 

I have conducted tests, and even though Twitch does not exhibit the link with "Escape from Tarkov Arena," the Drops & Rewards is still effective. 

Thank you for your time and efforts in maintaining this awesome program!

**Comment by DevilXD** [comment]
Hello. I'm assuming you've resolved your issue by yourself?

**Comment by portal-cat** [comment]
> Hello. I'm assuming you've resolved your issue by yourself?

Kind of. I noticed that Twitch fixed the connect for "Escape from Tarkov Arena" after the first day of drops. Thank you for your attention!
