### ISSUE TITLE
TwitchDropsMiner detects no association and therefore does not hang treasure.

### ISSUE THREAD

**Issue by a958946359** [DevilXD/TwitchDropsMiner#447]
Twitch was linked to the battle.net.  But twitch shows no correlation.  This causes TwitchDropsMiner to detect no association, so it does not hang the treasure. 
![dc25b8ec667eecd35625fbd8bf5d883](https://github.com/DevilXD/TwitchDropsMiner/assets/135683016/5d24bf2f-711a-42a8-b598-8fa9f71e80ec)

**Comment by DevilXD** [comment]
Not being able to link your account is not an issue with the miner, but with Twitch itself. I cannot help you resolve Twitch-related issues.

You can follow the "clean reconnect" instructional from here: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

There's no other way I can help you here.
