### ISSUE TITLE
Sorry if this is in the wrong spot! Is a dark theme ever possible?

### ISSUE THREAD

**Issue by Majaura** [DevilXD/TwitchDropsMiner#450]
Really sorry if this isn't in the right spot. I barely know how to use github. I love the app, but my eyes get burned out of my skull! I would so deeply appreciate a dark theme.

**Comment by DevilXD** [comment]
Dark mode was already suggested before, and is tracked by #197. You can check out the discussion there to try and compile your own version with one of the other preset themes, if you're desperate.
