### ISSUE TITLE
How can i use this to farm channel points? 

### ISSUE THREAD

**Issue by ranehal** [DevilXD/TwitchDropsMiner#451]
How can i use this to farm channel points? TIA

**Comment by DevilXD** [comment]
Hello o/

This project is called "Twitch Drops Miner", not "Twitch Points Miner". The main goal is to get Twitch Drops, not Channel Points. You do get channel points while using this application, but they're a result of trying to get the drops, not the other way around. There is no way to mine channel points from specific channels.

This is also explained in the project goals: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

**Comment by ranehal** [comment]
> Hello o/
> 
> This project is called "Twitch Drops Miner", not "Twitch Points Miner". The main goal is to get Twitch Drops, not Channel Points. You do get channel points while using this application, but they're a result of trying to get the drops, not the other way around. There is no way to mine channel points from specific channels.
> 
> This is also explained in the project goals: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

Thank you so much for your reply, looking forward to get a channel points miner with nice gui from you. Have a nice day
