### ISSUE TITLE
GQL API return error "Unauthorized"

### ISSUE THREAD

**Issue by coodrag** [DevilXD/TwitchDropsMiner#452]
I try to learn your code, and create my own twitch client_id.

I successfully get my access_token from oauth2 api:
`{
    "access_token": "q9xxwlug2x24uamy69j6u7j0w4iir6",
    "expires_in": 14450,
    "refresh_token": "fq7q5d8o4950sqe4uwqhb1yepafeyqa2lnv3m3e2sn6okj8g5b",
    "scope": [
        "channel_read",
        "chat:read",
        "user_blocks_edit",
        "user_blocks_read",
        "user_follows_edit",
        "user_read"
    ],
    "token_type": "bearer"
}`

But request gql api (https://gql.twitch.tv/gql) by this access_token get error "Unauthorized", I don't know what I did wrong.
`{
    "error": "Unauthorized",
    "status": 401,
    "message": "The \"Authorization\" token is invalid."
}`

Could you tell me? Thank you very much!!

**Comment by DevilXD** [comment]
Hello.

There is no "my own twitch client ID" here. This isn't a Twitch bot where you can use a different client ID. Changing the client ID to anything but whatever the miner currently comes with, won't work (Twitch blocks it), and is thus not supported.

The only way to use this miner, is to login with your own Twitch account.
