### ISSUE TITLE
GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}] 

### ISSUE THREAD

**Issue by oldschoola** [DevilXD/TwitchDropsMiner#464]
16:16:58: Traceback (most recent call last):
16:16:58:   File "main.py", line 158, in main
16:16:58:   File "twitch.py", line 768, in run
16:16:58:   File "twitch.py", line 824, in _run
16:16:58:   File "inventory.py", line 232, in claim
16:16:58:   File "inventory.py", line 138, in claim
16:16:58:   File "inventory.py", line 154, in _claim
16:16:58:   File "twitch.py", line 1570, in gql_request
16:16:58: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]
16:16:58:

**Comment by oldschoola** [comment]
i ran the dev build and it gave me this
16:24:53: Fatal error encountered:
16:24:53: 
16:24:53: Traceback (most recent call last):
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\main.py", line 158, in main
16:24:53:     await client.run()
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\twitch.py", line 768, in run
16:24:53:     await self._run()
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\twitch.py", line 824, in _run
16:24:53:     await drop.claim()
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\inventory.py", line 232, in claim
16:24:53:     result = await super().claim()
16:24:53:              ^^^^^^^^^^^^^^^^^^^^^
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\inventory.py", line 138, in claim
16:24:53:     result = await self._claim()
16:24:53:              ^^^^^^^^^^^^^^^^^^^
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\inventory.py", line 154, in _claim
16:24:53:     response = await self._twitch.gql_request(
16:24:53:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
16:24:53:   File "C:\Users\formatme\Desktop\TwitchDropsMiner-master\twitch.py", line 1570, in gql_request
16:24:53:     raise MinerException(f"GQL error: {response_json['errors']}")
16:24:53: exceptions.MinerException: GQL error: [{'message': 'service error', 'path': ['claimDropRewards']}]

**Comment by woctezuma** [comment]
Related:
- #417
- #337
- #444
- #347
- #301
