### ISSUE TITLE
Resetting farm progress

### ISSUE THREAD

**Issue by samSuSck** [DevilXD/TwitchDropsMiner#469]
Last week Twitch Miner dont want to work properly.
It make regular way to farm anything, but on each game it make progress of ~30% on first item and drop it to 0% without any claimed rewards.

![Снимок](https://github.com/DevilXD/TwitchDropsMiner/assets/170054040/2823efb7-41d5-4661-aec9-2f112db36678)

**Comment by Windows200000** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116078692

**Comment by Windows200000** [comment]
Check existing issues before making a new one.
