### ISSUE TITLE
Unable to claim drops, crashes

### ISSUE THREAD

**Issue by PockySweet** [DevilXD/TwitchDropsMiner#47]
The app properly watches the streamers and gets the channel points but seems unable to then claim the drops, it errors terminating the application and requests me to close the window.
![image](https://user-images.githubusercontent.com/79219650/190856760-07fa8036-2488-4915-81e2-8d6f885c29c4.png)
![image](https://user-images.githubusercontent.com/79219650/190856795-1e928b5e-6020-41bb-8c58-106a71f1d218.png)

**Comment by DevilXD** [comment]
Please see the pinned issue: #40
