### ISSUE TITLE
AppImage Errors & CPU Usage

### ISSUE THREAD

**Issue by iXerxes** [DevilXD/TwitchDropsMiner#470]
I'm unsure where to post this, so I'll just post it in both places. ([Windows200000's fork #23](https://github.com/Windows200000/TwitchDropsMiner-updated/issues/23))

I'm also aware that I'm not exactly using the miner as it was intended to be used, however, I thought I'd at least make note of this issue, just in case, as I was never getting these errors with previous versions.

I'm running the miner on Linux Ubuntu using @Windows200000's [fork](https://github.com/Windows200000/TwitchDropsMiner-updated), from the AppImage file, and I'm getting some errors I wasn't having before:
1. My console is being spammed with this error:
```
/tmp/.mount_miner.h1wTkZ/usr/lib/python3.10/asyncio/sslproto.py:320: ResourceWarning: unclosed transport <asyncio.sslproto._SSLProtocolTransport object at 0x7f230e8fe2c0>
```
2. The miner will disconnect from Twitch *far* more frequently than before, and give me the "Trying to reconnect" message. Not only this, but when the reconnect message appears, it seems to spam the console in a no-delay loop, meaning my CPU hits 100% load for an extended period of time.

**Comment by guihkx** [comment]
It doesn't make sense to report an issue on a fork here, especially since the code on that fork hasn't been properly reviewed by DevilXD yet.

**Comment by DevilXD** [comment]
As said, if you're using the fork, you have to report this on the fork's issues, not here.
