### ISSUE TITLE
No active campaigns to mine drops for. Waiting for an active campaign...

### ISSUE THREAD

**Issue by YashSwaraj** [DevilXD/TwitchDropsMiner#471]
Getting this message in the console. The app is not detecting any campaigns
![twitch miner](https://github.com/DevilXD/TwitchDropsMiner/assets/52151402/fa37e943-d236-4372-af5f-a3161698b40b)

**Comment by Windows200000** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116078692
