### ISSUE TITLE
Some time the viewing time will refresh even the times up can't get the reward

### ISSUE THREAD

**Issue by smoblk** [DevilXD/TwitchDropsMiner#473]
when i chose to see worldofwarships channel or some participating live channel
Mystery Drop and some even Drop the viewing time will refresh 
i was use v2rayN for using app

**Comment by smoblk** [comment]
I see the timer was going but i check the Inventory in website there no any (In Progress) was going that was empty.
only show the (Claimed) one .
its that a bug or just going ?

**Comment by Sodaly1318** [comment]
duplicate #462 
简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)

**Comment by smoblk** [comment]
> duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)

那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD

**Comment by Sodaly1318** [comment]
> > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> 
> 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD

最新的Release就能用的

**Comment by Sodaly1318** [comment]
> > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > 
> > > 
> > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > 
> > 
> > 最新的Release就能用的
> 
> 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝

我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是

**Comment by smoblk** [comment]
> > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > 
> > > > 
> > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > 
> > > 
> > > 最新的Release就能用的
> > 
> > 
> > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> 
> 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是

好的 我今晚试试 如果还是同样问题或者能使用我会再次回复你

**Comment by smoblk** [comment]
> > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > 
> > > > 
> > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > 
> > > 
> > > 最新的Release就能用的
> > 
> > 
> > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> 
> 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是

虽然关闭了 但是依旧没办法累计观看时间 观看时间100% 也无法领取奖励

**Comment by Sodaly1318** [comment]
> > > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > > 
> > > > > 
> > > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > > 
> > > > 
> > > > 最新的Release就能用的
> > > 
> > > 
> > > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> > 
> > 
> > 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是
> 
> 虽然关闭了 但是依旧没办法累计观看时间 观看时间100% 也无法领取奖励

fork里的那个吗？你还是用不了？你的意思是软件里进度正常走但是twitch里没动？

**Comment by smoblk** [comment]
> > > > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > > > 
> > > > > > 
> > > > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > > > 
> > > > > 
> > > > > 最新的Release就能用的
> > > > 
> > > > 
> > > > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> > > 
> > > 
> > > 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是
> > 
> > 
> > 虽然关闭了 但是依旧没办法累计观看时间 观看时间100% 也无法领取奖励
> 
> fork里的那个吗？你还是用不了？你的意思是软件里进度正常走但是twitch里没动？

软件进度100% 退出再进 又变回之前的进度 网页端查看也是之前为了保险挂的网页进度

**Comment by Sodaly1318** [comment]
> > > > > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > > > > 
> > > > > > > 
> > > > > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > > > > 
> > > > > > 
> > > > > > 最新的Release就能用的
> > > > > 
> > > > > 
> > > > > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> > > > 
> > > > 
> > > > 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是
> > > 
> > > 
> > > 虽然关闭了 但是依旧没办法累计观看时间 观看时间100% 也无法领取奖励
> > 
> > 
> > fork里的那个吗？你还是用不了？你的意思是软件里进度正常走但是twitch里没动？
> 
> 软件进度100% 退出再进 又变回之前的进度 网页端查看也是之前为了保险挂的网页进度

你是不是在软件挂的时候同时开着战舰世界的直播间，同时挂好像不涨进度的。
如果不是那我也不清楚了，我这里挂的正常，可以去那个fork里再提issue，问问那个外国大佬

**Comment by smoblk** [comment]
> > > > > > > > > duplicate #462 简单来说现在软件有bug但是开发者现在很忙，没时间修。有位大佬暂时修好了，可以先用他的[fork](https://github.com/Windows200000/TwitchDropsMiner-updated)
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 那这个FORK的使用流程怎么整？我单纯只会在Release整最新的 XD
> > > > > > > 
> > > > > > > 
> > > > > > > 最新的Release就能用的
> > > > > > 
> > > > > > 
> > > > > > 最新的在战舰世界的掉宝那边没法用 所以才发了这个issue 今晚的我是自己手动的挂的 一个是官方频道的神秘掉宝一个是指定频道的任务掉宝
> > > > > 
> > > > > 
> > > > > 我说的是fork里的release，你点一下我回复的第一条里的蓝色fork，那个就是
> > > > 
> > > > 
> > > > 虽然关闭了 但是依旧没办法累计观看时间 观看时间100% 也无法领取奖励
> > > 
> > > 
> > > fork里的那个吗？你还是用不了？你的意思是软件里进度正常走但是twitch里没动？
> > 
> > 
> > 软件进度100% 退出再进 又变回之前的进度 网页端查看也是之前为了保险挂的网页进度
> 
> 你是不是在软件挂的时候同时开着战舰世界的直播间，同时挂好像不涨进度的。 如果不是那我也不清楚了，我这里挂的正常，可以去那个fork里再提issue，问问那个外国大佬

没有同时开(甚至去洗漱很久才回来) 不过算了 最近就这一个掉宝 不去提问了
