### ISSUE TITLE
Miner does not update after linking Twitch account to game drop campaign

### ISSUE THREAD

**Issue by Travis2445** [DevilXD/TwitchDropsMiner#480]
I am encountering an issue with the TwitchDropsMiner where the miner does not update and show that a game is linked to my Twitch account, even after successfully linking my account to a game drop campaign. As a result, the miner does not start mining.

Steps to Reproduce:

Link Twitch account to a game drop campaign.
Check the miner to see if it updates and shows the linked campaign.
Notice that the miner does not update.

What I've Tried:

Logged out and back into my Twitch account multiple times.
Restarted the TwitchDropsMiner app several times.
Waited a couple of hours to see if it would eventually update.
Despite these efforts, the miner still does not show that it is linked to the campaign and does not start mining.

Expected Behavior:
The miner should update and show that it is linked to the Twitch account and the game drop campaign, allowing it to start mining.

Screenshots:
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/90297320/aa3f391a-84d9-4efe-aefa-7cd60ac54588)

System Information:

Operating System: Windows 11 Pro
App Version: v16.dev27

**Comment by DevilXD** [comment]
On the https://www.twitch.tv/drops/campaigns page, find the affected campaign and ensure that it's "Connection" section says "Linked". If it doesn't, use the link button youłl find there to perform the linking process again. Alternatively, perform a clean reconnect: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

Even with that solved, you'll still run into #462, just so you know. Let me know if your linking issue is solved.

**Comment by Travis2445** [comment]
It is working now. Before, I had checked on the https://www.twitch.tv/drops/campaigns page and it showed it connected. Only thing I did different this time is run/build the Dev build from the source code. For whatever reason it showed only rust in the priority list but it had it linked. When I jumped back to the other build it was fixed. No Clue.

**Comment by DevilXD** [comment]
Glad you could get it resolved :)
