### ISSUE TITLE
 The Miner is fake mining

### ISSUE THREAD

**Issue by noahnao** [DevilXD/TwitchDropsMiner#485]
The program thinks it's mining, but really nothing is happening.
This happens both on custom-builds made directly from the source code and with the beta version.

https://github.com/DevilXD/TwitchDropsMiner/assets/81416193/d81e22b2-acf1-41d8-9906-570d693edbc6

**Comment by flamedance58** [comment]
I'm pretty sure this is a known issue atm as in another issue post (https://github.com/DevilXD/TwitchDropsMiner/issues/462) it's stated the program is kinda broken atm due to some changes on Twitch's side.

iirc the dev has stated that they don't have easy access to their PC atm so work on the prog is TBD.

**Comment by noahnao** [comment]
> I'm pretty sure this is a known issue atm as in another issue post (#462) it's stated the program is kinda broken atm due to some changes on Twitch's side.
> 
> iirc the dev has stated that they don't have easy access to their PC atm so work on the prog is TBD. [#462 (comment)](https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116078692)

I hope they can get access to their PC soon then.

**Comment by Kimarnic** [comment]
Use @Windows200000 's updated version that works
https://github.com/Windows200000/TwitchDropsMiner-updated

**Comment by flamedance58** [comment]
> > I'm pretty sure this is a known issue atm as in another issue post (#462) it's stated the program is kinda broken atm due to some changes on Twitch's side.
> > iirc the dev has stated that they don't have easy access to their PC atm so work on the prog is TBD. [#462 (comment)](https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116078692)
> 
> I hope they can get access to their PC soon then.

https://github.com/DevilXD/TwitchDropsMiner/issues/462#issuecomment-2116004659

Apparently it's mostly due to crazy heavy work contract or something. So here's hoping the best for their health first and foremost and then finding time to work on this :)
