### ISSUE TITLE
active twitch account failure

### ISSUE THREAD

**Issue by RecanLive** [DevilXD/TwitchDropsMiner#487]
open the exe，and click loggin turn to twitch active page when i copy active codes then this page tell that someting error

how to solve？pls

**Comment by DevilXD** [comment]
Hello o/

There is no immediate solution at this time. I'll study login issues once #462 can be resolved, or I'll run into said login issue myself. For now, since #462 is still in effect, I'd recommend not trying to use the miner for the time being.

**Comment by RecanLive** [comment]
wish you solve it soon  ..good luck!

**Comment by DevilXD** [comment]
Please check the latest master build to see if that resolved your issue.

**Comment by DevilXD** [comment]
Is this issue still happening to you?

**Comment by DevilXD** [comment]
I've tested the login method a few times over the past week or two, and found no issues. I'm closing this due to lack of further information provided.
