### ISSUE TITLE
Miner not actually mining

### ISSUE THREAD

**Issue by OdegardXD** [DevilXD/TwitchDropsMiner#494]
The miner reports that its actually watching but when i go to twitch it says otherwise
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/132513473/7cfc47a4-178a-4b09-bffd-f572ea38dbe6)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/132513473/0cd4a59c-e493-4a7f-be65-9ee18a750f09)
This has ben happening for a while now.

**Comment by DevilXD** [comment]
This is a duplicate of #462.
