### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by dishophoiba** [DevilXD/TwitchDropsMiner#495]
![image_2024-06-07_233218220](https://github.com/DevilXD/TwitchDropsMiner/assets/18474401/704e6639-680f-4036-9a32-1e74e6bf805a)

**Comment by UniqueSaltedFish** [comment]
Hey guys。I have the same problem. Have you solved it？

**Comment by DealsBeam** [comment]
https://github.com/DevilXD/TwitchDropsMiner/issues/493

**Comment by DevilXD** [comment]
Duplicate of #493.
