### ISSUE TITLE
Twitch is down, retrying in X seconds...

### ISSUE THREAD

**Issue by axi92** [DevilXD/TwitchDropsMiner#497]
I just started and get

```
09:40:31: Twitch is down, retrying in 1 seconds...
09:40:32: Twitch is down, retrying in 2 seconds...
09:40:35: Twitch is down, retrying in 4 seconds...
```
but I am watching twitch at the same time in my browser. 
How is that possible that twitch is down?

What domain is not answering to causes that error?

Ref: #62 

Edit: I tried this fork https://github.com/Windows200000/TwitchDropsMiner-updated and it works there

**Comment by herhor67** [comment]
Same error, probably something changed on the twitch side again...

**Comment by herhor67** [comment]
Now it's
```
09:07:38: ERROR: Exception in task
09:07:38: Traceback (most recent call last):
09:07:38:   File "utils.py", line 139, in wrapper
09:07:38:   File "twitch.py", line 1042, in _watch_loop
09:07:38:   File "channel.py", line 379, in send_watch
09:07:38:   File "channel.py", line 237, in get_spade_url
09:07:38: exceptions.MinerException: Error while spade_url extraction: step #1
```

**Comment by DevilXD** [comment]
> I am watching twitch at the same time in my browser.

The miner won't work correctly if you do that.

The rest is being taken care of in #462. There's no point in opening any new issues about the miner "not working", if #462 is the main thing preventing it from working at all.
