### ISSUE TITLE
Error when launching the compiled .exe

### ISSUE THREAD

**Issue by nwvh** [DevilXD/TwitchDropsMiner#51]
Hey, so I tried to build the .exe with pyinstaller. It compiled successfully but when I run it, it gives me this error:

```
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_win32api.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "pywintypes.py", line 128, in <module>
  File "pywintypes.py", line 44, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path ['C:\\Users\\wooxh\\AppData\\Local\\Temp\\_MEI16282\\base_library.zip', 'C:\\Users\\wooxh\\AppData\\Local\\Temp\\_MEI16282\\lib-dynload', 'C:\\Users\\wooxh\\AppData\\Local\\Temp\\_MEI16282']

```

I searched up the error and it looks like pyinstaller error. Can someone confirm it? Thanks

**Comment by nwvh** [comment]
> Hello o/
> 
> This looks like a missing dependency. Have you followed the Advanced Usage section of the README?:
> ![obraz](https://user-images.githubusercontent.com/4180725/191097797-83ccd196-181c-4335-a26b-8a4d743f4cbe.png)
> 

yes I did

**Comment by DevilXD** [comment]
Assuming you've done everything from it correctly then, there's one thing you can try:
![obraz](https://user-images.githubusercontent.com/4180725/191102355-3465ebdf-6885-492d-8f43-1e87b97d44d6.png)

Command:
```
\env\Scripts\pywin32_postinstall.py -install
```
Note you have to run this from an activated venv too.

**Comment by DevilXD** [comment]
I've just pushed out https://github.com/DevilXD/TwitchDropsMiner/commit/44fc3122e0d8faa902587b62371578ae639f30c9, so you can try running the new setup script. It gives you an option to either install PyInstaller or not for you automatically.

**Comment by Huiaei** [comment]
I have the same problem.
```powershell
(env) PS D:\User\TwitchDropsMiner> pip list
Package                   Version
------------------------- ---------
aiohttp                   3.8.3
aiosignal                 1.2.0
altgraph                  0.17.2
async-timeout             4.0.2
attrs                     22.1.0
charset-normalizer        2.1.1
frozenlist                1.3.1
future                    0.18.2
idna                      3.4
multidict                 6.0.2
pefile                    2022.5.30
Pillow                    9.2.0
pip                       21.1.1
pyinstaller               5.4.1
pyinstaller-hooks-contrib 2022.10
pystray                   0.19.4
pywin32                   304
pywin32-ctypes            0.2.0
setuptools                56.0.0
six                       1.16.0
wheel                     0.37.1
yarl                      1.8.1
WARNING: You are using pip version 21.1.1; however, version 22.2.2 is available.
You should consider upgrading via the 'd:\user\twitchdropsminer\env\scripts\python.exe -m pip install --upgrade pip' command.
```

But I tried to build using github actions, Artifacts can be opened, but there are problems using it.
I opened the program, logged into my account and set up the program, restarted the program and got an error.
```
Fatal error encountered:

Traceback (most recent call last):
  File "main.py", line 169, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 418, in run
  File "twitch.py", line 438, in _run
  File "twitch.py", line 981, in get_auth
  File "twitch.py", line 198, in validate
  File "twitch.py", line 279, in _validate
exceptions.MinerException: Twitch considers this miner as a "Bad Bot". Try deleting the cookie file and try again.
```
[my actions artifacts link](https://github.com/Huiaei/TwitchDropsMiner/actions/runs/3104966380)

**Comment by DevilXD** [comment]
@Huiaei If you've managed to launch and log into the program, then you are not having the same issue then. The traceback you've got is related to #40 instead, not this issue.

As far as Github Actions, or as I saw another person do in a fork, any kind of CI or even Heroku deployment (which this app was never designed for): these are not really recommended from my side. I never designed this project with CI in mind - if you can make it work, so be it. If not, I have no real plans on "enabling" CI specifically, as everything required to build the application is already provided as-is in the repository.

By the way, [your artifacts build](https://github.com/Huiaei/TwitchDropsMiner/actions/runs/3104966380/jobs/5030037467) says at the end of the build phase:

> 30879 INFO: Building EXE from EXE-00.toc completed successfully.

..., which is exactly what I get every time I build the application, so it should be working already, minus the #40 issue that is currently crippling this project of course.

**Comment by Huiaei** [comment]
> @Huiaei If you've managed to launch and log into the program, then you are not having the same issue then. The traceback you've got is related to #40 instead, not this issue.
> 
> As far as Github Actions, or as I saw another person do in a fork, any kind of CI or even Heroku deployment (which this app was never designed for): these are not really recommended from my side. I never designed this project with CI in mind - if you can make it work, so be it. If not, I have no real plans on "enabling" CI specifically, as everything required to build the application is already provided as-is in the repository.
> 
> By the way, [your artifacts build](https://github.com/Huiaei/TwitchDropsMiner/actions/runs/3104966380/jobs/5030037467) says at the end of the build phase:
> 
> > 30879 INFO: Building EXE from EXE-00.toc completed successfully.
> 
> ..., which is exactly what I get every time I build the application, so it should be working already, minus the #40 issue that is currently crippling this project of course.

Thank you for your reply. I also found issue #40 when I finished replying to this thread. i will also turn my attention to issue #40 and look forward to the subsequent fix.

**Comment by DevilXD** [comment]
These issues should be fixed by the `v13` release: https://github.com/DevilXD/TwitchDropsMiner/releases
