### ISSUE TITLE
Argument Parser Error upon boot

### ISSUE THREAD

**Issue by Kitesszh** [DevilXD/TwitchDropsMiner#510]
![2024-07-04_141840](https://github.com/DevilXD/TwitchDropsMiner/assets/70734132/928bb514-f882-4c23-8dfc-114533d02597)
The last two versions dc48860 35c46c2

**Comment by DevilXD** [comment]
Hello. Thank you for your report. This issue has been accidentally introduced 3 days ago via this commit: https://github.com/DevilXD/TwitchDropsMiner/commit/14a9154366d2651dc2cf75903744553a64319eb3

https://github.com/DevilXD/TwitchDropsMiner/commit/18a03353efae21e3569cec43bac4e7bf4e899076 from the latest development build implements a fix. You'll need to uncheck and check again the "Autostart" option for the fix to apply properly. This issue should then no longer occur on subsequent restarts.

I'll keep this issue open for a week or two, in case someone else runs into it as well.
