### ISSUE TITLE
GQL error: [{'message': 'server error', 'path': ['user', 'broadcastSettings']}]

### ISSUE THREAD

**Issue by JacobJohn** [DevilXD/TwitchDropsMiner#514]
16:38:42: Fatal error encountered:
16:38:42: 
16:38:42: Traceback (most recent call last):
16:38:42:   File "channel.py", line 249, in get_stream
16:38:42:   File "twitch.py", line 1575, in gql_request
16:38:42: exceptions.MinerException: GQL error: [{'message': 'server error', 'path': ['user', 'broadcastSettings']}]
16:38:42: 
16:38:42: The above exception was the direct cause of the following exception:
16:38:42: 
16:38:42: Traceback (most recent call last):
16:38:42:   File "main.py", line 160, in main
16:38:42:   File "twitch.py", line 772, in run
16:38:42:   File "twitch.py", line 915, in _run
16:38:42:   File "channel.py", line 286, in update_stream
16:38:42:   File "channel.py", line 253, in get_stream
16:38:42: exceptions.MinerException: Channel: ironbandit_
16:38:42: 
16:38:42: Exiting...
16:38:42: 
16:38:42: Application Terminated.
16:38:42: Close the window to exit the application.

**Comment by JacobJohn** [comment]
I dont know what the issue was here, but I eventually walked away, and now it is fixed after another restart.

**Comment by DevilXD** [comment]
Hello,

This is more or less, the same as "service error" issue, handling of which is tracked by #417.

**Comment by matarife123** [comment]
this error today: 
19:31:43: Fatal error encountered:
19:31:43: 
19:31:43: Traceback (most recent call last):
19:31:43:   File "main.py", line 153, in main
19:31:43:   File "twitch.py", line 570, in run
19:31:43:   File "twitch.py", line 620, in _run
19:31:43:   File "twitch.py", line 1428, in fetch_inventory
19:31:43:   File "asyncio\tasks.py", line 571, in _wait_for_one
19:31:43:   File "twitch.py", line 1383, in fetch_campaigns
19:31:43:   File "twitch.py", line 1350, in gql_request
19:31:43: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
19:31:43: 
19:31:43: Saliendo...
19:31:43: 
19:31:43: La aplicación se ha detenido.
19:31:43: Por favor, cierre la aplicación.

**Comment by DevilXD** [comment]
@matarife123 That's an entirely different error from the original reported in this issue. Please make sure you're replying with information that's actually relevant to the issue.

PS: It's already fixed: https://github.com/DevilXD/TwitchDropsMiner/commit/97686353d415471668ae95440fa2fd896394c062

**Comment by matarife123** [comment]
> @matarife123Se trata de un error completamente diferente del original que se informó en este problema. Asegúrese de responder con información que sea realmente relevante para el problema.
> 
> PD: Ya está arreglado: [9768635](https://github.com/DevilXD/TwitchDropsMiner/commit/97686353d415471668ae95440fa2fd896394c062)

Thanks, try not to make double posts

**Comment by DevilXD** [comment]
I'm marking this as duplicate, since #417 already tracks this. It'll get taken care of eventually.
