### ISSUE TITLE
Virus ?

### ISSUE THREAD

**Issue by Mates31cz** [DevilXD/TwitchDropsMiner#517]
antivirus say i contain many viruses
Trojan:Win32/Wacatac.H!ml
Program:Win32/Contebrew.A!ml

What the hack ?

**Comment by DevilXD** [comment]
This is a duplicate of #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209 and #13.

Please always search existing issues before creating new ones.
