### ISSUE TITLE
PersistedQueryNotFound on a CampaignDetails GQL call

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#519]
![Sin título](https://github.com/user-attachments/assets/bc9494b0-0b4c-410c-a283-e5a8d5206f44)

**Comment by DevilXD** [comment]
Hello,

I understand that my attempt at hot-fixing this has initially failed. I've read into the traceback more closely, and it appears to be coming from the `CampaignDetails` operation, not the `Campaigns` one.

https://github.com/DevilXD/TwitchDropsMiner/commit/0f3a7841b7a99a53ddb9186e2ffc8ef2c18e332d should resolve this.

**Comment by matarife123** [comment]
thanks again :D

**Comment by fappyhrc** [comment]
problem solved!
thanks : )
