### ISSUE TITLE
Drop inventory bug?

### ISSUE THREAD

**Issue by automatic-gaming** [DevilXD/TwitchDropsMiner#522]
All this is speculation based on the best information I have. Black Desert is a game with a daily drop, that pretty frequently runs multiple campaigns at the same time.

Today I was checking the miner and noticed that it was stuck on 100% Progress for the Black Desert [SA] Community Week Day 6 drop. When I restarted the miner, it started the same drop over again from zero. The miner worked the day before, and I updated to the newest revision last night. I do not see any progress being made in the drop inventory towards either campaign, nor any drops waiting to be redeemed.

I did notice my drop inventory has a drop from the same game that appears to have expired from July 22nd. Perhaps it's an inventory bug?

I've attached screenshots of my drop inventory, the campaign, as well as redemption history.

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/user-attachments/assets/24d861d3-44f6-41d5-9081-cc0fc1091dd7)

![image](https://github.com/user-attachments/assets/7e486e55-0c77-47bb-a8fb-f0a99b4fce42)

![image](https://github.com/user-attachments/assets/26cfb11c-0793-4865-a488-8ad70426c2ec)

</p>
</details>

**Comment by automatic-gaming** [comment]
Update: It took a few hours but it did eventually complete the initial drop, then the second one. Could have just been an issue on Twitch's end?

**Comment by DevilXD** [comment]
Hello. It's really hard to say anything here, what could be the cause of what you've experienced. But generally, if the progress gets stuck at 100%, then it means the Twitch wasn't registering the "watching" properly. As the watching procedure continues even after the progress hits 100%, it will eventually reach the actual 100% on the Twitch server, and claim the drop like you've had it happen.

The usual cause of the miner not having the watching progress being counted properly, is either you using Twitch in the browser (watching another stream), or mining on multiple accounts at once. Twitch has some protections where it'll disregard a portion of the mining attempts if another stream is watched from the same IP address. This varies, but the general result is that the progress displayed in the miner will become inaccurate.

You can always check the real progress by visiting [the inventory page](https://www.twitch.tv/drops/inventory), or reloading/restarting the miner.
