### ISSUE TITLE
Online twitch accounts shows up as OFFLINE

### ISSUE THREAD

**Issue by bossman90** [DevilXD/TwitchDropsMiner#541]
![image](https://github.com/user-attachments/assets/1067f59d-0fb3-4d4a-ab9e-53ef44e4a6d1)
![image](https://github.com/user-attachments/assets/2e956839-7c15-4f19-92b7-0f163e551ebb)

**Comment by Minty-stack** [comment]
I'm seeing something similar with Warframe right now - even after a manual reload the channel still shows as OFFLINE, but the websocket drops are still updating - perhaps a display bug?

![Warframe](https://github.com/user-attachments/assets/99917d0b-195a-4148-b020-e6f2dd244609)

**Comment by DevilXD** [comment]
Hello,

This is normal, and has already been explained in #537. The channel status fetch is now done passively via websocket viewers count update, so it may take up to 2-3 minutes for each channel to come ONLINE after a reload. Everything else works as before. The logic that updates channel status on reload is disabled, until I can find some time to rewrite it properly.
