### ISSUE TITLE
Possible "Twitch is down, retrying" issue and questions

### ISSUE THREAD

**Issue by Windows200000** [DevilXD/TwitchDropsMiner#542]
Hi DevilXD,

I encountered this issue yesterday: https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172, do you have something similar?

Also does this TDM now work with the new API changes?

Do you have discord or something similar where we could chat about implementing stuff from my fork or issues we both encounter? Alternatively a permanent issue might make sense, so other people can see it as well.

**Comment by DevilXD** [comment]
Hello,

I have no such issues you're experiencing. The miner seems to be working, at least for me. No progress is being lost.

If you want to talk on discord, my username is `@devilxd` (duh). You may need to send a friend request first, otherwise DMs won't work.
