### ISSUE TITLE
No active campaigns to mine drops for. Waiting for an active campaign...

### ISSUE THREAD

**Issue by penisgesicht231** [DevilXD/TwitchDropsMiner#543]
No matter what I try it doesnt seem to start. I see the message "No active campaigns to mine drops for. Waiting for an active campaign..." even when I have no priority set...

**Comment by Windows200000** [comment]
Do you have games linked? Can you add a screenshot of the inventory with all options checked?

**Comment by DevilXD** [comment]
@penisgesicht231 Have you added any games to the priority list first? It won't do anything until you do.

**Comment by Windows200000** [comment]
TBF I do have: `No available channels to watch. Waiting for an ONLINE channel...`
![image](https://github.com/user-attachments/assets/fca34e70-c810-47d8-a66a-fdf9efb39852)

I set it to prio only and World of Tanks. My fork is farming on their official channel.
![image](https://github.com/user-attachments/assets/74a90d8b-d1b2-474d-b706-720315ed1b45)

**Comment by penisgesicht231** [comment]
> Do you have games linked? Can you add a screenshot of the inventory with all options checked?

I didnt link any accounts yet is that required to start farming ? Would you need to link every single game if I wanted to farm them all ?

**Comment by penisgesicht231** [comment]
> @penisgesicht231 Have you added any games to the priority list first? It won't do anything until you do.

I tried it with priority games too yes I currently have no game account linked is that required to start watchgin ?=

**Comment by Windows200000** [comment]
> > Do you have games linked? Can you add a screenshot of the inventory with all options checked?
> 
> I didnt link any accounts yet is that required to start farming ? Would you need to link every single game if I wanted to farm them all ?

Yes. You need that anyway to get the rewards.

From README.md:

>TDM is not intended for/as:
>
>- Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
>- Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
>- Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
>- 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
>- Being hosted on a remote server as a 24/7 miner.
>- Being used with more than one managed account.
>- Mining campaigns the managed account isn't linked to.

**Comment by penisgesicht231** [comment]
> > > Do you have games linked? Can you add a screenshot of the inventory with all options checked?
> > 
> > 
> > I didnt link any accounts yet is that required to start farming ? Would you need to link every single game if I wanted to farm them all ?
> 
> Yes. You need that anyway to get the rewards.
> 
> From README.md:
> 
> > TDM is not intended for/as:
> > 
> > * Mining channel points - again, it's about the drops: only. The current points you're getting are a byproduct of getting the drops, not the main goal of it.
> > * Mining anything else besides Twitch drops - no, I won't be adding support for a random 3rd party site that also happens to rely on watching Twitch streams.
> > * Unattended operation: worst case scenario, it'll stop working and you'll hopefully notice that at some point. Hopefully.
> > * 100% uptime application, due to the underlying nature of it, expect fatal errors to happen every so often.
> > * Being hosted on a remote server as a 24/7 miner.
> > * Being used with more than one managed account.
> > * Mining campaigns the managed account isn't linked to.

hmm ok will try later with added accounts I usually claim on twitch and add account later always worked guess not here

**Comment by Asatas** [comment]
It seems this has something to do with Exclude behavior. Even if my Exclude list is empty, in the Inventory all games only show up after I check "Excluded".

**Comment by DevilXD** [comment]
I feel like this is the same "issue" as #537. Due to semi-recent changes, all ACL channels start as OFFLINE now, which may cause the miner to switch to IDLE mode right after a reload, displaying that message. The channels will gradually come ONLINE over the next 2-3 minutes though, and the mining will continue as normal. This can also be seen on this picture: https://github.com/DevilXD/TwitchDropsMiner/issues/543#issuecomment-2295286209  Most channels have the `OFFLINE ⏳` status, indicating they're about to switch to `ONLINE` within the next 2 minutes or so.

@penisgesicht231 You have to link your Twitch account before you attempt mining drops, as unlinked accounts have a 24 hours period to link after claiming a drops, so you'd have to do it soon anyway. Linking is a single-time process, and persists between campaigns for a given game, so that shouldn't be an issue.

**Comment by TimFinitor** [comment]
![image](https://github.com/user-attachments/assets/9543d646-59fa-405b-9013-446ea8d07ad9)
Hey, I'm still getting the error ‘07:36:35: No active campaigns to mine drops for. Waiting for an active campaign...’ Although I have set a game in the settings:
![image](https://github.com/user-attachments/assets/b7082200-4425-44e6-8519-48a34780b039)
In addition, the inventory also works I do not understand what it is I hope someone has a solution ready :):
![image](https://github.com/user-attachments/assets/c60d4406-f76b-4e05-9722-cf3ae48a38c0)

**Comment by DevilXD** [comment]
The new bulk channel status refresh logic has been implemented, so this shouldn't be happening anymore. Otherwise, please open another issue.
