### ISSUE TITLE
Fatal errors on claiming drops.

### ISSUE THREAD

**Issue by FabulousTiger** [DevilXD/TwitchDropsMiner#546]
I am getting a few fatal errors and from the closed issues it seems it can't be fixed. So I am wondering if it's easy to disable the claiming part and I can use the auto drops claim extension instead for this. As I was using both to have a failsafe in claiming and watching. As I would select a stream and leave it on but I would also use the miner to make sure even if the stream I started myself went offline it would still mine drops. But then the fatal errors have been an issue where as it's fatal it would stop the program. So I am wondering if I run from source or build myself if I can disable the claiming part without the program getting confused.

**Comment by DevilXD** [comment]
Hello,

This application will automatically mine and claim drops for you. If it can't do either and both of these things, then it's considered broken and to-be looked at. Disabling claiming of drops isn't a feature, because it goes against what's the miner supposed to be doing - getting you the actual drops. Without claiming, they expire within 24 hours, and supporting 3rd party usages of "claiming via a different way" isn't on my radar either.

What exactly is the error you're experiencing? I'd need the full traceback to diagnose your issue.

**Comment by FabulousTiger** [comment]
I forgot to make copy of the output as i have since restarted it. But will update if it happens again next claim is in under 2 hours but it was something like "[{'message': 'service error', 'path': ['claimDropRewards']}]" but don't remember if it was service error but the claimDropRewards i do remember.

**Comment by FabulousTiger** [comment]
```
17:39:20: No available channels to watch. Waiting for an ONLINE channel...
17:41:22: Pestily goes ONLINE, switching...
17:41:22: Watching: Pestily
18:06:33: No available channels to watch. Waiting for an ONLINE channel...
18:08:54: NoGenerals goes ONLINE, switching...
18:08:54: Watching: NoGenerals
19:06:37: No available channels to watch. Waiting for an ONLINE channel...
19:08:54: Underdog82 goes ONLINE, switching...
19:08:54: Watching: Underdog82
19:36:22: No available channels to watch. Waiting for an ONLINE channel...
19:38:23: SmittyStone goes ONLINE, switching...
19:38:23: Watching: SmittyStone
20:36:26: No available channels to watch. Waiting for an ONLINE channel...
20:38:52: kiuza goes ONLINE, switching...
20:38:52: Watching: kiuza
21:06:58: No available channels to watch. Waiting for an ONLINE channel...
21:09:24: Liazal goes ONLINE, switching...
21:09:24: Watching: Liazal
22:07:02: No available channels to watch. Waiting for an ONLINE channel...
22:09:25: FereWoT goes ONLINE, switching...
22:09:25: Watching: FereWoT
22:35:42: FereWoT goes OFFLINE, switching...
22:35:42: Watching: Schmelko
22:36:31: No available channels to watch. Waiting for an ONLINE channel...
22:38:55: Basaboom goes ONLINE, switching...
22:38:55: Watching: Basaboom
23:36:35: No available channels to watch. Waiting for an ONLINE channel...
23:38:55: BeardedTortle goes ONLINE, switching...
23:38:55: Watching: BeardedTortle
00:06:44: Fatal error encountered:
00:06:44: 
00:06:44: Traceback (most recent call last):
00:06:44:   File "main.py", line 153, in main
00:06:44:   File "twitch.py", line 572, in run
00:06:44:   File "twitch.py", line 633, in _run
00:06:44:   File "inventory.py", line 245, in claim
00:06:44:   File "inventory.py", line 146, in claim
00:06:44:   File "inventory.py", line 162, in _claim
00:06:44:   File "twitch.py", line 1359, in gql_request
00:06:44: exceptions.GQLException: [{'message': 'service error', 'path': ['claimDropRewards']}]
00:06:44: 
00:06:44: Exiting...
00:06:44: 
00:06:44: Application Terminated.
00:06:44: Close the window to exit the application.
```
Ok it happend again. That is the output i got. It was service error. And i included some hours of on and off watching behavior.

**Comment by DevilXD** [comment]
Another service error, huh?

The bad news is that service errors may crop up on any GQL endpoint, not only the drop claiming one. The good news is that those will pass on it's own, and it'll stop doing that eventually.

And, well, #417 already tracks this, so unfortunately this is considered a duplicate issue. I'll try putting more priority into resolving it.

**Comment by FabulousTiger** [comment]
Ok i wish you good luck in finding a solution. But I have a question in terms of the watching not watching behavior every few hours. As I know some of not all those streamers were streaming the whole drop time. Any reason it would stop watching for few min and then start again.

**Comment by DevilXD** [comment]
You should be able to read on more about this in #537.
