### ISSUE TITLE
TDM can't switch to Star Wars Outlaws

### ISSUE THREAD

**Issue by xr1rx** [DevilXD/TwitchDropsMiner#549]
I have Star Wars Outlaws at the top of the priority list and there are a dozen streamers in the Outlaws category, but TDM simply won't switch to any of them even if I try to switch manually.

![5jj6w4](https://github.com/user-attachments/assets/23eda1e2-299b-410d-b809-a78f89a2e32b)

I have tried different setups, different accounts and brand new installs but the issue remains.

Is this universal (something on Twitch's end perhaps) or is this an isolated issue?

Thank you.

**Comment by villario** [comment]
Did you try to read drops description?
> Purchase 1 new recurring or gift subscription and claim the rewards The Memento Trinket and The Law Trinket
You see channels which play this game because you have game in list, but TDM is not able to do anything with it (if drops require watching streams, it will progress)

**Comment by xr1rx** [comment]
> Did you try to read drops description?
> 
> > Purchase 1 new recurring or gift subscription and claim the rewards The Memento Trinket and The Law Trinket
> 
> You see channels which play this game because you have game in list, but TDM is not able to do anything with it (if drops require watching streams, it will progress)

Ohh, that makes sense. I had no idea that drops with such requirements are listed among the normal drops now. They were listed at the top before to differentiate from the others previously.

But the reason I didn't look into it further is because there are other games I can't progress towards, such as XDefiant, Naraka and Vampire: The Masquerade – Bloodhunt. There are live streams with drops enabled but TDM just isn't switching to any of them and I'm out of ideas.

Thanks for letting me know anyhow.

**Comment by DevilXD** [comment]
> But the reason I didn't look into it further is because there are other games I can't progress towards, such as XDefiant, Naraka and Vampire: The Masquerade – Bloodhunt. There are live streams with drops enabled but TDM just isn't switching to any of them and I'm out of ideas.

On your picture, the miner is actually watching a channel playing "XDefiant". Are you sure what you're saying is true? The miner currently has no significant issues that'd prevent it from mining anything.

**Comment by xr1rx** [comment]
> > But the reason I didn't look into it further is because there are other games I can't progress towards, such as XDefiant, Naraka and Vampire: The Masquerade – Bloodhunt. There are live streams with drops enabled but TDM just isn't switching to any of them and I'm out of ideas.
> 
> On your picture, the miner is actually watching a channel playing "XDefiant". Are you sure what you're saying is true? The miner currently has no significant issues that'd prevent it from mining anything.

Yeah sorry, I should've been clear. It can work for some time but for some reason it stops working and the app tells me there are no active campaigns, even when there are.

Seems to work smoothly with Windows200000's fork however, and all campaigns are now progressing as expected.

**Comment by DevilXD** [comment]
> the app tells me there are no active campaigns, even when there are.

Are you sure it's not just #537 happening to you? If so, that's perfectly normal, the miner will still work.

**Comment by DevilXD** [comment]
@xr1rx Is the issue still happening to you? Have you seen my previous comment?

**Comment by xr1rx** [comment]
> @xr1rx Is the issue still happening to you? Have you seen my previous comment?

Sorry for the late reply, I did some testing and yes the same issue is still present. Today TDM can't load any Lost Ark stream even if there are streams with drops enabled. I can't figure out why because the Windows20000 fork works fine so far with the same settings and all. My priority list is very large (~120) but it doesn't seem to matter if I delete my settings and start from scratch.

**Comment by JourneyOver** [comment]
I wonder if you are running into the same issue I am/was in #554

**Comment by DevilXD** [comment]
@xr1rx Please run the miner with the `--dump` option, then post the `dump.dat` file that will be created in the miner's folder. I need to take a closer look.

**Comment by xr1rx** [comment]
> @xr1rx Please run the miner with the `--dump` option, then post the `dump.dat` file that will be created in the miner's folder. I need to take a closer look.
Sure but the file has over 11,000 lines, where can I post this?

> I wonder if you are running into the same issue I am/was in #554 since you as mentioned about windows200000 fork working fine for you, which doesn't have the whole `Don't set ACL channels online immediately` commit to it.

That's definitely possible, but I can't say for sure!

**Comment by guihkx** [comment]
>Sure but the file has over 11,000 lines, where can I post this?

I'm not sure if the file can be shared publicly (I'd wait on @DevilXD's confirmation), but you could compress it as a zip file and upload it here directly.

**Comment by DevilXD** [comment]
Hmm, I've taken a look at the dump file, and everything appears to be in order. However, #554 was discovered to be happening quite recently. Per #554, not using the "Priority list only" option, or having any of these games on the priority list, will severely impact the miner's performance, causing it to possibly stop mining:

- Eternal Return - 138 channels
- NARAKA: BLADEPOINT - 207 channels
- Smite 2 - 314 channels
- Don't Starve Together - 353 channels
- XDefiant - 638 channels
- Lost Ark - 641 channels
- Cult of the Lamb - 723 channels
- Ravendawn - 1043 channels

You can check out #554 for more information, but it's best to just remove those from the miner for now, and mine manually. This issue will resolve itself once new logic is implemented, which should be relatively soon - I'm working on it right now.

Despite this issue being first, the most relevant explanation exists in #554, so I have to close this as a duplicate.

**Comment by xr1rx** [comment]
> Hmm, I've taken a look at the dump file, and everything appears to be in order. However, #554 was discovered to be happening quite recently. Per #554, not using the "Priority list only" option, or having any of these games on the priority list, will severely impact the miner's performance, causing it to possibly stop mining:
> 
>     * Eternal Return - 138 channels
> 
>     * NARAKA: BLADEPOINT - 207 channels
> 
>     * Smite 2 - 314 channels
> 
>     * Don't Starve Together - 353 channels
> 
>     * XDefiant - 638 channels
> 
>     * Lost Ark - 641 channels
> 
>     * Cult of the Lamb - 723 channels
> 
>     * Ravendawn - 1043 channels
> 
> 
> You can check out #554 for more information, but it's best to just remove those from the miner for now, and mine manually. This issue will resolve itself once new logic is implemented, which should be relatively soon - I'm working on it right now.
> 
> Despite this issue being first, the most relevant explanation exists in #554, so I have to close this as a duplicate.

I will definitely try taking these out of the priority list in the meantime. Thanks for the quick rundown!
