### ISSUE TITLE
[Suggestion]Need console version or option

### ISSUE THREAD

**Issue by MadLongTom** [DevilXD/TwitchDropsMiner#55]
As the title says, the GUI consumes too much memory, and I want to let this program run in multithreading on the server.I tried to edit some code in gui.py,twitch.py and websocket.py ,but it caused some problem such as cannot switch channel automaticly and will show a blank window after websock launched.

**Comment by DevilXD** [comment]
Hello o/

This is exactly what "headless" mode does, and there already is an issue for this - please comment your thoughts there instead: #17 

Closing since this is a duplicate.
