### ISSUE TITLE
Error on new version with raspberry pi

### ISSUE THREAD

**Issue by yukaiin** [DevilXD/TwitchDropsMiner#553]
`python main.py
Traceback (most recent call last):
  File "/home/alex/Desktop/TwitchDropsMiner-master/main.py", line 25, in <module>
    from translate import _
  File "/home/alex/Desktop/TwitchDropsMiner-master/translate.py", line 7, in <module>
    from utils import json_load, json_save
  File "/home/alex/Desktop/TwitchDropsMiner-master/utils.py", line 22, in <module>
    from typing import Any, Literal, MutableSet, Callable, Generic, Mapping, TypeVar, ParamSpec, cast
ImportError: cannot import name 'ParamSpec' from 'typing' (/usr/lib/python3.9/typing.py)
`
no idea why this happens

**Comment by DevilXD** [comment]
Correct, Python 3.10 or higher is now needed to run the miner. I've finally upgraded from my old PC, which was still running Windows 7, that has reached it's EOL in 2020, where most of the miner code has been written on. Python 3.8.15 was the latest Python version that was able to run on Win7, with Python 3.9 or higher not being compatible anymore. Without the old PC holding me back, the minimum version has finally been updated.

Python 3.10 is used for the automatic builds via CI, so it makes sense to make it the new minimum. 3.8 is about to reach it's EOL, and 3.9 only has one more year before doing so as well: https://devguide.python.org/versions/
