### ISSUE TITLE
Commit f705cc1 causes some channels to never show ONLINE

### ISSUE THREAD

**Issue by JourneyOver** [DevilXD/TwitchDropsMiner#554]
Issue reference: https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2342407062

Copy+Paste from issue reference:
unsure of what is going on but I've recently noticed that the change you are talking about in https://github.com/Windows200000/TwitchDropsMiner-updated/issues/172#issuecomment-2328409646 with commit https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c makes it so that sometimes a channel never seems to come online in the miner even though it is clearly online on the site. I've tested this with the default version of the bot (as in from this repo) as well and not a forked version and it has the same problem.

Example:
I have ravendawn in my priority list along with a bunch of other games, and there are plenty of channels online for ravendawn (some channels have been streaming for hours) with drops active for it, and there is a drop going on currently until the 16th, but running the miner it never seems to pick up any of the online channels even after several hours (I tested letting it run for like ~7 hours and it never seemed to see a ravendawn channel online even though I checked periodically and everytime there was several channels online with drops active that had been online for 3-4+ hours).

Once I reverted the code change from that commit it ofc never had an issue with seeing any of the channels online and it instantly started mining... I'm unsure if the problem is affecting any other games/channels or not (I'm sure it probably is though)

Not sure if @Valentin-Metz has seen the same or not as well for any games, since he has the commit pushed into his repo as well, so I'm sure he probably has been.

**Comment by villario** [comment]
@JourneyOver TDM is fine for me, it works as expected (note: I have my own tiny patch (I've added one line) applied to skip sub/resub drops. Without skipping them for some reason TDM stuck on mining such drops and priority doesn't work in that case. As far as I understand Windows200000 fixed such issue by preventing dividing by 0 instead of removing specific drops from the list which caused dividing by 0. DevilXD's repo doesn't have such issues, because there are some checks on values and it's impossible to divide by 0).
I didn't check Windows200000's fork, but DevilXD applied fix for fetching data from Twitch - now data fetched by small portions (so at TDM's start some streams will be shown as Offline, but in like 5 minutes status will be updated and TDM will start mining game based on the priority).
I have almost the same output as Windows200000's fork has, so it (partial fetching) works like that:
```
07:49:42: No available channels to watch. Waiting for an ONLINE channel...
07:51:53: Firewall154 goes ONLINE, switching...
07:51:53: Watching: Firewall154
07:51:55: Game: Rocket League [RLCS '24 Worlds]: Progress: 1/120
```

**Comment by JourneyOver** [comment]
@villario

> but DevilXD applied fix for fetching data from Twitch - now data fetched by small portions (so at TDM's start some streams will be shown as Offline, but in like 5 minutes status will be updated and TDM will start mining game based on the priority).

Yes I know this was a recent change, and that was exactly the commit I was talking about in my OP but like I said I had even tested devilXD's version and not a fork and left things running for ~7 hours and channels that had been up the whole entire time while running TDM with a campaign active for a game (ravendawn from my example) that I had in my priority list just never came online in TDM at all even though like I just said there was multiple channels up the entire time that had drops activated I had TDM open...

**Comment by villario** [comment]
> @villario
> 
> > but DevilXD applied fix for fetching data from Twitch - now data fetched by small portions (so at TDM's start some streams will be shown as Offline, but in like 5 minutes status will be updated and TDM will start mining game based on the priority).
> 
> Yes I know this was a recent change, and that was exactly the commit I was talking about in my OP but like I said I had even tested devilXD's version and not a fork and left things running for ~7 hours and channels that had been up the whole entire time while running TDM with a campaign active for a game (ravendawn from my example) that I had in my priority list just never came online in TDM at all even though like I just said there was multiple channels up the entire time that had drops activated I had TDM open... it literally sat at `No available channels to watch. Waiting for an ONLINE channel...` for the entire ~7 hours that I had the app open as I had no other campaigns active other than that single one before I closed TDM down, and reverted said commit myself and then built the app and things started working again.
> 
> Windows200000's fork doesn't currently have the whole fetching of data in small portions commit like devils version does, so his version works perfectly fine right now short of it throwing a twitch is down error every so often which the reasoning on that is explained in the reference issue.
> 
> I'm not sure how big your priority list is, but this whole issue could very well be depending on how big someones priority list is, my current priority list contains 32 different games at the current time.

38 here :) I have the latest version and, as I said, patch to skip sub drops.
I have at least 2 issues:
- TDM feel bad if I open stream in browser or start "channel points miner" (TDM will not progress drops and start printing channel points messages - it doesn't print them if only TDM is active)
- claiming drops sometimes could take several hours :(

Can you get the latest version and apply my patch locally:
```
diff --git a/inventory.py b/inventory.py
index 5e885d9..f48c082 100644
--- a/inventory.py
+++ b/inventory.py
@@ -288,6 +288,7 @@ class DropsCampaign:
         self.timed_drops: dict[str, TimedDrop] = {
             drop_data["id"]: TimedDrop(self, drop_data, claimed_benefits)
             for drop_data in data["timeBasedDrops"]
+            if drop_data["id"] and drop_data.get("requiredSubs", 0) == 0
         }

     def __repr__(self) -> str:
```
and see if anything will change?

**Comment by JourneyOver** [comment]
Did a bit more testing, and added another game under my priority list below `Ravendawn` and it instantly picked it up and started watching a channel (tried with and without your little change)... So I'm honestly confused, maybe it's something specific to do with the specific game? 

@villario do you mind adding `Ravendawn` to your prio list and seeing if it works for you correctly or not?

**Comment by DevilXD** [comment]
Hello,

Two things here:

- The https://github.com/DevilXD/TwitchDropsMiner/commit/f705cc1527e806bb979df9e0dbd077d93728160c commit is crucial for not letting Twitch cut off the miner from accessing GQL. If you revert it, the miner will keep getting stuck. Rewriting the "channel refresh on reload" feature is still very high on my TODO list, and I'll get to it once I finish testing #488. My recommendation would be to not revert it, and instead focus on figuring out why it's not working as expected.  
- There should be nothing special about "Ravendawn", than any other game that exists on Twitch. Have you tried restarting the miner during those 7 hours of waiting for a channel to come online? Everything works on my side, baring having to wait 2 minutes for channels to update, as I've explained in my other comment. The viewer count updates are sent continuously every ~30 seconds, so even if the miner would miss one, the next one will set the channel online anyway.

**Comment by JourneyOver** [comment]
hello @DevilXD

> There should be nothing special about "Ravendawn", than any other game that exists on Twitch. Have you tried restarting the miner during those 7 hours of waiting for a channel to come online? Everything works on my side, baring having to wait 2 minutes for channels to update, as I've explained in my other comment. The viewer count updates are sent continuously every ~30 seconds, so even if the miner would miss one, the next one will set the channel online anyway.

Yes, I tried restarting several times during those 7 hours, but the same issue persisted. The campaign had been active since yesterday (Sep 9, 12:00 PM), and during that time, it successfully farmed 3 out of the 5 drops. However, today I noticed that the bot was no longer recognizing any channels streaming the game, even though I manually checked Twitch multiple times during those 7 hours. Each time I checked, there were channels with the drops active, and the bot was running without ever seeing them even after leaving the bot going for ~30-40+ minutes before doing another restart.

I'm not sure if something changed between yesterday and today that caused this issue, but from my testing over those 7 hours today, it never detected an active channel for Ravendawn. About 30 minutes ago, I added a different game with an active campaign to my list, and it instantly picked up the campaign and started farming it.

One odd thing that might help diagnose the issue: while I was testing with Ravendawn, the channels streaming the game never appeared in the bot's channel section under the `main` tab.

**Comment by JourneyOver** [comment]
> I'm guessing that this will resolve itself once I can rewrite the refresh logic. Until then, unfortunately, you'll need to either avoid adding Ravendawn to the priority list (as it'll oversaturate the channel list with offline channels), or just deal with it not mining sometimes.

Hmm okay, I'll probably just remove it from the list, since I haven't been playing the game lately anyways xD do wonder though if something along the lines of a batch processing to set ACL channels online like so for example:

```patch
diff --git a/twitch.py b/twitch.py
index f093728..32038cf 100644
--- a/twitch.py
+++ b/twitch.py
@@ -94,6 +94,8 @@ class SkipExtraJsonDecoder(json.JSONDecoder):
 # CLIENT_URL, CLIENT_ID, USER_AGENT = ClientType.MOBILE_WEB
 SAFE_LOADS = lambda s: json.loads(s, cls=SkipExtraJsonDecoder)
 
+BATCH_SIZE = 20  # Adjust this based on the expected rate limit
+REQUEST_DELAY = 0.5  # Delay between each batch to further avoid rate limits
 
 class _AuthState:
     def __init__(self, twitch: Twitch):
@@ -911,12 +913,11 @@ class Twitch:
                             no_acl.add(campaign.game)
                 # remove all ACL channels that already exist from the other set
                 acl_channels.difference_update(new_channels)
-                # use the other set to set them online if possible
-                # if acl_channels:
-                #     await asyncio.gather(*(
-                #         channel.update_stream(trigger_events=False)
-                #         for channel in acl_channels
-                #     ))
+
+                # Use batch processing to set ACL channels online
+                if acl_channels:
+                    await self.update_channels_in_batches(acl_channels, BATCH_SIZE, REQUEST_DELAY)
+
                 # finally, add them as new channels
                 new_channels.update(acl_channels)
                 for game in no_acl:
@@ -1040,6 +1041,28 @@ class Twitch:
                 break
             await self._state_change.wait()
 
+    async def update_channels_in_batches(self, channels, batch_size, delay):
+        """
+        Updates channels in batches to avoid hitting rate limits.
+
+        :param channels: Iterable of channels to update.
+        :param batch_size: Number of channels to process in each batch.
+        :param delay: Delay between each batch to further prevent rate-limiting.
+        """
+        channels_list = list(channels)
+        for i in range(0, len(channels_list), batch_size):
+            batch = channels_list[i:i + batch_size]
+            tasks = [channel.update_stream(trigger_events=False) for channel in batch]
+            results = await asyncio.gather(*tasks, return_exceptions=True)
+
+            # Log or handle exceptions for each channel update in the batch
+            for channel, result in zip(batch, results):
+                if isinstance(result, Exception):
+                    self.logger.error(f"Failed to update stream for channel {channel.id}: {result}")
+
+            # Wait before processing the next batch
+            await asyncio.sleep(delay)
+
     async def _watch_sleep(self, delay: float) -> None:
         # we use wait_for here to allow an asyncio.sleep-like that can be ended prematurely
         self._watching_restart.clear()
```

would work in the meantime to help alievate the issue or not really, I did do some testing with the batch processing stuff I did above and it seemed like it picked up Ravendawn just fine and didn't seem like it had caused any issues, but I'm not sure if it would of caused other issues or not at some point really as I didn't run a test for very long with it.

**Comment by DevilXD** [comment]
It'd be an "eh" and possibly slow monkey-patch, and I want to do it the right way. The GQL service can process up to 20 queries at a time, and that's already used when fetching information about campaigns: https://github.com/DevilXD/TwitchDropsMiner/blob/9c58befac35bde6f80fe93bb61c61961e296a5a5/twitch.py#L1395-L1412

The issue with doing this for channel status, is that the request is wrapped in the `update_stream` call already, so it's not easy to batch it. I'll need a way to extract it out of the function, run it in batch, then assign the result to each channel from a batch. It's doable, but I'm too far into #488 being almost finished, to just drop it and work on something else. Once that's done, only then I can work on this.

**Comment by JourneyOver** [comment]
Hmm alrighty, well I'll leave it up to you then on getting things implemented when you can.

**Comment by DevilXD** [comment]
Just as a FYI to anyone who'd find and see this issue - having any of these games on the priority list, or generally causing the miner to try and mine those, will severely impact the miner's performance, causing it to possibly stop mining. The more ACL channels a campaign has, the greater the risk of performance degradation. The miner's channel limit is 199 channels.

Partial degradation: 

• **Eternal Return** - 138 channels
• **NARAKA: BLADEPOINT** - 207 channels
• **Smite 2** - 314 channels
• **Don't Starve Together** - 353 channels

Severe degradation:

• **XDefiant** - 638 channels
• **Lost Ark** - 641 channels
• **Cult of the Lamb** - 723 channels
• **Ravendawn** - 1043 channels

For more information, please see the discussion above.

**Comment by DevilXD** [comment]
I've managed to implement the bulk status check logic via an external update to all channels: https://github.com/DevilXD/TwitchDropsMiner/commit/b9dfc75398caac63f9291ef4fff86eff0f4932f6

It seems to work just fine, at least in my testing. However, if someone has a lot of campaigns added to their priority list (30+), and those have a lot of ACL channels, the miner may still run into trouble with overburdening GQL with requests. Having all of the games listed in the previous comment on the priority list results in 4057 ACL channels in total, requiring 203 GQL requests of 20 channels each, to update their status. Then, any channel that's ONLINE also has the `drops_enabled` flag adjusted, leading to ~10 more requests being made. All of this happens in just a few seconds, and is quite an overkill, considering the miner only handles 199 channels, even if more than that would be ONLINE.

This kinda calls for a rewrite to the channel gathering logic, where the miner would only keeping updating status for channels that may still end up being below the limit, but I'm afraid that'd elongate that phase of the reload, by quite a lot. Before running all of these in parallel, the gathering phase was lasting 5-7 seconds for the 6 games I have on my priority list, and that was for about 300 channels. Assuming linear scale and 6s average, 4000 channels would take 82 seconds to refresh, which is quite a bit long.

This is something that I'd like to revisit in a rewrite, assuming it'd ever happen. For now, it's "let's hope Twitch doesn't get upset at this", and me maybe implementing a rate-limit handler for the GQL, that'll throttle the amount of requests when needed. Taking 2-3s more is better over getting the miner disconnected.
