### ISSUE TITLE
Inventory not showing completed drops when 'Finished' is checked

### ISSUE THREAD

**Issue by issue-reporter** [DevilXD/TwitchDropsMiner#563]
The inventory tab is no longer showing completed drops when the 'Finished' option is checked.

This feature used to show all the drops that finished, but recently seems to show nothing. Not sure if it's a bug or a change on Amazon's end, but figured I'd report it just in case.

Thanks for all your hard work, your project has really made Twitch drops something enjoyable again.

**Comment by DevilXD** [comment]
Hello,

A campaign will be shown as "Finished" only if it hasn't expired yet, and all drops from it have been mined out. In addition to this, none of the other filtering option can cause it to be hidden - to rule this out, you can check all of the filtering options and hit Refresh. Checking all of the options will always show all possible campaigns.

Expired and finished campaigns may sometimes still show in the inventory, but then it's up to Twitch to decide when it's going to disappear - I have no control over this.

Please confirm that you still cannot see them after checking all of the filtering options.

**Comment by DevilXD** [comment]
This should be now fixed by https://github.com/DevilXD/TwitchDropsMiner/commit/bd048e0cfa62a0ad705b4b97884651ed521196d8
