### ISSUE TITLE
No active campaigns to mine drops for. Waiting for an active campaign...

### ISSUE THREAD

**Issue by DygDyg** [DevilXD/TwitchDropsMiner#569]
No active campaigns to mine drops for. Waiting for an active campaign...

Перестал видить drops.

I started writing this message all the time. on twitch there is no “Twitch Mobile Web” in connections

build date: 2024-09-29 20:22:49+00:00 (May 19, 2023 66с3611

**Comment by DevilXD** [comment]
Hello,

Do you have any games added to the Priority list? If you just started using the miner, you have to configure it to let it know which games you're interested on. By default, it won't mine anything until you tell it what to mine. Additionally, you need to have your Twitch account linked with the game you intend on mining, otherwise a campaign isn't considered a mining target.

**Comment by DygDyg** [comment]
The problem turned out to be that the account was not linked, please indicate this nuance in the instructions, otherwise I did not know about this.

**Comment by DevilXD** [comment]
This is already stated in multiple places, including in-app help, as well as README of the project:

![picture](https://github.com/user-attachments/assets/c692b2a1-2e42-4e29-b442-df10dc74f879)

I'll try to make sure that information is more obvious to anyone visiting the project's page.

**Comment by guihkx** [comment]
>I'll try to make sure that information is more obvious to anyone visiting the project's page.

You could probably introduce an [issues template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms). You can then require users to read and check boxes for the most common questions asked here...

**Comment by DevilXD** [comment]
It's actually not a bad idea, but I kinda dislike the "robotic" way of how issues are reported through forms like that. The most important things I usually need to know about, is application version and the error the user is getting. If I don't know something, I can just ask for more information, or explain what happens/has happened, or how something works.

In addition to that, I actually quite enjoy user interactions through this "uncoordinated" way of reporting things. It's really not that bad, and I feel that being forced to fill out a form would take some of the charm away. If I really had to make a form for this, it'd only have "version", "error/traceback" and "description" fields anyway.

For now, let's just stick with improving the documentation. This should help relive the confusion about the account linking requirements.

**Comment by Bage340** [comment]
Есть ли возможность сделать так, чтобы Drops фармились и без привязки к аккаунту?

**Comment by Bage340** [comment]
Is there a way to make Drops farm without linking Twitch to an account with the game?

**Comment by DevilXD** [comment]
@Bage340 No, because that'd be against the project goals. If you'd like to learn more, you can check out the project goals description here: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

**Comment by Bage340** [comment]
> @Bage340 Нет, потому что это противоречит целям проекта. Если вы хотите узнать больше, вы можете ознакомиться с описанием целей проекта здесь: https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals

I'm sorry, but after reading the goals, I didn't find how mining drops without linking twitch to an account with the game can contradict them

**Comment by DevilXD** [comment]
If you really want me to answer that question, please open a separate issue.

**Comment by DevilXD** [comment]
I guess this can be closed now.
