### ISSUE TITLE
Fatal error keeps occuring

### ISSUE THREAD

**Issue by r5vx** [DevilXD/TwitchDropsMiner#578]
I have tried fully reinstalling, yet this keeps occurring and im not sure how to fix. It was working fine for a while and now today I can't get it to work at all.
 
 Fatal error encountered:
15:58:08: 
15:58:08: Traceback (most recent call last):
15:58:08:   File "main.py", line 155, in main
15:58:08:   File "twitch.py", line 587, in run
15:58:08:   File "twitch.py", line 747, in _run
15:58:08:   File "twitch.py", line 1656, in bulk_check_online
15:58:08:   File "asyncio\tasks.py", line 571, in _wait_for_one
15:58:08:   File "twitch.py", line 1387, in gql_request
15:58:08: exceptions.GQLException: [{'message': 'service error', 'path': ['channel', 'viewerDropCampaigns']}]
15:58:08: 
15:58:08: Exiting...

**Comment by Luckz** [comment]
Seems there's again a problem with some campaign: it starts successfully in Priority Only mode.

**Comment by Luckz** [comment]
I blocked Destiny 2 and now it doesn't crash anymore. Great success.

**Comment by DevilXD** [comment]
This is a duplicate of #415. Please see my response there.
