### ISSUE TITLE
oh baby kart does not get linked even if steam and twitch are both linked tried multiple ways

### ISSUE THREAD

**Issue by dragongrafdiscord** [DevilXD/TwitchDropsMiner#580]
![image](https://github.com/user-attachments/assets/4de3b0a9-83c2-455e-9d13-3351b6bab7b5)
![image](https://github.com/user-attachments/assets/2267fa8f-94fb-43fd-ad4a-b1bd30830f92)
my "whatever" are just place holders via inspect element

**Comment by DevilXD** [comment]
Hello,

Please perform a clean reconnect of your Twitch account to the game account. Some instructions for it can be found here: https://github.com/DevilXD/TwitchDropsMiner/issues/309#issuecomment-1749628379

Please let me know if you were able to resolve your issue.

**Comment by DevilXD** [comment]
I'm assuming that this has been resolved.
