### ISSUE TITLE
Unavoidable Crash - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by notNSANE** [DevilXD/TwitchDropsMiner#583]
```
14:58:08: Fatal error encountered:
14:58:08: 
14:58:08: Traceback (most recent call last):
14:58:08:   File "main.py", line 155, in main
14:58:08:   File "twitch.py", line 587, in run
14:58:08:   File "twitch.py", line 753, in _run
14:58:08:   File "twitch.py", line 1601, in get_live_streams
14:58:08:   File "twitch.py", line 1602, in <listcomp>
14:58:08:   File "channel.py", line 145, in from_directory
14:58:08: TypeError: 'NoneType' object is not subscriptable
14:58:08: 
14:58:08: Exiting...
14:58:08: 
14:58:08: Application Terminated.
14:58:08: Close the window to exit the application.
```

This is using the very latest dev version.

**Comment by T4bletopG4mes** [comment]
Possible cause (?)
![image](https://github.com/user-attachments/assets/85ab8b88-f269-49c9-8f62-17fe26786a9c)

**Comment by jordyamc** [comment]
> Possible cause (?) 
No, I have the same error but I'm not mining that game

**Comment by T4bletopG4mes** [comment]
> No, I have the same error but I'm not mining that game

Its an open reward campaign, not an open drop one but requires watch time. It could be something else but thats the only campaign that was added around the time the error started I think.

**Comment by jordyamc** [comment]
Ok, I found a workaround
[twitch.py:1605](https://github.com/DevilXD/TwitchDropsMiner/blob/1228ab0911b692e919a1206c7876c90e965b2132/twitch.py#L1605)
```diff
-for stream_channel_data in response["data"]["game"]["streams"]["edges"]
+for stream_channel_data in response["data"]["game"]["streams"]["edges"] if stream_channel_data["node"]["broadcaster"]
```

**Comment by DevilXD** [comment]
Hello,

Channel data being `None` usually means the streamer has been banned, and thus their channel information cannot be loaded. This was already taken care of in a few places, but apparently not in `get_live_channels`. I wouldn't think Twitch would return a banned channel when asked for a list of live streams, but so be it I guess.

Fixed in the latest master. Please verify everything works now.

**Comment by introvertism** [comment]
Not sure if this was related but using the latest master I was able to mine for about 40 minutes and then received this:

```
16:04:03: Watching: InfernoTheFireLord
16:43:12: Watching: mellowteddy
16:43:33: ERROR: Exception in _watch_loop task
16:43:33: Traceback (most recent call last):
16:43:33:   File "channel.py", line 380, in send_watch
16:43:33:   File "contextlib.py", line 199, in __aenter__
16:43:33:   File "twitch.py", line 1313, in request
16:43:33:   File "gui.py", line 2198, in coro_unless_closed
16:43:33:   File "aiohttp\client.py", line 1343, in send
16:43:33:   File "aiohttp\client.py", line 592, in _request
16:43:33: aiohttp.client_exceptions.InvalidUrlClientError: %5B%7B%22error%22:%22Can%20not%20find%20channel%22%7D%5D
16:43:33: 
16:43:33: The above exception was the direct cause of the following exception:
16:43:33: 
16:43:33: Traceback (most recent call last):
16:43:33:   File "utils.py", line 132, in wrapper
16:43:33:   File "twitch.py", line 888, in _watch_loop
16:43:33:   File "channel.py", line 401, in send_watch
16:43:33: exceptions.MinerException
16:43:33: Exiting...
16:43:33: 
16:43:33: Application Terminated.
16:43:33: Close the window to exit the application.

```

**Comment by carratala92** [comment]
057be65 works now without a problem. Thanks @DevilXD.

**Comment by DevilXD** [comment]
@introvertism That looks like it's worthy a separate issue: #586

I'm closing this one as fixed.
