### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by XKaos32X** [DevilXD/TwitchDropsMiner#6]
Redownloaded multiple times and keep running into the same error. I have multiple channels streaming and 2 of them have drops enabled. Keep getting this error:

Traceback (most recent call last):
  File "main.py", line 101, in <module>
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "twitch.py", line 266, in run
  File "channel.py", line 228, in check_online
  File "channel.py", line 221, in get_stream
TypeError: 'NoneType' object is not subscriptable
Exiting...
Application Terminated.
Close the window to exit the application.

**Comment by DevilXD** [comment]
Hmm, interesting. I'm assuming this comes from the latest `v9` version? An error like this implies that a stream exists, but the streamer doesn't, which makes little sense on it's own.

Which game from the Game Selector are you getting this for?

**Comment by DevilXD** [comment]
Actually, https://github.com/DevilXD/TwitchDropsMiner/commit/32f475d7ed4fc03c0e892644f24a7a61c172a77c should do at resolving the issue, regardless of the game. This will be fixed in `v10` once it's out.

**Comment by DevilXD** [comment]
This is now fixed in `v10`: https://github.com/DevilXD/TwitchDropsMiner/releases
