### ISSUE TITLE
Twitch Drops Without Linking a Game Account

### ISSUE THREAD

**Issue by GardoTL** [DevilXD/TwitchDropsMiner#603]
Hello, is it possible to farm Twitch drops for a game without having a linked game account?

**Comment by TheLovinator1** [comment]
Nope

**Comment by GardoTL** [comment]
:(

**Comment by DevilXD** [comment]
Hello,

To receive the drops, you'll need to link your account anyway. Without that, the claimed drop will expire within a week or two. Part of the linking requirement is there to prevent you from running into that situation, by requiring the linking beforehand.

Also, this has been asked many times in the past: #499, #162. The project goals also explain everything: https://github.com/DevilXD/TwitchDropsMiner#project-goals

Please use the search option before posting next time.
