### ISSUE TITLE
Problems with setting up the virtual environment

### ISSUE THREAD

**Issue by pwform** [DevilXD/TwitchDropsMiner#606]
![image](https://github.com/user-attachments/assets/c7e7d7a6-0cfe-4002-9bc4-34890b42642c)

**Comment by DevilXD** [comment]
Hello,

The error points towards either lack of necessary permissions, or incorrectly installed Python. If you're following the wiki installation guide, make sure to do it properly. Every selected option and sentence put there has a purpose.

: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

**Comment by pwform** [comment]
Forgot to answer you
Apparently there was some problem with Python 3.13, I reinstalled it and it worked (not for so long)
Then, a new problem appeared when creating the .exe with pyinstaller (tcl and tk), even after reinstalling python again
I uninstalled the 3.13 version and installed the 1.12 one, so everything went right!
Thank you for the help and thank you for the app!
