### ISSUE TITLE
Feature Request: Exclude channels, items?

### ISSUE THREAD

**Issue by rudowinger** [DevilXD/TwitchDropsMiner#609]
- To exclude channels von particular drops, i.e. when those are buggy
- To exclude drop items when they have strange properties and hinder one from getting the rest of the items

**Comment by DevilXD** [comment]
Hello,

> To exclude channels von particular drops, i.e. when those are buggy

"Buggy" isn't a good reason for a feature like this. Bugs have to be fixed, and this application is supposed to be as automatic as possible. If you're having trouble with an issue that involves a specific channel, please make a new issue describing what's happening, and I'll fix it. Unless, of course, you're talking about #586 here, in which case that's already been reported and being worked on - you just need to wait.

> To exclude drop items when they have strange properties and hinder one from getting the rest of the items

Again, it sounds like something that needs to be fixed instead. A feature to let you disable specific drops has been already suggested in #170, so this would be a duplicate. If you're interested, please comment under that issue instead.

For now, both of those is a NoFix from me. I'd rather put my time into fixing broken things.
