### ISSUE TITLE
Multiple errors running from source (Windows).

### ISSUE THREAD

**Issue by apotheosis-source** [DevilXD/TwitchDropsMiner#612]
Attempting to run the build from source in a virtual environment as stated in the wiki [here](https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running), Python version 3.12.3 results in a number of errors.

```
Traceback (most recent call last):
05:59:50:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\main.py", line 170, in <module>
05:59:50:     loop.run_until_complete(client.run())
05:59:50:   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
05:59:50:     return future.result()
05:59:50:            ^^^^^^^^^^^^^^^
05:59:50:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 764, in run
05:59:50:     await self._run()
05:59:50:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 806, in _run
05:59:50:     await self.fetch_inventory()
05:59:50:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 1598, in fetch_inventory
05:59:50:     b["id"]: timestamp(b["lastAwardedAt"]) for b in inventory["gameEventDrops"]
05:59:50:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:59:50:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\utils.py", line 89, in timestamp
05:59:50:     return datetime.strptime(string, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
05:59:50:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:59:50:   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\_strptime.py", line 554, in _strptime_datetime
05:59:50:     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
05:59:50:                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:59:50:   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\_strptime.py", line 333, in _strptime
05:59:50:     raise ValueError("time data %r does not match format %r" %
05:59:50: ValueError: time data '2024-11-07T23:46:56.126Z' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

The time conversion doesn't seem to consider the inclusion of milliseconds as part of the time string and fails, a potential fix would be to check for the decimal point in the string and sanitize/convert the input to make sure its compatible, using an except clause to handle millisecond format.

```
if '.' in string:
    return datetime.strptime(string, "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=timezone.utc)
else:
    return datetime.strptime(string[:-1] + ".0Z", "%Y-%m-%dT%H:%M:%S.%fZ").replace(tzinfo=timezone.utc)%SZ").replace(tzinfo=timezone.utc)
```

```
Traceback (most recent call last):
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\main.py", line 170, in <module>
05:44:10:     loop.run_until_complete(client.run())
05:44:10:   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
05:44:10:     return future.result()
05:44:10:            ^^^^^^^^^^^^^^^
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 764, in run
05:44:10:     await self._run()
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 806, in _run
05:44:10:     await self.fetch_inventory()
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\twitch.py", line 1644, in fetch_inventory
05:44:10:     await self.gui.inv.add_campaign(campaign)
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\gui.py", line 1293, in add_campaign
05:44:10:     campaign_image = await self._cache.get(campaign.image_url, size=(108, 144))
05:44:10:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\cache.py", line 99, in get
05:44:10:     img_hash = self._hash(image)
05:44:10:                ^^^^^^^^^^^^^^^^^
05:44:10:   File "C:\Users\admin\OneDrive\Warframe\Twitch Drops Miner\TwitchDropsMiner-dev-build\cache.py", line 78, in _hash
05:44:10:     pixel_data = list(image.resize((10, 10), Image_module.ANTIALIAS).convert('L').getdata())
05:44:10:                                              ^^^^^^^^^^^^^^^^^^^^^^
05:44:10: AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```

This is because the requirements.txt file doesn't specify a version for the pillow package, any pillow version 10.0.0 or later will fail

>ANTIALIAS was removed in Pillow 10.0.0 (after being deprecated through many previous versions). Now you need to use PIL.Image.LANCZOS or PIL.Image.Resampling.LANCZOS.<br>
>(This is the exact same algorithm that ANTIALIAS referred to, you just can no longer access it through the name ANTIALIAS.)<br>
>Reference: [Pillow 10.0.0 release notes (with table of removed constants)](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants)

**Comment by apotheosis-source** [comment]
Just checked and they appear to be fixed on the master branch, the latest release just needs to be updated.

**Comment by DevilXD** [comment]
I don't know what to get out of this issue report. The v15 release has warnings and "**DO NOT USE**" text plastered at the top and bottom of the release description, the executable has been removed to prevent people from downloading and trying to run the obviously old, outdated and broken version, and you've still managed to do it.

This bug has been fixed over a year ago on the master branch, on the 9th of October 2023, here: #311. It's also a duplicate of #312, #325, #329, #340, #345, #360, #361, #365, #368, #372, #388, #403 and #409.

Please use search before reporting anything.

**Comment by apotheosis-source** [comment]
> I don't know what to get out of this issue report. The v15 release has warnings and "**DO NOT USE**" text plastered at the top and bottom of the release description, the executable has been removed to prevent people from downloading and trying to run the obviously old, outdated and broken version, and you've still managed to do it.
> 
> This bug has been fixed over a year ago on the master branch, on the 9th of October 2023, here: #311. It's also a duplicate of #312, #325, #329, #340, #345, #360, #361, #365, #368, #372, #388, #403 and #409.
> 
> Please use search before reporting anything.

I downloaded off of Releases > Development Build > Assets > Source Code (zip). That's why I was mistakenly under the impression that these bugs were current. The source code in the assets tab should probably be updated (last updated 2023) or removed entirely.

**Comment by DevilXD** [comment]
> That's why I was mistakenly under the impression that these bugs were current.

Doesn't excuse you from not searching for the 13 already existing and closed issues, before creating a new one.

> The source code in the assets tab should probably be updated (last updated May 2023) to be in line with builds or removed entirely.

They're generated automatically by Github when a release is created, and cannot be removed. The development build's sole purpose is to provide an executable out of the current master branch. The only way to "refresh" the attached source code, would be to change the CI so that the entire pre-release build entry would be deleted and recreated, instead of being edited in with new files, like it currently is.

I wouldn't think it's really that much of an issue to take note of what you're actually downloading, but regardless. #613 has been created, and should result in the attached source code being refreshed alongside the executables accordingly.
