### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Evgencheg** [DevilXD/TwitchDropsMiner#619]
19:09:05: Fatal error encountered:
19:09:05: 
19:09:05: Traceback (most recent call last):
19:09:05:   File "main.py", line 155, in main
19:09:05:   File "twitch.py", line 587, in run
19:09:05:   File "twitch.py", line 753, in _run
19:09:05:   File "twitch.py", line 1601, in get_live_streams
19:09:05:   File "twitch.py", line 1602, in <listcomp>
19:09:05:   File "channel.py", line 145, in from_directory
19:09:05: TypeError: 'NoneType' object is not subscriptable

**Comment by Evgencheg** [comment]
![image](https://github.com/user-attachments/assets/fc665fb3-8b98-43bb-8bf1-7bd30b9c4b83)

**Comment by DevilXD** [comment]
Duplicate of #583. Update the application.
