### ISSUE TITLE
Problem: Output filled with cannot connect to twitch

### ISSUE THREAD

**Issue by josephisticated** [DevilXD/TwitchDropsMiner#62]
Is that ok? Should I run it like this?

**Comment by DevilXD** [comment]
Hello o/

That usually means you just can't reach the site right now. Please verify that you can't access https://twitch.tv via normal browser.

If you can reach the site via the browser, then there's something wrong going on at some point between the application and the server, which you'll have to verify. If you'd notice nothing wrong, then please let me know and we'll try to narrow down the issue somehow.

**Comment by MidnightD4wn** [comment]
i have the same issue :/

**Comment by MidnightD4wn** [comment]
i tried again it works now somehow

**Comment by DevilXD** [comment]
@MidnightD4wn Please verify access to the site "the normal way" via the browser, next time this would happen. If you can't access if via the browser, the app won't be able to access it either, and vice versa.

**Comment by MidnightD4wn** [comment]
thank you i'll do that, it works like a charm now ^^

**Comment by DevilXD** [comment]
@josephisticated Are you still having this issue?

**Comment by DevilXD** [comment]
Also, please try the newest `v14` release, apparently the `v13` one was not the one it was supposed to be: https://github.com/DevilXD/TwitchDropsMiner/releases

**Comment by matarife123** [comment]
![Captura de pantalla 2022-11-01 162506](https://user-images.githubusercontent.com/110930030/199271105-8bc10c59-7f48-4cdd-833f-871c1debb5ed.png)
V14

**Comment by matarife123** [comment]
it seems that twitch is down

**Comment by DevilXD** [comment]
@matarife123 This doesn't tell me anything, it's working perfectly fine for me. It looks like a connection issue on your side.

Can you access the twitch page normally?: https://twitch.tv

**Comment by DevilXD** [comment]
If that's so, then it's not a surprise the miner cannot connect to Twitch. Please remember to verify your connection to the website first, before reporting it next time :+1:

**Comment by DevilXD** [comment]
Since OP didn't reply, I'm assuming this issue has been dealt with for now.

**Comment by josephisticated** [comment]
sorry I haven't been able to log into github,
it's not solved, the problem is just the logs are filled with cannot connect to twitch but it still mines so I dont know if it'll cause any problem

**Comment by DevilXD** [comment]
There is exactly zero problems with it, as it's only an information for you that a request tried to reach Twitch, but couldn't - after the displayed amount of time, it'll retry sending the request again. It's normal to get one, two or a couple of those every once in a while, it happens when your internet connection is unstable. Usually that's temporary, but some people have a constantly unstable connection and will be getting those all the time - can't do anything about this.

If "it still mines", that only tells me and you that in between all of those retries, it's still doing it's job.
