### ISSUE TITLE
Why detected as a virus ?

### ISSUE THREAD

**Issue by bastienwilmotte** [DevilXD/TwitchDropsMiner#620]
I can't run the .exe because Windows Defender delete the .exe et mark the file as virus ?!

**Comment by bastienwilmotte** [comment]
-

**Comment by DevilXD** [comment]
Add it as an exception, or use a smarter antivirus engine than Windows Defender.

This is a duplicate of #616, #517, #508, #503, #420, #384, #335, #333, #315, #284, #270, #249, #217, #209, #137 and #13. Please search the existing issues (even closed ones) before submitting an issue yourself.
