### ISSUE TITLE
[FEAT] Web UI, Containerization?

### ISSUE THREAD

**Issue by Davixk** [DevilXD/TwitchDropsMiner#621]
Hello, thanks for your great work!

Would you be interested in moving the UI to be served via web, and containerize the app?
I can help with a Django / Docker setup, and with Docker CD Actions workflows.

I think it would make the project more accessible and greatly enhance flexibility on deployments.

**Comment by JourneyOver** [comment]
Devil has no plans on ever having a docker setup going for this by default, as mentioned in #111 and #425 and #17 as well as his [project goals](https://github.com/DevilXD/TwitchDropsMiner?tab=readme-ov-file#project-goals)

**Comment by DevilXD** [comment]
Hello,

As the other person have mentioned, the goals of this project do not cover any form of "deployment" or UI access via web. This is a desktop application - you're supposed to simply download and install it on a desktop computer (laptop also works), and then use it like any other application. If you need to check how it's doing, simply use the already-existing GUI to interact with the software. That's it. Server usage and any form of remote deployment is not supported.
