### ISSUE TITLE
V16 no LOGIN

### ISSUE THREAD

**Issue by Lifeng77X** [DevilXD/TwitchDropsMiner#625]
Hello, while I wait to find a way to install it on my UNRAID server, I decided to do it via WINDOWS. 

My problem is that when I launch the .EXE, I do not have the option to enter my login credentials.

![image](https://github.com/user-attachments/assets/bf625943-7efa-4715-b7f6-295362aac90d)

- I have already tried to delete the file cookies.jar, but it didn't yield any results...

**Comment by DevilXD** [comment]
Hello,

I am unable to reproduce this. The only case where you won't get to login without the cookie file being present, is when there's no internet connection available upon launching the application - which is exactly what are the messages in the output window about. Please check your internet connection first, and confirm that you can open https://www.twitch.tv in your browser as normal.

**Comment by Lifeng77X** [comment]
Thank you for your analysis regarding the fact that the .exe did not have internet access, 

which allowed me to identify the source of the problem. It is actually "Bitdefender that was blocking it...". 

Problem resolved.
