### ISSUE TITLE
PersistedQueryNotFound on the DropCampaignDetails GQL operation

### ISSUE THREAD

**Issue by DevilXD** [DevilXD/TwitchDropsMiner#626]
```py
08:46:27: Fatal error encountered:
08:46:27: 
08:46:27: Traceback (most recent call last):
08:46:27:   File "main.py", line 155, in main
08:46:27:   File "twitch.py", line 587, in run
08:46:27:   File "twitch.py", line 637, in _run
08:46:27:   File "twitch.py", line 1468, in fetch_inventory
08:46:27:   File "asyncio\tasks.py", line 571, in _wait_for_one
08:46:27:   File "twitch.py", line 1425, in fetch_campaigns
08:46:27:   File "twitch.py", line 1387, in gql_request
08:46:27: exceptions.GQLException: [{'message': 'PersistedQueryNotFound'}]
08:46:27: 
08:46:27: Exiting...
08:46:28: 
08:46:28: Application Terminated.
08:46:28: Close the window to exit the application.
```

_Originally posted by @dragongrafdiscord in https://github.com/DevilXD/TwitchDropsMiner/issues/590#issuecomment-2482183055_

**Comment by dragongrafdiscord** [comment]
alright could u write me a message here when there is a new dev build? :D

**Comment by DevilXD** [comment]
Still no hash change. This seems different than normal. We'll need to wait some more.

@dragongrafdiscord You can just "watch" this repo to receive updates for it. The "Watch" button is at the top of the repository's main page.

**Comment by dragongrafdiscord** [comment]
alr will try
hopefully the watch also works when custom for releases bc i dotn wana get notified for every each thing
also currently it seems to be running alr again... 
![image](https://github.com/user-attachments/assets/2b8a834b-a81b-4882-b1d0-98ddf8d0128a)
and i still have a bit older dev build but as long as it works its alr for me (unless u add some nice features)

**Comment by Totesfleisch** [comment]
Having the same Issue. I realized, when there is a Campaign for Caliber Live, theres a 99% Guarantee it crashes. without the Game having an active campaign, its more like 70/30 Chance, however, it eventually will always crash.
That being said, when i use a forked Version of the Project that hasnt been updated in a while. It works fine, aside from the Issue that said older Miner doesnt recognize some Games having active Streams.

**Comment by DevilXD** [comment]
The hashes have been updated a while ago, so this should no longer be happening: https://github.com/DevilXD/TwitchDropsMiner/commit/2c5f56b33b49552a1784dc1e6320860b1c0a99ad
