### ISSUE TITLE
No active campgains to mine drops for. Waiting for an active campgain...

### ISSUE THREAD

**Issue by i2r1st** [DevilXD/TwitchDropsMiner#63]
What is this?

**Comment by DevilXD** [comment]
Hello o/

I'm assuming you've figured it out already. But basically, it means that there's no campaigns that are currently account-linked, selected and active - only those can be mined. You can manage your account links here: https://www.twitch.tv/drops/campaigns

With no campaigns to mine, the application is just going to wait and idle until one becomes available.
