### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by justanoldgit** [DevilXD/TwitchDropsMiner#632]
tkinter is in the lib folder, 
-m site lists 'D:\\Program Files\\Python313\\Lib',
python -m tkinter gives a box with this is Tcl/Tk 8.6.14
still when i run the exe i get 

Traceback (most recent call last):
  File "main.py", line 17, in <module>
ModuleNotFoundError: No module named 'tkinter'

in new to all this and have exhausted my googling ability

**Comment by TheLovinator1** [comment]
Related: https://github.com/DevilXD/TwitchDropsMiner/issues/581, https://github.com/DevilXD/TwitchDropsMiner/issues/605

Use [Python 3.12.7](https://www.python.org/downloads/release/python-3127/) if you want to build the project.

**Comment by DevilXD** [comment]
Hello,

Yeah, that one's related to the Python 3.13.0 bug. Just use the latest available 3.12.X version instead.

Closing this as a duplicate.

**Comment by JourneyOver** [comment]
Either downgrade to 3.12.X or upgrade to 3.13.1 and it'll solve this issue.
