### ISSUE TITLE
Fatal error encountered

### ISSUE THREAD

**Issue by Kitesszh** [DevilXD/TwitchDropsMiner#635]
14:53:37: Fatal error encountered:
14:53:37: 
14:53:37: Traceback (most recent call last):
14:53:37:   File "twitch.py", line 1588, in get_live_streams
14:53:37:   File "twitch.py", line 1387, in gql_request
14:53:37: exceptions.GQLException: [{'message': 'service error', 'path': ['game']}]
14:53:37: 
14:53:37: The above exception was the direct cause of the following exception:
14:53:37: 
14:53:37: Traceback (most recent call last):
14:53:37:   File "main.py", line 155, in main
14:53:37:   File "twitch.py", line 587, in run
14:53:37:   File "twitch.py", line 753, in _run
14:53:37:   File "twitch.py", line 1599, in get_live_streams
14:53:37: exceptions.MinerException: Game: world-of-tanks

**Comment by DevilXD** [comment]
Duplicate of #415.
