### ISSUE TITLE
I have problems with version 13 (I don't see anything in the inventory anymore)

### ISSUE THREAD

**Issue by Slippy2k** [DevilXD/TwitchDropsMiner#64]
I don't see anything in the inventory anymore, so it tells me that there is nothing to drop and under websocket I only have 2 connections there I always had 50/50 and 18/50
![1](https://user-images.githubusercontent.com/36570207/198310252-fb104d2a-0c6e-406e-975f-5d0af64a443f.jpg)
![2](https://user-images.githubusercontent.com/36570207/198310262-54edcc60-4feb-4d70-8688-ad62c7750eee.jpg)

**Comment by DevilXD** [comment]
Hello o/

It looks like you're using the 6th dev version of `v13`. This is pretty bad, as only the release `v13` has the changes that currently work. You're only going to get errors with any of the `v13` dev versions.

Please make sure to grab the latest non-dev `v13` release: https://github.com/DevilXD/TwitchDropsMiner/releases

Also make sure to read the important notice in it's description. Not doing so might read to problems.

Please let me know if that solves your issue.

**Comment by matarife123** [comment]
> Hello o/
> 
> It looks like you're using the 6th dev version of `v13`. This is pretty bad, as only the release `v13` has the changes that currently work. You're only going to get errors with any of the `v13` dev versions.
> 
> Please make sure to grab the latest non-dev `v13` release: https://github.com/DevilXD/TwitchDropsMiner/releases
> 
> Also make sure to read the important notice in it's description. Not doing so might read to problems.
> 
> Please let me know if that solves your issue.

the link contains v13 dev 6

**Comment by matarife123** [comment]
> I don't see anything in the inventory anymore, so it tells me that there is nothing to drop and under websocket I only have 2 connections there I always had 50/50 and 18/50 ![1](https://user-images.githubusercontent.com/36570207/198310252-fb104d2a-0c6e-406e-975f-5d0af64a443f.jpg) ![2](https://user-images.githubusercontent.com/36570207/198310262-54edcc60-4feb-4d70-8688-ad62c7750eee.jpg)

you have V13 no dev?

**Comment by DevilXD** [comment]
Hmm. Well, that's not what it's supposed to contain. The current release is supposed to say just `v13`, with no additional `dev` to it.

Please give me a minute to sort this out.

**Comment by DevilXD** [comment]
@matarife123 Please try the `v14` one: https://github.com/DevilXD/TwitchDropsMiner/releases

**Comment by matarife123** [comment]
> @matarife123 Please try the `v14` one: https://github.com/DevilXD/TwitchDropsMiner/releases

seems to work, although I don't see some drops
![Captura de pantalla 2022-10-27 180615](https://user-images.githubusercontent.com/110930030/198344159-1e663f4d-b7ef-429c-b3ef-4e8cee2308f5.png)

**Comment by DevilXD** [comment]
Please define "I don't see some drops". Are you talking about the Inventory tab? If so, you may need to play around with the filters to see everything, in particular, checking "Finished", "Excluded" and "Expired", and unchecking "Linked only" should show you the entire in-memory inventory state.

**Comment by matarife123** [comment]
> Defina "No veo algunas gotas". ¿Estás hablando de la pestaña Inventario? Si es así, es posible que deba jugar con los filtros para ver todo, en particular, marcar "Terminado", "Excluido" y "Caducado", y desmarcar "Solo vinculados" debería mostrarle el estado completo del inventario en memoria.

for example the game "dragon raja" does not appear to me, even if I give it priority

**Comment by matarife123** [comment]
this is the problem, the bot does not find drops, although there are online channels with active drops
![Sin título](https://user-images.githubusercontent.com/110930030/198353088-dcfc19dd-b221-4ef6-b476-98eeda1c3a30.png)

**Comment by DevilXD** [comment]
@matarife123 Can you confirm you have your account linked to be able to receive the drops? The application won't mine any campaign that you don't have an account linked to, but normally you can still earn the drops through Twitch, just not claim them.

Please go to the inventory tab, check "Excluded" and uncheck "Linked only", find the Dragon Baja campaign and post a picture of it like so (this is mine):
![obraz](https://user-images.githubusercontent.com/4180725/198367112-855db034-6201-44d9-bc6d-e3c912977986.png)

**Comment by matarife123** [comment]
true, I do not have a linked account and it is very complicated for what I tried, thank you very much.

**Comment by matarife123** [comment]
@DevilXD any way to get the drop without linking the account?

**Comment by DevilXD** [comment]
@matarife123 No, the application currently only considers campaigns where drops can be claimed, meaning you have to have your account linked. If there's no linked account, it's not going to mine it. This limitation is there because otherwise, with the "Priority Only" option unchecked, it would try to mine every single campaign that's currently active. This includes all campaigns in the "Open Campaigns" section on the campaigns page: https://www.twitch.tv/drops/campaigns
![obraz](https://user-images.githubusercontent.com/4180725/198381630-46960522-90e7-42dc-8802-0182d6d434b4.png)

There is currently 41 campaigns, which would easily overwhelm (but hopefully not break) the application, if it tried to mine everything at once.

**Comment by Slippy2k** [comment]
The problem still persists, I deleted the cookies.jar and settings.json then logged in again and I still don't see anything in the inventory. I tried it now with 2 accounts and with both the same
![1](https://user-images.githubusercontent.com/36570207/198383534-bb85e579-1b59-4a96-9e9e-d206d986787c.jpg)
![2](https://user-images.githubusercontent.com/36570207/198383538-d7b1e68f-2f8e-4106-944c-02c95fec8991.jpg)

**Comment by matarife123** [comment]
it works for me
![Captura de pantalla 2022-10-27 221739](https://user-images.githubusercontent.com/110930030/198389632-db14e3bf-0b77-4975-b793-cf7ca415cb44.png)

**Comment by DevilXD** [comment]
@Slippy2k Please go to the inventory tab, then uncheck "Linked Only", then check all three leftover options ("Expired", "Excluded" and "Finished"). Press on "Refresh" and see if the inventory displays anything. If so, please take a picture and post it here.
![obraz](https://user-images.githubusercontent.com/4180725/198507231-ca9917fe-399f-4e23-8b0c-487e336a81a5.png)

**Comment by Slippy2k** [comment]
> @Slippy2k Please go to the inventory tab, then uncheck "Linked Only", then check all three leftover options ("Expired", "Excluded" and "Finished"). Press on "Refresh" and see if the inventory displays anything. If so, please take a picture and post it here. ![obraz](https://user-images.githubusercontent.com/4180725/198507231-ca9917fe-399f-4e23-8b0c-487e336a81a5.png)

now it works for me too :) I really had to unlink them all again and then re-link them
