### ISSUE TITLE
Fatal error encountered: PersistedQueryNotFound in Rust

### ISSUE THREAD

**Issue by LucasWinkler** [DevilXD/TwitchDropsMiner#640]
I started running this before I went to sleep. When I woke up I believe my computer crashed or auto-restarted for some reason and now I get this error every time I open the miner.

Error:
```python
14:43:29: Fatal error encountered:
14:43:29: 
14:43:29: Traceback (most recent call last):
14:43:29:   File "twitch.py", line 1736, in get_live_streams
14:43:29:   File "twitch.py", line 1575, in gql_request
14:43:29: exceptions.MinerException: GQL error: [{'message': 'PersistedQueryNotFound'}]
14:43:29: 
14:43:29: The above exception was the direct cause of the following exception:
14:43:29: 
14:43:29: Traceback (most recent call last):
14:43:29:   File "main.py", line 160, in main
14:43:29:   File "twitch.py", line 772, in run
14:43:29:   File "twitch.py", line 923, in _run
14:43:29:   File "twitch.py", line 1747, in get_live_streams
14:43:29: exceptions.MinerException: Game: rust
14:43:29: 
14:43:29: Exiting...
14:43:30: 
14:43:30: Application Terminated.
14:43:30: Close the window to exit the application.
```

**Comment by DevilXD** [comment]
Hello,

The error implies the has operation has changed for that GQL operation, but I've just checked and it's the same one on my side. Either Twitch is rolling out a new feature again, or there's something fishy going on in the background. This is similar to what #626 is all about.

If the issue persists, give it 24 hours and try using the miner again. Do not launch the miner in the mean time. It could be a new way for Twitch shooing away bots and scripts (as they've always been doing).

**Comment by LucasWinkler** [comment]
> Hello,
> 
> The error implies the has operation has changed for that GQL operation, but I've just checked and it's the same one on my side. Either Twitch is rolling out a new feature again, or there's something fishy going on in the background. This is similar to what #626 is all about.
> 
> If the issue persists, give it 24 hours and try using the miner again. Do not launch the miner in the mean time. It could be a new way for Twitch shooing away bots and scripts (as they've always been doing).

Sounds good! I'll try it out tomorrow, thanks.

**Comment by fxrmed** [comment]
> Hello,
> 
> The error implies the has operation has changed for that GQL operation, but I've just checked and it's the same one on my side. Either Twitch is rolling out a new feature again, or there's something fishy going on in the background. This is similar to what #626 is all about.
> 
> If the issue persists, give it 24 hours and try using the miner again. Do not launch the miner in the mean time. It could be a new way for Twitch shooing away bots and scripts (as they've always been doing).

Hi!

I could observe on my side that the hash for the gql request `DirectoryPage_Game` was changed to the hash `c7c9d5aad09155c4161d2382092dc44610367f3536aac39019ec2582ae5065f9`. They also added the variable `includeIsDJ` to the `DirectoryPage_Game` request which is a bool and was set to true in the request sent from my browser. 

They also added another variable to the gql request `PlaybackAccessToken` which is the string `platform` which was set to the value `web` in the my requests.

After these changes the initial error and crash appeared to be fixed, and the bot seems to be working fine mining drops.

**Comment by LucasWinkler** [comment]
> So, how did it go? Is the error gone?

Sorry I forgot to reply. It worked fine after waiting the time.

**Comment by DevilXD** [comment]
Some hashes were updated via https://github.com/DevilXD/TwitchDropsMiner/commit/2c5f56b33b49552a1784dc1e6320860b1c0a99ad, so this should more or less not be a problem anymore.
