### ISSUE TITLE
[Idea] Implement Automatic Restart on Exception in TDM

### ISSUE THREAD

**Issue by someC0d3r** [DevilXD/TwitchDropsMiner#646]
I occasionally encounter exceptions with Twitch Drops Miner (TDM) on my server, causing the miner to halt until I manually restart it via remote desktop.

**Proposed Feature: Automatic Restart on Exception**

Introduce an optional setting, or enable by default, that allows TDM to automatically restart when an exception occurs.

**Additional Safeguard: Retry Limit**

To prevent potential issues, implement a threshold such as:

- If TDM attempts to restart 5 times within a 15-minute period, it should cease further restart attempts. (maybe make values configurable)

What are your thoughts on this enhancement?

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add functionality to automatically restart the miner on exception, with a retry limit to prevent excessive restarts.

You can review changes in this commit: https://github.com/wwqwq2313/DevilXD-TwitchDropsMiner-646/commit/27750ab79262f85994422641f3993b9dfdc3f068.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
