### ISSUE TITLE
Traceback Error When Claming Drops

### ISSUE THREAD

**Issue by Cryptic-Soldier** [DevilXD/TwitchDropsMiner#653]
### Description

Using the latest build. everything runs fine, but after awhile, the program crashes with a traceback error, forcing me to restart. This is causing me to miss out on drops because I let the program AFK, and I'm not finding it until later.

### To Reproduce

As far as I know, run the program.

### Expected behavior

The program should run.

### Observed behavior

The program is crashing.. possibly a twitch update? The error suggests that this is a problem with claiming the drop? Looks like it crashes after it claims one.

### Screenshots

![lTAur9n](https://github.com/user-attachments/assets/9340ba47-37ac-4173-8175-d30a059783ca)

### OS

Windows 11

### Build

.exe and source code

### Version/Commit

Latest Dev Build

### Additional context

Using the latest dev build, as soon as the timer hits 0 on a drop, the program crashes with the above error forcing the end user to exit and restart. If left unattended as most people do with this program, this will cause people to miss out on drops.

This bug is copied from @Windows200000 branch of the build, but is present in both theirs (their latest build, which also has a dark mode) and yours.

**Comment by DevilXD** [comment]
Hello.

The traceback doesn't match anything that can be found in my miner, so this whole report is invalid. I am not responsible for, nor interested in, solving issues in any forks you might be using. If you're using a forked version of the miner - please report this under the the fork's repository instead. If you do actually encounter an issue with my miner, then I expect the traceback to match the currently present miner's code - cross-posting like this serves exactly zero purpose.

Besides, a fix for this issue has already been pushed out yesterday (https://github.com/DevilXD/TwitchDropsMiner/commit/1dac01b1415263c4371a1918828ef2fd4cc39e40), so it seems to me like you aren't using the "Latest Dev Build" like you're claiming to be.
