### ISSUE TITLE
i cant get v13

### ISSUE THREAD

**Issue by matarife123** [DevilXD/TwitchDropsMiner#66]
I cleared cache, cookies and logged in again, still I can't get v13 no dev
![Captura de pantalla 2022-10-27 173115](https://user-images.githubusercontent.com/110930030/198333684-e300620d-77b5-43c0-b209-578d2edc76fd.png)

**Comment by DevilXD** [comment]
I've responded to you under #64, please see my response there.

**Comment by DevilXD** [comment]
Please keep it to #64 as this is yet another duplicate of the same issue. There's no need to split the discussion like this.
