### ISSUE TITLE
Issues with Campaign ACLs

### ISSUE THREAD

**Issue by EffortlessFury** [DevilXD/TwitchDropsMiner#69]
So, I was having a similar issue to #38, and in this case, it is the Honkai Impact 3rd campaign. I investigated the "Inventory" page's query response JSON for the campaign ACLs and it is reporting the existence of an ACL; it does not specify that the ACL is disabled. However, the request being made from the "All Campaigns" tab DOES specify that it is disabled.

For reference, the request being made on the "All Campaigns" tab is using operationName "DropCampaignDetails" for each individual campaign.

I've verified that any channel playing the game with Drops Enabled is generating progress, indicating that the "Inventory" page's query response is inaccurate, while the "All Campaigns" response is accurate.

**Comment by DevilXD** [comment]
Hello o/

I'm a little bit confused about what you're trying to say. According to what I just checked, the campaign you've mentioned has a disabled ACL with two channels on it, thus it should end up as "Allowed channels: All" on the inventory tab in the miner. If that's not the case, please restart the application to see if it fixes the issue.

**Comment by EffortlessFury** [comment]
I have tried restarting, trust me. XD Here's my application:
![image](https://user-images.githubusercontent.com/1612977/198836671-0ab14d8f-9598-48f7-b1d7-33360c4218fb.png)
Here's the response from my Inventory tab:
![image](https://user-images.githubusercontent.com/1612977/198836732-80988f32-0ddf-4759-ae0e-e49401cf9598.png)
Here's the response from my All Campaigns tab:
![image](https://user-images.githubusercontent.com/1612977/198836788-8d52cf56-a132-4c9b-994a-b09787ad0215.png)

**Comment by DevilXD** [comment]
I see. Are you able to run the latest master branch build?

**Comment by EffortlessFury** [comment]
Not initially, had to copy over my cookies, didn't realize it'd JUST broken. Yikes.

Still has the issue, if you were expecting it to not be an issue.

**Comment by DevilXD** [comment]
No, I wasn't expecting nor did / changed anything, just asking if you'd be willing to immediately try out a solution once I add it in. I can't test it myself since I can't progress that campaign.

**Comment by EffortlessFury** [comment]
Gotcha gotcha, yeah I can.

**Comment by EffortlessFury** [comment]
Also, at this point, I recognize it is probably not worth investigating this issue given the state of the project, so feel free to close this if that's the case.

**Comment by DevilXD** [comment]
I'm good, as long as you have a valid cookie you can test it on. If you've ran into #68, this can also stay open until I'm able to revive this project again (hopefully).

Still working on a special version for you, but I just had a working weekend, so haven't gotten enough free time to really sit on it yet.

**Comment by DevilXD** [comment]
My testing shows that the fix I just implemented in https://github.com/DevilXD/TwitchDropsMiner/commit/fdd0172abf71e5a49ee8253533523b969ac9b969 registers the campaign in question as one with no ACL now:
![obraz](https://user-images.githubusercontent.com/4180725/199094865-8a57af23-bfdf-4a90-bfa2-b8c512d6c43e.png)

Please give the latest master a go and tell me if it fixes your issue :slightly_smiling_face:

**Comment by EffortlessFury** [comment]
So, I'm a dumbass and accidentally finished the campaign before I could test this. However, looking over your solution, it makes sense to me, and seeing as you said you tested it, it checks out in my book. Thanks for addressing it!

**Comment by DevilXD** [comment]
This is now fixed in `v15`.
