### ISSUE TITLE
ImportError: You need to install Visual C++ Redist

### ISSUE THREAD

**Issue by LaoMingZi** [DevilXD/TwitchDropsMiner#76]
F:\TwitchDropsMiner-master>main
Traceback (most recent call last):
  File "F:\TwitchDropsMiner-master\twitch.py", line 22, in <module>
    from seleniumwire.request import Request
ModuleNotFoundError: No module named 'seleniumwire'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\TwitchDropsMiner-master\main.py", line 39, in <module>
    from twitch import Twitch
  File "F:\TwitchDropsMiner-master\twitch.py", line 26, in <module>
    raise ImportError(
ImportError: You need to install Visual C++ Redist (x86 and x64): https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

**Comment by DevilXD** [comment]
Hello o/

Well, what's the matter? The error tells you what to do. Follow the link and install the latest C++ Redistributables please: https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads

This error exists for the end user like you, not me.

**Comment by DevilXD** [comment]
Also, are you trying to run a release executable or a dev version from source, because you could get this from the dev version if your `env` folder is old. You can delete it and then recreate it by running `setup_env.bat` again.

**Comment by DevilXD** [comment]
@LaoMingZi Were you able to resolve the issue?

**Comment by LaoMingZi** [comment]
> @LaoMingZi Were you able to resolve the issue?
I'm sorry I can't

**Comment by DevilXD** [comment]
Well, I can't install the C++ Redis for you then, and if you're unable to do it yourself, then unfortunately my ability to help you ends here.

Again, please try installing the C++ Redis the error message links you to. Then delete the `env` folder from the project's directory, and run `setup_env.bat` again to recreate it, and it should work.

**Comment by LaoMingZi** [comment]
C++has been installed many times. Thank you. I'll try again

**Comment by DevilXD** [comment]
It could be just a matter of recreating the `env` folder then. Please let me know how it went.

**Comment by LaoMingZi** [comment]
It is still invalid, which may be the reason why the chorme plug-in installation cannot be completed. Opening VPN to obtain it from GitHub will fail.

**Comment by LaoMingZi** [comment]
Can I download the Chrome plug-in to the disk and install it independently?

**Comment by DevilXD** [comment]
> It is still invalid, which may be the reason why the chorme plug-in installation cannot be completed.

I'm not sure I understand. Is there an error you're getting while running `setup_env.bat`? Would it be possible for me to see it's entire output?

**Comment by LaoMingZi** [comment]
> > It is still invalid, which may be the reason why the chorme plug-in installation cannot be completed.
> 
> I'm not sure I understand. Is there an error you're getting while running `setup_env.bat`? Would it be possible for me to see it's entire output?

Program Error Video[https://youtu.be/Nx1-1C73l74](url)

**Comment by DevilXD** [comment]
Hold on a second, I just realized:

![obraz](https://user-images.githubusercontent.com/4180725/204312656-b98495f9-4577-496a-ae9b-963d17754e95.png)

That's not how you run this thing. The `env` folder serves as a virtual environment (venv) for all the installed packages. To be able to use them, you need to either activate the venv first, and then run `python main.py` for a with-console run, or `pythonw main.py` for the intended no-console run, OR, use the `.../env/scripts/python` and `.../env/scripts/pythonw` executables directly to run the `main.py` file instead (as that's all the "venv activation" does, redirects bare `python` calls to those executables).

If you try running just `python main.py` (or simply `main` like you're doing), it's going to use the global python installation and it's packages, instead of those installed in the `env` folder. Since they're only installed in that folder, your global installation packages do not contain the `seleniumwire` library, leading to this error.

Please try running it from the venv first, before doing the steps above.

**Comment by LaoMingZi** [comment]
Thank you very much, it's solved.

**Comment by LaoMingZi** [comment]
Thank you for your patient guidance and sharing, I want to share and promote it to more players in China, so that more people will know that you are the author of the software.

**Comment by LaoMingZi** [comment]
> Hold on a second, I just realized:
> 
> ![obraz](https://user-images.githubusercontent.com/4180725/204312656-b98495f9-4577-496a-ae9b-963d17754e95.png)
> 
> That's not how you run this thing. The `env` folder serves as a virtual environment (venv) for all the installed packages. To be able to use them, you need to either activate the venv first, and then run `python main.py` for a with-console run, or `pythonw main.py` for the intended no-console run, OR, use the `.../env/scripts/python` and `.../env/scripts/pythonw` executables directly to run the `main.py` file instead (as that's all the "venv activation" does, redirects bare `python` calls to those executables).
> 
> If you try running just `python main.py` (or simply `main` like you're doing), it's going to use the global python installation and it's packages, instead of those installed in the `env` folder. Since they're only installed in that folder, your global installation packages do not contain the `seleniumwire` library, leading to this error.
> 
> Please try running it from the venv first, before doing the steps above.

Thank you for your patient guidance and sharing, I want to share and promote it to more players in China, so that more people will know that you are the author of the software.
