### ISSUE TITLE
Suggestion: show currently-idled game name

### ISSUE THREAD

**Issue by Luckz** [DevilXD/TwitchDropsMiner#85]
The UI could show the game name on the left side, I suppose in the Campaign area.
Campaign names often don't include the game name.
Sometimes the 'Game' shown for the listed streamer on the right UI side in 'Channels' does not match what you are expecting to be idling.

![image](https://user-images.githubusercontent.com/224748/204686828-32ccb2c9-e618-46af-99a2-3be14afe2e0b.png)

![image](https://user-images.githubusercontent.com/224748/204686869-5ed26c1e-c927-444f-9041-40bb222755a3.png)

Similarly, the log line:
_Claimed drop: FM Lower Suit Skull-Black (2/2)_ could be improved to show the game name.

P.S.: Maybe when not idling, the progress bar colours could be different or the Campaign / Drop area colouring could be different?
![image](https://user-images.githubusercontent.com/224748/204687160-a5be630a-1cec-42dc-8897-ad9a28b7fb16.png)
_At a glance_, it's not 100% clear (to me) that I'm not currently idling for anything.

P.P.S.: I feel being able to resize the left side of the UI would be neat too. At present we can change the horizontal width of the right side, but I'd have more of a use case for making the log (Output) area bigger. Actually I'd like Output as a full-width panel below the rest of the UI (with Channels getting less space)...

**Comment by DevilXD** [comment]
> Sometimes the 'Game' shown for the listed streamer on the right UI side in 'Channels' does not match what you are expecting to be idling.

This shouldn't ever be the case, as you cannot earn drops for a different game, other than the one the person is playing. How did you arrive at this conclusion?

Regarding the rest of the suggestions, they look perfectly fine. I can add the current game to the left of the "Campaign: ..." display on the top part of the campaign progress section. Message can be "Claimed drop: Game: Drop_name (X/Y)". When idling, the progress bars remains showing the last UI update before the state switch, but I can make it so they're cleared when the miner switches to the `IDLE` state easily.

**Comment by DevilXD** [comment]
@ThisIsCyreX Good catch, cheers 👍

**Comment by DevilXD** [comment]
How are these?

![obraz](https://user-images.githubusercontent.com/4180725/204775653-ecfd2fa7-3ea8-432c-91f7-fff8448fd730.png)
![obraz](https://user-images.githubusercontent.com/4180725/204775364-6571e881-3088-4d0f-b3f7-e91c99e374a3.png)

**Comment by DevilXD** [comment]
Timestamps can be tricky because not all messages span a single line only, but should still be doable. Is the `HH:MM:SS: Message` format enough? I don't want the line to be too long because of the timestamp.

**Comment by DevilXD** [comment]
I feel like I've implemented everything from this issue now. The only thing that might be missing is the ability to vertically resize the channel list section of the main tab, but I've leaving it as unimplemented for now. If someone would like to see this as a feature, they can open a new issue. I'll probably implement it anyway at some point, but for now, just don't want to delay `v15` release any more than I have to.

**Comment by DevilXD** [comment]
This is now a part of the `v15` release. If you'd like to suggest more changes than currently exist, please open another issue.
