### ISSUE TITLE
Where can i set a time to reload the drop chanel when none.Thx.

### ISSUE THREAD

**Issue by metachos** [DevilXD/TwitchDropsMiner#91]

**Comment by DevilXD** [comment]
Hello o/

The reloading process is automatic, triggered once every up to one hour. Triggers earlier than an hour are also possible, given there's a campaign that starts earlier than the next trigger is supposed to happen. A reload can also be manually triggered by pressing the button on the Settings tab.

**Comment by metachos** [comment]
Thx.Its work.
