### ISSUE TITLE
请问这个软件可以实现多账号同时挂twitch掉宝活动吗

### ISSUE THREAD

**Issue by afasfef** [DevilXD/TwitchDropsMiner#92]
请问这个软件可以实现多账号同时挂twitch掉宝活动吗

**Comment by Suz1e** [comment]
no

**Comment by DevilXD** [comment]
@afasfef Sorry, I don't speak Chinese, or whatever that language is. By google translate, if you're asking about adding support for multiple accounts, there's already an issue open at #31 for this.
