### ISSUE TITLE
integrity ip mismatched

### ISSUE THREAD

**Issue by shenzhuangzhi1** [DevilXD/TwitchDropsMiner#95]
when i login in , i met a error:

integrity ip mismatched

the response is that :
{"error_code":5028,"error_description":"integrity ip mismatched"}
so, what should i do ?

**Comment by DevilXD** [comment]
Hello o/

Which version you're using and what is the actual output? There's nothing in the current master branch that'd print out such an error.

**Comment by shenzhuangzhi1** [comment]
> Hello o/
> 
> Which version you're using and what is the actual output? There's nothing in the current master branch that'd print out such an error.

actually， i use least chrome, but with proxy, if the error about the proxy?
