### ISSUE TITLE
Login error code: 5024

### ISSUE THREAD

**Issue by Huiaei** [DevilXD/TwitchDropsMiner#98]
I encountered a situation where I could not log in. Here are the logs.

```
09:18:02: Please log in to continue.
09:18:10: Login error code: 5024
09:18:10: Your login attempt was denied by CAPTCHA.
09:18:10: Please try again in 12+ hours.
09:18:10: Exiting...
09:18:11: 
09:18:11: Application Terminated.
09:18:11: Close the window to exit the application.
```

The ones already logged in are working properly, but new logins are not available. I tried the browser and the login for the relevant account is working fine.

**Comment by Suz1e** [comment]
This is usually caused by logging into multiple accounts, Twitch has made restrictions on this, and it also tells you that it takes at least 12 hours
