### ISSUE TITLE
I have been unable to log in my twitch. Please help me

### ISSUE THREAD

**Issue by shen890208** [DevilXD/TwitchDropsMiner#99]
![1](https://user-images.githubusercontent.com/120549339/207523920-d23b2081-aa37-4424-90ec-9c35b33356dd.JPG)

**Comment by DevilXD** [comment]
Hello o/

It looks like you're using version `v14`, which broke when the issue #68 was reported. The latest `v15`, which is still in development, fixes this issue already, It looks like Twitch has finally fixed the error being reported in JSON twice, and the decoder no longer complains with the exact same error as #68 says, but the underlying issue preventing you from logging in is the same..

You can compile and use the latest `v15.dev` yourself by following these instructions: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running

Or you can just wait for an official `v15` release, in the nearest future.

**Comment by koghzera** [comment]
> Hello o/
> 
> It looks like you're using version `v14`, which broke when the issue #68 was reported. The latest `v15`, which is still in development, fixes this issue already, It looks like Twitch has finally fixed the error being reported in JSON twice, and the decoder no longer complains with the exact same error as #68 says, but the underlying issue preventing you from logging in is the same..
> 
> You can compile and use the latest `v15.dev` yourself by following these instructions: https://github.com/DevilXD/TwitchDropsMiner/wiki/Setting-up-the-environment,-building-and-running
> 
> Or you can just wait for an official `v15` release, in the nearest future.

Hello @DevilXD , i know its an work in progress, but compiling the v15 im getting 5024 error code. 
Thanks for the great work!

**Comment by DevilXD** [comment]
> im getting 5024 error code.

If the compiled version doesn't crash anymore, then this issue can be closed. Getting any `5XXX` login error code is normal and already handled properly - you should get the same message as in #98. Both 5023 and 5024 have the same solution - just wait a bit and try again later. It working or not is independent of anything I can do.

**Comment by Huiaei** [comment]
>  Both 5023 and 5024 have the same solution - just wait a bit and try again later.

I waited for 12 hours as prompted and tried again, but an error still occurred. It is the same result to open only one program without using multiple accounts.
At first, I thought it might be a problem with the proxy server, but the browser web login was still normal.
The user who has logged in a cookie file before can still use it normally. Due to constant errors, I try to manually generate cookie. jar directly, but this file cannot be opened normally. Maybe I can convert it to cookie. jar through the EditThisCookies plug-in, but I don't know how to do it.
Because #98 is locked, I have to reply here.

**Comment by Kottonye** [comment]
> > Both 5023 and 5024 have the same solution - just wait a bit and try again later.
> 
> I waited for 12 hours as prompted and tried again, but an error still occurred. It is the same result to open only one program without using multiple accounts. At first, I thought it might be a problem with the proxy server, but the browser web login was still normal. The user who has logged in a cookie file before can still use it normally. Due to constant errors, I try to manually generate cookie. jar directly, but this file cannot be opened normally. Maybe I can convert it to cookie. jar through the EditThisCookies plug-in, but I don't know how to do it. Because #98 is locked, I have to reply here.

Yeah, I've been having the same problem. Can't log in even after the 12 hours passed, using only one account though. Password is correct, user is correct, 2FA is correct. Maybe pulling cookies from your browser would bypass captcha?
